<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><title>Informe clínico RI</title>
<style>@page{margin:28px 34px}body{font-family:DejaVu Sans,sans-serif;color:#24343a;font-size:9.5px;line-height:1.45}.brand{color:#315a91;font-size:9px;font-weight:bold;letter-spacing:1.2px}.header{border-bottom:3px solid #4776b5;padding-bottom:12px}.header h1{font-size:22px;margin:4px 0;color:#1d3d68}.meta{color:#687986}.hero{margin:14px 0;padding:14px;background:#edf4fc;border-radius:8px}.hero strong{font-size:18px;color:#315a91}.status{float:right;padding:5px 9px;background:#fff;border:1px solid #95b1d5;border-radius:12px}h2{font-size:12px;color:#315a91;border-bottom:1px solid #c2d3e8;padding-bottom:4px;margin:15px 0 7px}table{width:100%;border-collapse:collapse;margin:5px 0}td,th{border:1px solid #d7e0eb;padding:5px 6px;text-align:left}th{background:#f3f6fa;color:#3c536f}.label{font-size:8px;text-transform:uppercase;color:#687986}.value{font-size:11px;font-weight:bold}.metric{display:inline-block;width:21%;margin:2px;padding:8px;background:#f4f7fb;border-top:4px solid #4776b5}.bar{height:11px;background:#e1e8f1;border-radius:6px}.fill{height:11px;background:#4776b5;border-radius:6px}.note{padding:9px;background:#fff8df;border:1px solid #e3cb75}.footer{position:fixed;bottom:-15px;left:0;right:0;text-align:center;color:#788793;font-size:8px}ul{padding-left:17px;margin:4px 0}.signature{margin-top:28px;width:45%;border-top:1px solid #687986;padding-top:5px;text-align:center}</style></head><body>
<div class="header"><div class="brand">PMOS · SALUD METABÓLICA INTEGRAL</div><h1>Informe de resistencia a la insulina</h1><div class="meta">Documento individual · Generado {{ $fechaGeneracion->format('d/m/Y H:i') }}</div></div>
<div class="hero"><span class="status">{{ ucfirst($ri->estado_validacion_experta ?? 'pendiente') }}</span><div class="label">Resultado diagnóstico</div><strong>{{ $ri->resistencia_confirmada ? 'Resistencia a la insulina confirmada' : 'Resistencia no confirmada' }}</strong><div>Grado {{ $ri->grado_resistencia ?: 'no clasificado' }} · Riesgo cardiometabólico {{ $ri->riesgo_cardiometabolico ?: 'no evaluado' }}</div></div>
<h2>Identificación y responsable clínico</h2><table><tr><th>Paciente</th><td>{{ trim($paciente->nombres.' '.$paciente->apellido_paterno.' '.$paciente->apellido_materno) }}</td><th>CI</th><td>{{ $paciente->ci ?: 'N/D' }}</td></tr><tr><th>Edad</th><td>{{ $paciente->fecha_nacimiento?->age ?? 'N/D' }}</td><th>Fecha diagnóstico</th><td>{{ $ri->fecha_diagnostico?->format('d/m/Y') }}</td></tr><tr><th>Endocrinólogo</th><td colspan="3">{{ $endocrinologo?->name ?? 'No registrado' }}</td></tr></table>
<h2>Biomarcadores metabólicos</h2><div class="metric"><div class="label">HOMA-IR</div><div class="value">{{ $ri->homa_ir ?? $glucosa?->homa_ir ?? 'N/D' }}</div></div><div class="metric"><div class="label">QUICKI</div><div class="value">{{ $ri->quicki ?? 'N/D' }}</div></div><div class="metric"><div class="label">Glucosa ayunas</div><div class="value">{{ $ri->glucosa_ayunas ?? $glucosa?->glucosa_ayunas ?? 'N/D' }} mg/dL</div></div><div class="metric"><div class="label">Insulina ayunas</div><div class="value">{{ $ri->insulina_ayunas ?? $glucosa?->insulina_ayunas ?? 'N/D' }} µU/mL</div></div>
<table><tr><th>HbA1c</th><td>{{ $ri->hemoglobina_glicosilada ?? $glucosa?->hemoglobina_glicosilada ?? 'N/D' }}%</td><th>Triglicéridos</th><td>{{ $ri->trigliceridos ?? $lipidos?->trigliceridos ?? 'N/D' }} mg/dL</td></tr><tr><th>HDL</th><td>{{ $ri->hdl ?? $lipidos?->hdl ?? 'N/D' }} mg/dL</td><th>IMC / cintura</th><td>{{ $fisica?->imc ?? 'N/D' }} / {{ $fisica?->circunferencia_cintura ?? 'N/D' }} cm</td></tr><tr><th>Acantosis nigricans</th><td>{{ $fisica?->acantosis_nigricans ? 'Presente' : 'No registrada/ausente' }}</td><th>Grado</th><td>{{ ucfirst($ri->grado_resistencia ?: 'no clasificado') }}</td></tr></table>
<h2>Evidencia utilizada y puntos de corte</h2>
@php
    $homa = is_numeric($ri->homa_ir) ? (float) $ri->homa_ir : null;
    $glucosaAyunas = is_numeric($ri->glucosa_ayunas) ? (float) $ri->glucosa_ayunas : (is_numeric($glucosa?->glucosa_ayunas) ? (float) $glucosa->glucosa_ayunas : null);
    $insulinaAyunas = is_numeric($ri->insulina_ayunas) ? (float) $ri->insulina_ayunas : (is_numeric($glucosa?->insulina_ayunas) ? (float) $glucosa->insulina_ayunas : null);
    $hba1c = is_numeric($ri->hemoglobina_glicosilada) ? (float) $ri->hemoglobina_glicosilada : (is_numeric($glucosa?->hemoglobina_glicosilada) ? (float) $glucosa->hemoglobina_glicosilada : null);
    $tg = is_numeric($ri->trigliceridos) ? (float) $ri->trigliceridos : (is_numeric($lipidos?->trigliceridos) ? (float) $lipidos->trigliceridos : null);
    $hdl = is_numeric($ri->hdl) ? (float) $ri->hdl : (is_numeric($lipidos?->hdl) ? (float) $lipidos->hdl : null);
@endphp
<table><tr><th>Indicador</th><th>Resultado</th><th>Referencia aplicada</th><th>Aporte a la decisión</th></tr><tr><td><b>HOMA-IR</b></td><td>{{ $homa ?? 'N/D' }}</td><td>RI ≥ 2.5 · leve 2.5–2.99 · moderada 3.0–4.99 · severa ≥ 5.0</td><td>{{ $homa === null ? 'Dato no disponible' : ($homa >= 2.5 ? 'Compatible con resistencia a la insulina '.($ri->grado_resistencia ?: '') : 'Por debajo del punto de corte') }}</td></tr><tr><td><b>Glucosa en ayunas</b></td><td>{{ $glucosaAyunas ?? 'N/D' }} mg/dL</td><td>Riesgo elevado ≥ 100 mg/dL</td><td>{{ $glucosaAyunas !== null && $glucosaAyunas >= 100 ? 'Aumenta riesgo de diabetes' : 'No activa este criterio' }}</td></tr><tr><td><b>HbA1c</b></td><td>{{ $hba1c ?? 'N/D' }}%</td><td>Riesgo elevado ≥ 5.7%</td><td>{{ $hba1c !== null && $hba1c >= 5.7 ? 'Aumenta riesgo de diabetes' : 'No activa este criterio' }}</td></tr><tr><td><b>Triglicéridos</b></td><td>{{ $tg ?? 'N/D' }} mg/dL</td><td>Elevados ≥ 150 mg/dL</td><td>{{ $tg !== null && $tg >= 150 ? 'Factor de riesgo cardiometabólico' : 'No activa este criterio' }}</td></tr><tr><td><b>HDL</b></td><td>{{ $hdl ?? 'N/D' }} mg/dL</td><td>Bajo &lt; 50 mg/dL</td><td>{{ $hdl !== null && $hdl < 50 ? 'Factor de riesgo cardiometabólico' : 'No activa este criterio' }}</td></tr></table>
<h3>Cálculos derivados</h3><table><tr><th>Fórmula HOMA-IR</th><td>(glucosa en ayunas × insulina en ayunas) / 405</td><th>Datos sustituidos</th><td>({{ $glucosaAyunas ?? 'N/D' }} × {{ $insulinaAyunas ?? 'N/D' }}) / 405 = {{ $homa ?? 'N/D' }}</td></tr><tr><th>QUICKI</th><td>1 / [log10(glucosa) + log10(insulina)]</td><th>Resultado</th><td>{{ $ri->quicki ?? 'N/D' }}</td></tr></table>
<h3>Hallazgos físicos y antropométricos</h3><table><tr><th>Peso / talla</th><td>{{ $fisica?->peso ?? 'N/D' }} kg / {{ $fisica?->talla ?? 'N/D' }} m</td><th>IMC</th><td>{{ $fisica?->imc ?? 'N/D' }}</td></tr><tr><th>Circunferencia de cintura</th><td>{{ $fisica?->circunferencia_cintura ?? 'N/D' }} cm</td><th>Acantosis nigricans</th><td>{{ $fisica?->acantosis_nigricans ? 'Presente' : 'Ausente/no registrada' }}</td></tr></table>
<div class="note"><b>Fundamento diagnóstico:</b> La resistencia se confirma con HOMA-IR ≥ 2.5. El grado depende de su magnitud. El riesgo de diabetes considera glucosa ≥ 100 mg/dL o HbA1c ≥ 5.7%; el riesgo cardiometabólico integra triglicéridos ≥ 150 mg/dL y HDL &lt; 50 mg/dL.</div>
<h2>Estratificación de riesgo</h2><table><tr><th style="width:28%">Confianza del análisis</th><td><div class="bar"><div class="fill" style="width:{{ min(100, (($ri->confianza_experta ?? 0) <= 1 ? ($ri->confianza_experta ?? 0) * 100 : $ri->confianza_experta)) }}%"></div></div></td><td style="width:10%">{{ round((($ri->confianza_experta ?? 0) <= 1 ? ($ri->confianza_experta ?? 0) * 100 : $ri->confianza_experta)) }}%</td></tr></table><table><tr><th>Riesgo de diabetes</th><td>{{ ucfirst($ri->riesgo_diabetes ?: 'no evaluado') }}</td><th>Riesgo cardiometabólico</th><td>{{ ucfirst($ri->riesgo_cardiometabolico ?: 'no evaluado') }}</td></tr></table>
<h2>Conclusión y plan médico</h2><p><b>Conclusión:</b> {{ $ri->conclusion_medica ?: 'Sin conclusión médica registrada.' }}</p><p><b>Recomendaciones:</b> {{ $ri->recomendaciones_medicas ?: 'Sin recomendaciones médicas registradas.' }}</p>
@if(count($explicacionRi))<h2>Fundamento del análisis asistido</h2><ul>@foreach($explicacionRi as $texto)<li>{{ $texto }}</li>@endforeach</ul>@endif
@if(count($recomendacionesRi))<h2>Orientaciones complementarias</h2><ul>@foreach($recomendacionesRi as $texto)<li>{{ $texto }}</li>@endforeach</ul>@endif
<h2>Validación profesional</h2><table><tr><th>Estado</th><td>{{ ucfirst($ri->estado_validacion_experta ?? 'pendiente') }}</td><th>Fecha</th><td>{{ $ri->fecha_validacion?->format('d/m/Y H:i') ?? 'Pendiente' }}</td></tr><tr><th>Observación</th><td colspan="3">{{ $ri->observacion_validacion ?: 'Sin observaciones.' }}</td></tr></table>
<div class="note"><b>Nota clínica:</b> Los índices metabólicos y el análisis computacional apoyan la decisión profesional; deben interpretarse según contexto, laboratorio y criterio clínico.</div><div class="signature">Firma y sello del endocrinólogo</div><div class="footer">Informe metabólico confidencial · Historia clínica de {{ trim($paciente->nombres.' '.$paciente->apellido_paterno) }}</div>
</body></html>
