<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><title>Informe clínico PMOS</title>
<style>
@page{margin:28px 34px}body{font-family:DejaVu Sans,sans-serif;color:#243632;font-size:9.5px;line-height:1.45}.brand{color:#176b5b;font-size:9px;font-weight:bold;letter-spacing:1.2px}.header{border-bottom:3px solid #1f8a70;padding-bottom:12px}.header h1{font-size:22px;margin:4px 0;color:#123d35}.meta{color:#657a75}.hero{margin:14px 0;padding:14px;background:#eaf7f3;border-radius:8px}.hero strong{font-size:18px;color:#176b5b}.status{float:right;padding:5px 9px;background:#fff;border:1px solid #80bcae;border-radius:12px}h2{font-size:12px;color:#176b5b;border-bottom:1px solid #b9d8d0;padding-bottom:4px;margin:15px 0 7px}table{width:100%;border-collapse:collapse;margin:5px 0}td,th{border:1px solid #d6e2df;padding:5px 6px;text-align:left}th{background:#f2f7f5;color:#365d54}.grid td{width:25%}.label{font-size:8px;text-transform:uppercase;color:#667b76}.value{font-size:11px;font-weight:bold}.bar{height:11px;background:#e0ebe8;border-radius:6px}.fill{height:11px;background:#1f8a70;border-radius:6px}.criterion{display:inline-block;width:29%;margin:2px;padding:8px;background:#f3f8f6;border-left:4px solid #1f8a70}.note{padding:9px;background:#fff8df;border:1px solid #e3cb75}.footer{position:fixed;bottom:-15px;left:0;right:0;text-align:center;color:#78908a;font-size:8px}ul{padding-left:17px;margin:4px 0}.signature{margin-top:28px;width:45%;border-top:1px solid #667b76;padding-top:5px;text-align:center}
</style></head><body>
<div class="header"><div class="brand">PMOS · SALUD ENDOCRINA INTEGRAL</div><h1>Informe clínico de síndrome de ovario poliquístico</h1><div class="meta">Documento individual · Generado {{ $fechaGeneracion->format('d/m/Y H:i') }}</div></div>
<div class="hero"><span class="status">{{ ucfirst($pmos->estado_validacion_experta ?? 'pendiente') }}</span><div class="label">Resultado diagnóstico</div><strong>{{ $pmos->diagnostico_confirmado ? 'Compatible con PMOS' : 'PMOS no confirmado' }}</strong><div>Fenotipo {{ $pmos->fenotipo_pmos ?: 'no clasificado' }} · {{ $pmos->total_criterios_rotterdam }}/3 criterios de Rotterdam</div></div>
<h2>Identificación y responsable clínico</h2><table class="grid"><tr><td><div class="label">Paciente</div><div class="value">{{ trim($paciente->nombres.' '.$paciente->apellido_paterno.' '.$paciente->apellido_materno) }}</div></td><td><div class="label">CI</div><div class="value">{{ $paciente->ci ?: 'N/D' }}</div></td><td><div class="label">Edad</div><div class="value">{{ $paciente->fecha_nacimiento?->age ?? 'N/D' }}</div></td><td><div class="label">Fecha diagnóstico</div><div class="value">{{ $pmos->fecha_diagnostico?->format('d/m/Y') }}</div></td></tr></table>
<p><b>Endocrinólogo:</b> {{ $endocrinologo?->name ?? 'No registrado' }}</p>
<h2>Perfil diagnóstico</h2><table><tr><th>Fenotipo</th><td>{{ $pmos->fenotipo_pmos ?: 'No clasificado' }}</td><th>Severidad</th><td>{{ str_replace('_',' ',ucfirst($pmos->severidad_clinica ?: 'no clasificada')) }}</td></tr><tr><th>Riesgo metabólico</th><td>{{ str_replace('_',' ',ucfirst($pmos->riesgo_metabolico ?: 'no evaluado')) }}</td><th>Hiperandrogenismo</th><td>{{ str_replace('_',' ',ucfirst($pmos->tipo_hiperandrogenismo ?: 'no clasificado')) }}</td></tr></table>
<h2>Criterios de Rotterdam</h2><div class="criterion"><b>{{ $pmos->cumple_alteracion_ovulatoria ? '✓' : '—' }} Alteración ovulatoria</b><br>{{ $historiaMenstrual?->regularidad_ciclo ? 'Ciclo '.$historiaMenstrual->regularidad_ciclo : 'Sin detalle menstrual' }}</div><div class="criterion"><b>{{ $pmos->cumple_hiperandrogenismo ? '✓' : '—' }} Hiperandrogenismo</b><br>{{ $pmos->tipo_hiperandrogenismo ?: 'No identificado' }}</div><div class="criterion"><b>{{ $pmos->cumple_morfologia_ovarica ? '✓' : '—' }} Morfología ovárica</b><br>{{ $ecografia?->morfologia_compatible_pmos ? 'Ecografía compatible' : 'No compatible/no registrada' }}</div>
<h2>Evidencia clínica utilizada</h2>
<h3>1. Función ovulatoria e historia menstrual</h3>
<table><tr><th>Regularidad del ciclo</th><td>{{ $historiaMenstrual?->regularidad_ciclo ? ucfirst($historiaMenstrual->regularidad_ciclo) : 'No registrada' }}</td><th>Duración / intervalo</th><td>{{ $historiaMenstrual?->duracion_ciclo_dias ?? 'N/D' }} / {{ $historiaMenstrual?->intervalo_entre_ciclos_dias ?? 'N/D' }} días</td></tr><tr><th>Amenorrea</th><td>{{ $historiaMenstrual?->amenorrea ? 'Sí' : 'No' }}</td><th>Oligomenorrea</th><td>{{ $historiaMenstrual?->oligomenorrea ? 'Sí' : 'No' }}</td></tr><tr><th>Sospecha de anovulación</th><td>{{ $historiaMenstrual?->sospecha_anovulacion ? 'Sí' : 'No' }}</td><th>Progesterona lútea</th><td>{{ $historiaMenstrual?->progesterona_lutea ?? 'N/D' }}</td></tr></table>
<h3>2. Evidencia de hiperandrogenismo</h3>
<table><tr><th>Acné / grado</th><td>{{ $historiaHiperandrogenica?->acne ? 'Sí · '.($historiaHiperandrogenica->acne_grado ?: 'sin grado') : 'No' }}</td><th>Hirsutismo</th><td>{{ $historiaHiperandrogenica?->hirsutismo ? 'Sí' : 'No' }}</td></tr><tr><th>Ferriman-Gallwey</th><td>{{ $historiaHiperandrogenica?->puntaje_ferriman_gallwey ?? 'N/D' }}</td><th>Bioquímico</th><td>{{ $pmos->cumple_hiperandrogenismo_bioquimico ? 'Positivo' : 'No documentado/negativo' }}</td></tr><tr><th>Testosterona total</th><td>{{ $perfilAndrogenico?->testosterona_total ?? 'N/D' }}</td><th>Testosterona libre</th><td>{{ $perfilAndrogenico?->testosterona_libre ?? 'N/D' }}</td></tr><tr><th>SHBG</th><td>{{ $perfilAndrogenico?->shbg ?? 'N/D' }}</td><th>Índice androgénico libre</th><td>{{ $perfilAndrogenico?->indice_androgenico_libre ?? 'N/D' }}</td></tr></table>
<h3>3. Evidencia ecográfica</h3>
<table><tr><th>Fecha / tipo</th><td>{{ $ecografia?->fecha_ecografia?->format('d/m/Y') ?? 'N/D' }} · {{ $ecografia?->tipo_ecografia ?? 'N/D' }}</td><th>Morfología compatible</th><td>{{ $ecografia?->morfologia_compatible_pmos ? 'Sí' : 'No' }}</td></tr><tr><th>Volumen ovárico D/I</th><td>{{ $ecografia?->volumen_ovario_derecho ?? 'N/D' }} / {{ $ecografia?->volumen_ovario_izquierdo ?? 'N/D' }} mL</td><th>Folículos D/I</th><td>{{ $ecografia?->foliculos_ovario_derecho ?? 'N/D' }} / {{ $ecografia?->foliculos_ovario_izquierdo ?? 'N/D' }}</td></tr></table>
<h3>4. Descarte de causas alternativas</h3>
<table><tr><th>Función tiroidea</th><td>{{ $diferencial?->alteracion_tiroidea_descartada ? 'Descartada' : 'Pendiente' }} · TSH {{ $diferencial?->tsh ?? 'N/D' }}</td><th>Hiperprolactinemia</th><td>{{ $diferencial?->hiperprolactinemia_descartada ? 'Descartada' : 'Pendiente' }} · PRL {{ $diferencial?->prolactina ?? 'N/D' }}</td></tr><tr><th>Hiperplasia suprarrenal</th><td>{{ $diferencial?->hiperplasia_suprarrenal_descartada ? 'Descartada' : 'Pendiente' }} · 17-OHP {{ $diferencial?->diecisiete_oh_progesterona ?? 'N/D' }}</td><th>Síndrome de Cushing</th><td>{{ $diferencial?->cushing_descartado ? 'Descartado' : 'Pendiente' }} · Cortisol {{ $diferencial?->cortisol ?? 'N/D' }}</td></tr></table>
<div class="notice"><b>Fundamento diagnóstico:</b> Rotterdam requiere al menos 2 de 3 criterios (alteración ovulatoria, hiperandrogenismo y morfología ovárica) después de excluir causas alternativas. En esta evaluación se documentaron <b>{{ $pmos->total_criterios_rotterdam }} de 3</b> criterios y el descarte diferencial figura como <b>{{ $pmos->diagnosticos_diferenciales_descartados ? 'completo' : 'pendiente' }}</b>.</div>
<h2>Indicadores visuales</h2><table><tr><th style="width:28%">Criterios Rotterdam</th><td><div class="bar"><div class="fill" style="width:{{ min(100, ($pmos->total_criterios_rotterdam / 3) * 100) }}%"></div></div></td><td style="width:10%">{{ $pmos->total_criterios_rotterdam }}/3</td></tr><tr><th>Confianza del análisis</th><td><div class="bar"><div class="fill" style="width:{{ min(100, (($pmos->confianza_experta ?? 0) <= 1 ? ($pmos->confianza_experta ?? 0) * 100 : $pmos->confianza_experta)) }}%"></div></div></td><td>{{ round((($pmos->confianza_experta ?? 0) <= 1 ? ($pmos->confianza_experta ?? 0) * 100 : $pmos->confianza_experta)) }}%</td></tr></table>
<h2>Conclusión y plan médico</h2><p><b>Conclusión:</b> {{ $pmos->conclusion_medica ?: 'Sin conclusión médica registrada.' }}</p><p><b>Recomendaciones:</b> {{ $pmos->recomendaciones_medicas ?: 'Sin recomendaciones médicas registradas.' }}</p>
@if(count($explicacionPmos))<h2>Fundamento del análisis asistido</h2><ul>@foreach($explicacionPmos as $texto)<li>{{ $texto }}</li>@endforeach</ul>@endif
@if(count($recomendacionesPmos))<h2>Orientaciones complementarias</h2><ul>@foreach($recomendacionesPmos as $texto)<li>{{ $texto }}</li>@endforeach</ul>@endif
<h2>Validación profesional</h2><table><tr><th>Estado</th><td>{{ ucfirst($pmos->estado_validacion_experta ?? 'pendiente') }}</td><th>Fecha</th><td>{{ $pmos->fecha_validacion?->format('d/m/Y H:i') ?? 'Pendiente' }}</td></tr><tr><th>Observación</th><td colspan="3">{{ $pmos->observacion_validacion ?: 'Sin observaciones.' }}</td></tr></table>
<div class="note"><b>Nota clínica:</b> El análisis computacional constituye apoyo a la decisión. El diagnóstico y tratamiento final son responsabilidad del profesional tratante.</div><div class="signature">Firma y sello del endocrinólogo</div><div class="footer">Informe PMOS confidencial · Historia clínica de {{ trim($paciente->nombres.' '.$paciente->apellido_paterno) }}</div>
</body></html>
