import { SlidersHorizontal } from 'lucide-react';

interface Item {nombre:string;motivo?:string}
export interface ContextoAjustePlan {id_plan_considerado:number|null;nombre_plan_considerado:string|null;recetas_bien_aceptadas:Item[];recetas_a_evitar:Item[];ingredientes_no_conseguidos:Item[];necesita_mas_saciedad:Record<string,boolean>;recomendaciones_nutricionista:string[];resumen_ajuste:string[];hambre_nocturna_frecuente:boolean;ansiedad_comida_frecuente:boolean;antojos_dulces_frecuentes:boolean;hinchazon_frecuente:boolean}
export default function ResumenAjustePlanCard({contexto}:{contexto:ContextoAjustePlan}){
 if(!contexto.id_plan_considerado&&contexto.resumen_ajuste.length===0)return null;
 const sintomas=[contexto.hambre_nocturna_frecuente&&'Hambre nocturna',contexto.ansiedad_comida_frecuente&&'Ansiedad por comida',contexto.antojos_dulces_frecuentes&&'Antojos dulces',contexto.hinchazon_frecuente&&'Hinchazón'].filter(Boolean) as string[];
 return <div className="card-elevated p-5"><div className="flex items-center gap-2"><SlidersHorizontal className="text-primary" size={19}/><div><h3 className="font-bold">Contexto para el siguiente plan</h3><p className="text-sm text-base-content/60">El próximo plan considerará el seguimiento reciente del paciente.</p></div></div><div className="mt-4 grid gap-4 md:grid-cols-2"><Lista titulo="Recetas favorecidas" items={contexto.recetas_bien_aceptadas.map(x=>x.nombre)} clase="badge-success"/><Lista titulo="Recetas a evitar o revisar" items={contexto.recetas_a_evitar.map(x=>x.nombre)} clase="badge-error"/><Lista titulo="Necesitan mayor saciedad" items={Object.keys(contexto.necesita_mas_saciedad)} clase="badge-warning"/><Lista titulo="Síntomas considerados" items={sintomas} clase="badge-warning"/></div>{contexto.recomendaciones_nutricionista.length>0&&<div className="mt-4"><h4 className="text-xs font-bold uppercase text-base-content/55">Recomendaciones profesionales consideradas</h4><ul className="mt-2 list-disc space-y-1 pl-5 text-sm">{contexto.recomendaciones_nutricionista.slice(0,5).map(x=><li key={x}>{x}</li>)}</ul></div>}</div>
}
function Lista({titulo,items,clase}:{titulo:string;items:string[];clase:string}){return <div><h4 className="text-xs font-bold uppercase text-base-content/55">{titulo}</h4><div className="mt-2 flex flex-wrap gap-2">{items.length?items.map(x=><span className={`badge ${clase}`} key={x}>{x}</span>):<span className="text-sm text-base-content/45">Sin registros.</span>}</div></div>}
