import { router } from '@inertiajs/react';
import { MessageSquareText, Send } from 'lucide-react';
import { FormEvent, useState } from 'react';

export interface RetroalimentacionHistorial { id_retroalimentacion_paciente:number;tipo_retroalimentacion:string;prioridad:string;mensaje:string;visible_para_paciente:boolean;leido_por_paciente:boolean;fecha_lectura_paciente:string|null;created_at:string|null;profesional:string|null;estado:string }
export default function RetroalimentacionPacientePanel({pacienteId,planId,historial}:{pacienteId:number;planId?:number|null;historial:RetroalimentacionHistorial[]}){
 const [tipo,setTipo]=useState('recomendacion_general'),[prioridad,setPrioridad]=useState('normal'),[mensaje,setMensaje]=useState(''),[visible,setVisible]=useState(true),[enviando,setEnviando]=useState(false),[error,setError]=useState<string|null>(null),[exito,setExito]=useState<string|null>(null);
 const enviar=async(e:FormEvent)=>{e.preventDefault();setEnviando(true);setError(null);setExito(null);try{const token=document.querySelector<HTMLMetaElement>('meta[name="csrf-token"]')?.content??'';const r=await fetch(`/nutricionista/pacientes/${pacienteId}/retroalimentaciones`,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':token},body:JSON.stringify({tipo_retroalimentacion:tipo,prioridad,mensaje,visible_para_paciente:visible,id_plan_alimentario:planId??null})});const data=await r.json();if(!r.ok)throw new Error(r.status===422?'Revisa los datos de la retroalimentación.':data.message??'No se pudo enviar.');setMensaje('');setExito(data.message);router.reload({only:['retroalimentacionesPaciente']});}catch(x){setError(x instanceof Error?x.message:'No se pudo enviar la retroalimentación.')}finally{setEnviando(false)}};
 return <div className="card-elevated p-5"><div className="flex items-center gap-2"><MessageSquareText className="text-primary" size={20}/><h3 className="text-lg font-bold">Enviar retroalimentación al paciente</h3></div><p className="mt-1 text-sm text-base-content/60">Orientación profesional basada en el seguimiento registrado.</p><form onSubmit={enviar} className="mt-4 space-y-3"><div className="grid gap-3 sm:grid-cols-2"><label className="form-control"><span className="label-text mb-1 text-xs font-bold">Tipo</span><select className="select select-bordered" value={tipo} onChange={e=>setTipo(e.target.value)}>{['comida','sintomas','adherencia','recomendacion_general','ajuste_plan','recordatorio'].map(x=><option key={x} value={x}>{x.replaceAll('_',' ')}</option>)}</select></label><label className="form-control"><span className="label-text mb-1 text-xs font-bold">Prioridad</span><select className="select select-bordered" value={prioridad} onChange={e=>setPrioridad(e.target.value)}>{['baja','normal','alta'].map(x=><option key={x}>{x}</option>)}</select></label></div><label className="form-control"><span className="label-text mb-1 text-xs font-bold">Mensaje</span><textarea required maxLength={1500} className="textarea textarea-bordered min-h-28" placeholder="Escribe una orientación clara y profesional..." value={mensaje} onChange={e=>setMensaje(e.target.value)}/><span className="mt-1 text-right text-xs text-base-content/45">{mensaje.length}/1500</span></label><label className="label w-fit cursor-pointer gap-3"><input type="checkbox" className="checkbox checkbox-primary" checked={visible} onChange={e=>setVisible(e.target.checked)}/><span className="label-text">Visible para el paciente</span></label>{error&&<div className="alert alert-error py-2 text-sm">{error}</div>}{exito&&<div className="alert alert-success py-2 text-sm">{exito}</div>}<button className="btn btn-primary" disabled={enviando||!mensaje.trim()}><Send size={16}/>{enviando?'Enviando...':'Enviar retroalimentación'}</button></form><div className="divider">Historial reciente</div>{historial.length===0?<p className="text-sm text-base-content/50">Todavía no se enviaron retroalimentaciones.</p>:<div className="space-y-2">{historial.map(x=><article className="rounded-xl border border-base-300 p-3" key={x.id_retroalimentacion_paciente}><div className="flex flex-wrap gap-2"><span className="badge badge-outline capitalize">{x.tipo_retroalimentacion.replaceAll('_',' ')}</span><span className={`badge ${x.prioridad==='alta'?'badge-error':x.prioridad==='baja'?'badge-ghost':'badge-warning'}`}>{x.prioridad}</span><span className={`badge ${x.leido_por_paciente?'badge-success':'badge-ghost'}`}>{x.leido_por_paciente?'Leído':'No leído'}</span></div><p className="mt-2 text-sm">{x.mensaje}</p><p className="mt-2 text-xs text-base-content/45">{x.created_at?new Date(x.created_at).toLocaleString('es-BO'):'Sin fecha'} · {x.visible_para_paciente?'Visible':'Oculto'}</p></article>)}</div>}</div>
}
