import { AlertTriangle, ClipboardList, HeartPulse, Utensils } from 'lucide-react';
import type { SeguimientoPacienteNutricionista } from '@/Pages/Nutricionista/Pacientes/PerfilNutricional/tipos';

const texto = (v: unknown) => v === null || v === undefined || v === '' ? 'Sin registro' : String(v).replaceAll('_', ' ');
const color: Record<string,string> = {completada:'badge-success',parcial:'badge-warning',no_realizada:'badge-error',reemplazada:'badge-info',pendiente:'badge-ghost'};

export default function SeguimientoPacientePanel({seguimiento}:{seguimiento:SeguimientoPacienteNutricionista}) {
    if (!seguimiento.plan || !seguimiento.resumen_adherencia) return <div className="card-elevated p-6 text-center"><ClipboardList className="mx-auto mb-2 text-base-content/30"/><h3 className="font-bold">Sin plan activo para seguimiento</h3><p className="text-sm text-base-content/60">Este panel se habilitará con un plan aprobado o activo.</p></div>;
    const r=seguimiento.resumen_adherencia, i=seguimiento.indicadores_siguiente_plan, s=seguimiento.seguimiento_sintomas.indicadores;
    const alertas=[r.porcentaje_adherencia<60&&'La adherencia general está por debajo del 60%.',r.no_realizadas>0&&`Hay ${r.no_realizadas} comida(s) no realizada(s).`,i.hambre_frecuente>0&&'Se reportó hambre posterior o ansiedad.',s.alerta_general===true&&'Existen síntomas frecuentes que requieren revisión.'].filter(Boolean) as string[];
    return <div className="space-y-4">
        <div className="card-elevated p-5"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="text-lg font-bold">Seguimiento del paciente</h3><p className="text-sm text-base-content/60">{seguimiento.plan.nombre} · {texto(seguimiento.plan.estado_plan)}</p></div><div className="text-right"><b className="block text-3xl text-primary">{r.porcentaje_adherencia}%</b><span className="text-xs text-base-content/60">adherencia general</span></div></div><progress className="progress progress-primary mt-4 w-full" value={r.porcentaje_adherencia} max="100"/><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-5">{[['Completadas',r.completadas],['Parciales',r.parciales],['No realizadas',r.no_realizadas],['Reemplazadas',r.reemplazadas],['Pendientes',r.pendientes]].map(([l,v])=><div className="rounded-xl bg-base-200 p-3 text-center" key={String(l)}><b className="block text-lg">{v}</b><span className="text-xs text-base-content/60">{l}</span></div>)}</div></div>
        {alertas.length>0&&<div className="alert alert-warning items-start"><AlertTriangle size={20}/><div><b>Aspectos que requieren atención</b><ul className="list-disc pl-5 text-sm">{alertas.map(a=><li key={a}>{a}</li>)}</ul></div></div>}
        <div className="grid gap-3 md:grid-cols-4">{Object.entries(seguimiento.adherencia_por_tipo_comida).map(([tipo,d])=><div className="card-elevated p-4" key={tipo}><h4 className="flex items-center gap-2 font-bold capitalize"><Utensils size={15}/>{texto(tipo)}</h4><b className="mt-2 block text-2xl">{d.porcentaje_adherencia}%</b><progress className="progress progress-primary w-full" value={d.porcentaje_adherencia} max="100"/><p className="text-xs text-base-content/60">{d.completadas} completas · {d.pendientes} pendientes</p></div>)}</div>
        <div className="grid gap-4 lg:grid-cols-2"><div className="card-elevated p-5"><h4 className="font-bold">Indicadores para el siguiente plan</h4><Lista titulo="Bien aceptadas" items={i.recetas_bien_aceptadas}/><Lista titulo="Evitar o revisar" items={i.recetas_a_evitar}/><Lista titulo="Preparaciones problemáticas" items={i.alimentos_o_preparaciones_problematicas}/><Lista titulo="Recomendaciones" items={i.recomendaciones_para_nutricionista}/></div><div className="card-elevated p-5"><h4 className="flex items-center gap-2 font-bold"><HeartPulse size={17}/>Síntomas recientes</h4><div className="mt-3 flex flex-wrap gap-2">{Object.entries(s).filter(([,v])=>v===true).map(([k])=><span className="badge badge-warning h-auto py-2" key={k}>{texto(k)}</span>)}</div>{Array.isArray(s.recomendaciones_para_nutricionista)&&<Lista titulo="Recomendaciones" items={s.recomendaciones_para_nutricionista as string[]}/>}<p className="mt-3 text-xs text-base-content/60">{texto(s.registros_ultimos_7_dias)} registro(s) recientes.</p></div></div>
        <div className="card-elevated p-5"><h4 className="mb-3 font-bold">Detalle diario reportado</h4><div className="space-y-2">{seguimiento.seguimiento_comidas.map(d=><details className="collapse collapse-arrow border border-base-300" key={d.id_dia_plan_alimentario}><summary className="collapse-title font-semibold">Día {d.numero_dia} · {d.nombre_dia} {d.fecha?`· ${d.fecha}`:''}</summary><div className="collapse-content grid gap-3 md:grid-cols-2">{d.comidas.map(c=><article className="rounded-xl border border-base-300 p-4" key={c.id_comida_plan_alimentario}><div className="flex justify-between gap-2"><div><b className="capitalize">{texto(c.tipo_comida)}</b><p className="text-xs text-base-content/60">{c.hora_sugerida} · {c.componentes.join(', ')||c.nombre_comida}</p></div><span className={`badge ${color[c.estado_cumplimiento]??'badge-ghost'}`}>{texto(c.estado_cumplimiento)}</span></div><dl className="mt-3 grid grid-cols-2 gap-2 text-xs"><Dato l="Consumido" v={c.porcentaje_consumido===null?null:`${c.porcentaje_consumido}%`}/><Dato l="Agrado" v={c.nivel_agrado}/><Dato l="Saciedad" v={c.nivel_saciedad}/><Dato l="Hambre posterior" v={c.nivel_hambre_posterior}/><Dato l="Molestia" v={c.presento_molestia===null?null:c.presento_molestia?`${texto(c.tipo_molestia)} (${texto(c.intensidad_molestia)})`:'No'}/><Dato l="Ingredientes" v={c.consiguio_ingredientes===null?null:c.consiguio_ingredientes?'Sí':'No'}/></dl>{(c.comentario_paciente||c.sugerencia_paciente)&&<div className="mt-3 rounded-lg bg-base-200 p-3 text-xs"><p><b>Comentario:</b> {texto(c.comentario_paciente)}</p><p><b>Sugerencia:</b> {texto(c.sugerencia_paciente)}</p></div>}</article>)}</div></details>)}</div></div>
    </div>;
}
function Lista({titulo,items}:{titulo:string;items:string[]}){return <div className="mt-4"><p className="text-xs font-bold uppercase text-base-content/55">{titulo}</p>{items.length?<div className="mt-2 flex flex-wrap gap-2">{items.map(x=><span className="badge badge-outline h-auto py-2" key={x}>{x}</span>)}</div>:<p className="mt-1 text-sm text-base-content/45">Sin registros.</p>}</div>}
function Dato({l,v}:{l:string;v:unknown}){return <div><dt className="text-base-content/50">{l}</dt><dd className="font-medium">{texto(v)}</dd></div>}
