import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, router } from '@inertiajs/react';
import { ChevronLeft, ChevronRight, Download, FileBarChart, Salad, Search, ShieldAlert, Users } from 'lucide-react';
import { useState } from 'react';
import clsx from 'clsx';
import AvatarPaciente from '@/Components/ui/avatar-paciente';

interface Definicion { titulo:string; descripcion:string }
interface Reporte { tipo:string;titulo:string;descripcion:string;columnas:Record<string,string>;filas:Record<string,string|number|null>[];resumen:{etiqueta:string;valor:string|number}[];paginacion:{pagina_actual:number;ultima_pagina:number;por_pagina:number;total:number;desde:number;hasta:number} }
interface Props { catalogo:Record<string,Definicion>;reporte:Reporte;filtros:Record<string,string> }
const iconos:Record<string,typeof Users>={pacientes:Users,adherencia:FileBarChart,planes:Salad,incidencias:ShieldAlert};
const niveles={alta:'Alta (85–100%)',media:'Media (50–84%)',baja:'Baja (1–49%)',cero:'Adherencia 0%',sin_registros:'Sin registros'};
const estados={al_dia:'Al día',en_progreso:'En progreso',requiere_atencion:'Requiere atención',sin_registros:'Sin registros'};
const estadosPlan={sugerido:'Sugerido',en_revision:'En revisión',aprobado:'Aprobado',activo:'Activo',rechazado:'Rechazado',finalizado:'Finalizado'};

const utilidad:Record<string,{decision:string;momento:string}>={
 pacientes:{decision:'Organizar la cartera y decidir a quién revisar primero.',momento:'Al iniciar la jornada o preparar controles.'},
 adherencia:{decision:'Explicar con datos cómo se está cumpliendo el plan.',momento:'Durante el seguimiento o al informar avances.'},
 planes:{decision:'Auditar qué se planificó, su vigencia y validación.',momento:'En el control documental de las planificaciones.'},
 incidencias:{decision:'Reconocer barreras y proponer ajustes concretos.',momento:'Antes de una consulta de seguimiento.'},
};

export default function Index({catalogo,reporte,filtros}:Props){
 const[buscar,setBuscar]=useState(filtros.buscar??''),[nivel,setNivel]=useState(filtros.nivel??''),[estado,setEstado]=useState(filtros.estado??''),[estadoPlan,setEstadoPlan]=useState(filtros.estado_plan??''),[desde,setDesde]=useState(filtros.desde??''),[hasta,setHasta]=useState(filtros.hasta??'');
 const parametros=(tipo=reporte.tipo)=>Object.fromEntries(Object.entries({tipo,buscar,nivel,estado,estado_plan:estadoPlan,desde,hasta}).filter(([,v])=>v));
 const elegir=(tipo:string)=>router.get(route('nutricionista.reportes.index'),{tipo},{preserveState:false});
 const aplicar=()=>router.get(route('nutricionista.reportes.index'),parametros(),{preserveState:true,preserveScroll:true});
 const cambiarPagina=(page:number)=>router.get(route('nutricionista.reportes.index'),{...parametros(),page},{preserveState:true,preserveScroll:true});
 const esPlanes=reporte.tipo==='planes';
 const esCartera=reporte.tipo==='pacientes';
 const esIncidencias=reporte.tipo==='incidencias';
 return <AuthenticatedLayout title="Reportes nutricionales"><Head title="Reportes nutricionales"/><main className="space-y-5">
  <section className="card-elevated overflow-hidden border-l-4 border-brand-green">
   <div className="grid gap-5 p-5 lg:grid-cols-[1fr_auto] lg:items-center">
    <div><p className="text-[9px] font-bold uppercase tracking-[.14em] text-brand-green-dark dark:text-brand-green">Centro de apoyo clínico</p><h1 className="mt-1 text-[19px] font-bold text-ink dark:text-ink-dark">Reportes para comprender y decidir</h1><p className="mt-1 max-w-3xl text-[10.5px] leading-relaxed text-ink-muted">Convierte la planificación y el seguimiento registrados en información útil para priorizar pacientes, evaluar resultados, preparar consultas y justificar decisiones nutricionales.</p></div>
    <div className="grid grid-cols-3 gap-2 text-center"><div className="rounded-xl bg-brand-green/[.06] px-3 py-2.5"><b className="text-brand-green-dark dark:text-brand-green">1</b><p className="text-[8.5px] text-ink-muted">Selecciona</p></div><div className="rounded-xl bg-brand-green/[.06] px-3 py-2.5"><b className="text-brand-green-dark dark:text-brand-green">2</b><p className="text-[8.5px] text-ink-muted">Filtra</p></div><div className="rounded-xl bg-brand-green/[.06] px-3 py-2.5"><b className="text-brand-green-dark dark:text-brand-green">3</b><p className="text-[8.5px] text-ink-muted">Documenta</p></div></div>
   </div>
   <div className="border-t border-surface-border bg-black/[.012] px-5 py-2.5 text-[9px] text-ink-muted dark:border-surface-border-dark dark:bg-white/[.015]"><b className="text-ink dark:text-ink-dark">Uso responsable:</b> estos reportes apoyan el criterio profesional y deben interpretarse junto con la valoración clínica.</div>
  </section>
  <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{Object.entries(catalogo).map(([tipo,d])=>{const Icon=iconos[tipo]??FileBarChart,activo=tipo===reporte.tipo;return <button key={tipo} type="button" onClick={()=>elegir(tipo)} className={clsx('rounded-2xl border p-4 text-left transition-all',activo?'border-brand-green/40 bg-brand-green/[0.07] ring-1 ring-brand-green/15':'border-surface-border bg-surface-card hover:border-brand-green/25 dark:border-surface-border-dark dark:bg-surface-card-dark')}><Icon size={17} className={activo?'text-brand-green-dark dark:text-brand-green':'text-ink-muted'}/><h2 className="mt-3 text-[12px] font-bold text-ink dark:text-ink-dark">{d.titulo}</h2><p className="mt-1 text-[9.5px] leading-relaxed text-ink-muted">{d.descripcion}</p></button>})}</section>
  <section className="grid gap-3 rounded-2xl border border-brand-green/20 bg-brand-green/[.035] p-4 md:grid-cols-2"><div><p className="text-[8.5px] font-bold uppercase tracking-wider text-brand-green-dark dark:text-brand-green">Decisión que apoya</p><p className="mt-1 text-[10.5px] font-semibold text-ink dark:text-ink-dark">{utilidad[reporte.tipo]?.decision}</p></div><div><p className="text-[8.5px] font-bold uppercase tracking-wider text-brand-green-dark dark:text-brand-green">Cuándo conviene usarlo</p><p className="mt-1 text-[10.5px] font-semibold text-ink dark:text-ink-dark">{utilidad[reporte.tipo]?.momento}</p></div></section>
  <section className="card-elevated space-y-4 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-[16px] font-bold text-ink dark:text-ink-dark">{reporte.titulo}</h2><p className="text-[10.5px] text-ink-muted">{reporte.descripcion}</p></div><a href={route('nutricionista.reportes.adherencia.pdf',parametros())} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-lg bg-brand-green/15 px-4 py-2.5 text-[11px] font-bold text-brand-green-dark hover:bg-brand-green/25 dark:text-brand-green"><Download size={14}/> Generar PDF ({reporte.paginacion.total})</a></div>
   <div className="grid gap-2 md:grid-cols-2 xl:grid-cols-5"><CampoBuscar value={buscar} onChange={setBuscar}/>{esPlanes?<><Selector label="Estado del plan" value={estadoPlan} onChange={setEstadoPlan} opciones={estadosPlan}/><Fecha label="Desde" value={desde} onChange={setDesde}/><Fecha label="Hasta" value={hasta} onChange={setHasta}/></>:<>{esCartera&&<Selector label="Estado del plan" value={estadoPlan} onChange={setEstadoPlan} opciones={estadosPlan}/>}<Selector label="Nivel de adherencia" value={nivel} onChange={setNivel} opciones={niveles}/><Selector label="Estado de seguimiento" value={estado} onChange={setEstado} opciones={estados}/></>}<div className="flex items-end"><button type="button" onClick={aplicar} className="w-full rounded-lg border border-brand-green/25 bg-brand-green/10 px-4 py-2 text-[11px] font-bold text-brand-green-dark dark:text-brand-green">Aplicar filtros</button></div></div>
   {esCartera&&<div className="grid gap-2 rounded-xl border border-surface-border bg-black/[.01] p-3 dark:border-surface-border-dark dark:bg-white/[.015] md:grid-cols-3"><div><b className="text-[9px] text-ink dark:text-ink-dark">Situación actual</b><p className="mt-0.5 text-[8.5px] text-ink-muted">Plan, vigencia y estado del seguimiento.</p></div><div><b className="text-[9px] text-ink dark:text-ink-dark">Respuesta del paciente</b><p className="mt-0.5 text-[8.5px] text-ink-muted">Adherencia y cantidad de comidas registradas.</p></div><div><b className="text-[9px] text-ink dark:text-ink-dark">Siguiente decisión</b><p className="mt-0.5 text-[8.5px] text-ink-muted">Acción sugerida para orientar la revisión profesional.</p></div></div>}
   {esPlanes&&<div className="grid gap-2 rounded-xl border border-surface-border bg-black/[.01] p-3 dark:border-surface-border-dark dark:bg-white/[.015] md:grid-cols-3"><div><b className="text-[9px] text-ink dark:text-ink-dark">Control documental</b><p className="mt-0.5 text-[8.5px] text-ink-muted">Estado y periodo de cada planificación.</p></div><div><b className="text-[9px] text-ink dark:text-ink-dark">Alcance nutricional</b><p className="mt-0.5 text-[8.5px] text-ink-muted">Duración y energía semanal planificada.</p></div><div><b className="text-[9px] text-ink dark:text-ink-dark">Trazabilidad</b><p className="mt-0.5 text-[8.5px] text-ink-muted">Distingue asistencia experta y elaboración profesional.</p></div></div>}
   {esIncidencias&&<div className="grid gap-2 rounded-xl border border-brand-orange/20 bg-brand-orange/[.025] p-3 md:grid-cols-3"><div><b className="text-[9px] text-ink dark:text-ink-dark">Qué ocurrió</b><p className="mt-0.5 text-[8.5px] text-ink-muted">Total y señal predominante del seguimiento.</p></div><div><b className="text-[9px] text-ink dark:text-ink-dark">A quién priorizar</b><p className="mt-0.5 text-[8.5px] text-ink-muted">Adherencia y estado actual del paciente.</p></div><div><b className="text-[9px] text-ink dark:text-ink-dark">Qué revisar</b><p className="mt-0.5 text-[8.5px] text-ink-muted">Acción concreta sugerida para la consulta.</p></div></div>}
   <div className="grid grid-cols-2 gap-2 lg:grid-cols-4">{reporte.resumen.map(x=><div key={x.etiqueta} className="rounded-xl border border-surface-border bg-black/[0.015] p-3 dark:border-surface-border-dark dark:bg-white/[0.02]"><b className="text-[16px] text-ink dark:text-ink-dark">{x.valor}</b><p className="text-[9px] uppercase tracking-wide text-ink-muted">{x.etiqueta}</p></div>)}</div>
   <div className="overflow-x-auto rounded-xl border border-surface-border dark:border-surface-border-dark"><table className="w-full min-w-[760px] text-left"><thead className="bg-black/[0.025] text-[9px] uppercase tracking-wider text-ink-muted dark:bg-white/[0.03]"><tr>{Object.values(reporte.columnas).map(c=><th key={c} className="px-4 py-3">{c}</th>)}</tr></thead><tbody className="divide-y divide-surface-border dark:divide-surface-border-dark">{reporte.filas.map((fila,i)=><tr key={i} className="text-[10.5px] text-ink dark:text-ink-dark">{Object.keys(reporte.columnas).map(c=><td key={c} className="px-4 py-3 capitalize">{c==='paciente'?<div className="flex min-w-[190px] items-center gap-2.5"><AvatarPaciente nombre={String(fila[c]??'Paciente')} avatarUrl={typeof fila._avatar_url==='string'?fila._avatar_url:null} size="sm"/><span className="font-semibold">{fila[c]??'—'}</span></div>:fila[c]??'—'}</td>)}</tr>)}</tbody></table>{reporte.filas.length===0&&<div className="py-10 text-center text-[11px] text-ink-muted">No existen resultados para este reporte y sus filtros.</div>}</div>
   <Paginacion datos={reporte.paginacion} onCambiar={cambiarPagina}/>
  </section>
 </main></AuthenticatedLayout>}
function CampoBuscar({value,onChange}:{value:string;onChange:(v:string)=>void}){return <label><span className="mb-1 block text-[9.5px] font-semibold text-ink-muted">Buscar paciente o CI</span><div className="relative"><Search size={13} className="absolute left-3 top-2.5 text-ink-muted"/><input value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-lg border border-surface-border bg-transparent py-2 pl-8 pr-3 text-[11px] text-ink dark:border-surface-border-dark dark:text-ink-dark"/></div></label>}
function Selector({label,value,onChange,opciones}:{label:string;value:string;onChange:(v:string)=>void;opciones:Record<string,string>}){return <label><span className="mb-1 block text-[9.5px] font-semibold text-ink-muted">{label}</span><select value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-lg border border-surface-border bg-surface-card px-3 py-2 text-[11px] text-ink dark:border-surface-border-dark dark:bg-surface-card-dark dark:text-ink-dark"><option value="">Todos</option>{Object.entries(opciones).map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label>}
function Fecha({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label><span className="mb-1 block text-[9.5px] font-semibold text-ink-muted">{label}</span><input type="date" value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-lg border border-surface-border bg-surface-card px-3 py-2 text-[11px] text-ink dark:border-surface-border-dark dark:bg-surface-card-dark dark:text-ink-dark"/></label>}
function Paginacion({datos,onCambiar}:{datos:Reporte['paginacion'];onCambiar:(p:number)=>void}){if(datos.ultima_pagina<=1)return null;return <div className="flex flex-col gap-2 border-t border-surface-border pt-3 dark:border-surface-border-dark sm:flex-row sm:items-center sm:justify-between"><p className="text-[9.5px] text-ink-muted">Mostrando <b className="text-ink dark:text-ink-dark">{datos.desde}–{datos.hasta}</b> de <b className="text-ink dark:text-ink-dark">{datos.total}</b> resultados</p><div className="flex items-center gap-1"><button type="button" disabled={datos.pagina_actual===1} onClick={()=>onCambiar(datos.pagina_actual-1)} className="flex h-8 items-center gap-1 rounded-lg border border-surface-border px-2.5 text-[9px] font-bold disabled:opacity-35 dark:border-surface-border-dark"><ChevronLeft size={12}/>Anterior</button><span className="min-w-20 text-center text-[9.5px] font-semibold text-ink dark:text-ink-dark">Página {datos.pagina_actual} de {datos.ultima_pagina}</span><button type="button" disabled={datos.pagina_actual===datos.ultima_pagina} onClick={()=>onCambiar(datos.pagina_actual+1)} className="flex h-8 items-center gap-1 rounded-lg border border-surface-border px-2.5 text-[9px] font-bold disabled:opacity-35 dark:border-surface-border-dark">Siguiente<ChevronRight size={12}/></button></div></div>}
