import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, router } from '@inertiajs/react';
import { ClipboardList, Download, FileBarChart, Salad, Search, ShieldAlert, Users } from 'lucide-react';
import { useState } from 'react';
import clsx from 'clsx';

interface Definicion { titulo:string; descripcion:string }
interface Reporte { tipo:string;titulo:string;descripcion:string;columnas:Record<string,string>;filas:Record<string,string|number>[];resumen:{etiqueta:string;valor:string|number}[] }
interface Props { catalogo:Record<string,Definicion>;reporte:Reporte;filtros:Record<string,string> }
const iconos:Record<string,typeof Users>={pacientes:Users,adherencia:FileBarChart,planes:Salad,incidencias:ShieldAlert,sin_seguimiento:ClipboardList};
const niveles={alta:'Alta (85–100%)',media:'Media (50–84%)',baja:'Baja (1–49%)',cero:'Adherencia 0%',sin_registros:'Sin registros'};
const estados={al_dia:'Al día',en_progreso:'En progreso',requiere_atencion:'Requiere atención',sin_registros:'Sin registros'};
const estadosPlan={sugerido:'Sugerido',en_revision:'En revisión',aprobado:'Aprobado',activo:'Activo',rechazado:'Rechazado',finalizado:'Finalizado'};

export default function Index({catalogo,reporte,filtros}:Props){
 const[buscar,setBuscar]=useState(filtros.buscar??''),[nivel,setNivel]=useState(filtros.nivel??''),[estado,setEstado]=useState(filtros.estado??''),[estadoPlan,setEstadoPlan]=useState(filtros.estado_plan??''),[desde,setDesde]=useState(filtros.desde??''),[hasta,setHasta]=useState(filtros.hasta??'');
 const parametros=(tipo=reporte.tipo)=>Object.fromEntries(Object.entries({tipo,buscar,nivel,estado,estado_plan:estadoPlan,desde,hasta}).filter(([,v])=>v));
 const elegir=(tipo:string)=>router.get(route('nutricionista.reportes.index'),{tipo},{preserveState:false});
 const aplicar=()=>router.get(route('nutricionista.reportes.index'),parametros(),{preserveState:true,preserveScroll:true});
 const esPlanes=reporte.tipo==='planes';
 return <AuthenticatedLayout title="Reportes nutricionales"><Head title="Reportes nutricionales"/><main className="space-y-5">
  <section className="card-elevated border-l-4 border-brand-green px-6 py-5"><p className="text-[10px] font-bold uppercase tracking-wider text-brand-green-dark dark:text-brand-green">Centro de reportes</p><h1 className="mt-1 text-[20px] font-bold text-ink dark:text-ink-dark">Generador de reportes nutricionales</h1><p className="mt-1 text-[11.5px] text-ink-muted">Elige la información, filtra los resultados y genera un documento profesional.</p></section>
  <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{Object.entries(catalogo).map(([tipo,d])=>{const Icon=iconos[tipo]??FileBarChart,activo=tipo===reporte.tipo;return <button key={tipo} type="button" onClick={()=>elegir(tipo)} className={clsx('rounded-2xl border p-4 text-left transition-all',activo?'border-brand-green/40 bg-brand-green/[0.07] ring-1 ring-brand-green/15':'border-surface-border bg-surface-card hover:border-brand-green/25 dark:border-surface-border-dark dark:bg-surface-card-dark')}><Icon size={17} className={activo?'text-brand-green-dark dark:text-brand-green':'text-ink-muted'}/><h2 className="mt-3 text-[12px] font-bold text-ink dark:text-ink-dark">{d.titulo}</h2><p className="mt-1 text-[9.5px] leading-relaxed text-ink-muted">{d.descripcion}</p></button>})}</section>
  <section className="card-elevated space-y-4 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-[16px] font-bold text-ink dark:text-ink-dark">{reporte.titulo}</h2><p className="text-[10.5px] text-ink-muted">{reporte.descripcion}</p></div><a href={route('nutricionista.reportes.adherencia.pdf',parametros())} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-lg bg-brand-green/15 px-4 py-2.5 text-[11px] font-bold text-brand-green-dark hover:bg-brand-green/25 dark:text-brand-green"><Download size={14}/> Generar PDF ({reporte.filas.length})</a></div>
   <div className="grid gap-2 md:grid-cols-2 xl:grid-cols-4"><CampoBuscar value={buscar} onChange={setBuscar}/>{esPlanes?<><Selector label="Estado del plan" value={estadoPlan} onChange={setEstadoPlan} opciones={estadosPlan}/><Fecha label="Desde" value={desde} onChange={setDesde}/><Fecha label="Hasta" value={hasta} onChange={setHasta}/></>:<><Selector label="Nivel de adherencia" value={nivel} onChange={setNivel} opciones={niveles}/><Selector label="Estado de seguimiento" value={estado} onChange={setEstado} opciones={estados}/></>}<div className="flex items-end"><button type="button" onClick={aplicar} className="w-full rounded-lg border border-brand-green/25 bg-brand-green/10 px-4 py-2 text-[11px] font-bold text-brand-green-dark dark:text-brand-green">Aplicar filtros</button></div></div>
   <div className="grid grid-cols-2 gap-2 lg:grid-cols-4">{reporte.resumen.map(x=><div key={x.etiqueta} className="rounded-xl border border-surface-border bg-black/[0.015] p-3 dark:border-surface-border-dark dark:bg-white/[0.02]"><b className="text-[16px] text-ink dark:text-ink-dark">{x.valor}</b><p className="text-[9px] uppercase tracking-wide text-ink-muted">{x.etiqueta}</p></div>)}</div>
   <div className="overflow-x-auto rounded-xl border border-surface-border dark:border-surface-border-dark"><table className="w-full min-w-[760px] text-left"><thead className="bg-black/[0.025] text-[9px] uppercase tracking-wider text-ink-muted dark:bg-white/[0.03]"><tr>{Object.values(reporte.columnas).map(c=><th key={c} className="px-4 py-3">{c}</th>)}</tr></thead><tbody className="divide-y divide-surface-border dark:divide-surface-border-dark">{reporte.filas.map((fila,i)=><tr key={i} className="text-[10.5px] text-ink dark:text-ink-dark">{Object.keys(reporte.columnas).map(c=><td key={c} className="px-4 py-3 capitalize">{fila[c]??'—'}</td>)}</tr>)}</tbody></table>{reporte.filas.length===0&&<div className="py-10 text-center text-[11px] text-ink-muted">No existen resultados para este reporte y sus filtros.</div>}</div>
  </section>
 </main></AuthenticatedLayout>}
function CampoBuscar({value,onChange}:{value:string;onChange:(v:string)=>void}){return <label><span className="mb-1 block text-[9.5px] font-semibold text-ink-muted">Buscar paciente o CI</span><div className="relative"><Search size={13} className="absolute left-3 top-2.5 text-ink-muted"/><input value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-lg border border-surface-border bg-transparent py-2 pl-8 pr-3 text-[11px] text-ink dark:border-surface-border-dark dark:text-ink-dark"/></div></label>}
function Selector({label,value,onChange,opciones}:{label:string;value:string;onChange:(v:string)=>void;opciones:Record<string,string>}){return <label><span className="mb-1 block text-[9.5px] font-semibold text-ink-muted">{label}</span><select value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-lg border border-surface-border bg-surface-card px-3 py-2 text-[11px] text-ink dark:border-surface-border-dark dark:bg-surface-card-dark dark:text-ink-dark"><option value="">Todos</option>{Object.entries(opciones).map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label>}
function Fecha({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label><span className="mb-1 block text-[9.5px] font-semibold text-ink-muted">{label}</span><input type="date" value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-lg border border-surface-border bg-surface-card px-3 py-2 text-[11px] text-ink dark:border-surface-border-dark dark:bg-surface-card-dark dark:text-ink-dark"/></label>}
