<?php
namespace Tests\Feature\Nutricion;
use App\Models\Paciente;use App\Models\PlanAlimentario;use App\Models\RecomendacionNutricionalExperta;use App\Models\Role;use App\Models\User;use App\Models\UserRole;use App\Services\Nutricion\CicloPlanAlimentarioService;use Carbon\Carbon;use DomainException;use Illuminate\Foundation\Testing\RefreshDatabase;use Tests\TestCase;
class CicloPlanAlimentarioServiceTest extends TestCase
{
 use RefreshDatabase;
 public function test_finaliza_aprobado_y_genera_sugerido_con_fecha_indicada():void{[$u,$p,$plan]=$this->escenario('aprobado');$nuevo=app(CicloPlanAlimentarioService::class)->finalizarYGenerarSiguiente($plan,$u,Carbon::parse('2026-09-01'),'Cierre clínico');$this->assertSame('finalizado',$plan->fresh()->estado_plan);$this->assertSame('sugerido',$nuevo->estado_plan);$this->assertSame('2026-09-01',$nuevo->fecha_inicio->toDateString());$this->assertSame('2026-09-07',$nuevo->fecha_fin->toDateString());$this->assertStringContainsString('Cierre clínico',$plan->fresh()->observaciones);$this->assertSame(2,$p->planesAlimentarios()->count());}
 public function test_finaliza_activo_y_usa_dia_siguiente_a_fecha_fin():void{[$u,,$plan]=$this->escenario('activo');$plan->update(['fecha_fin'=>'2026-08-31']);$nuevo=app(CicloPlanAlimentarioService::class)->finalizarYGenerarSiguiente($plan,$u);$this->assertSame('finalizado',$plan->fresh()->estado_plan);$this->assertSame('2026-09-01',$nuevo->fecha_inicio->toDateString());}
 public function test_bloquea_estados_no_finalizables():void{foreach(['sugerido','en_revision','rechazado','finalizado'] as $estado){[$u,$p,$plan]=$this->escenario($estado);try{app(CicloPlanAlimentarioService::class)->finalizarYGenerarSiguiente($plan,$u);$this->fail('Debió bloquear '.$estado);}catch(DomainException){$this->assertSame($estado,$plan->fresh()->estado_plan);$this->assertSame(1,$p->planesAlimentarios()->count());}}}
 public function test_sin_recomendacion_aprobada_no_finaliza_ni_genera():void{[$u,$p,$plan]=$this->escenario('activo',false);$this->expectException(DomainException::class);try{app(CicloPlanAlimentarioService::class)->finalizarYGenerarSiguiente($plan,$u);}finally{$this->assertSame('activo',$plan->fresh()->estado_plan);$this->assertSame(1,$p->planesAlimentarios()->count());}}
 public function test_falla_del_generador_hace_rollback():void{[$u,$p,$plan]=$this->escenario('activo');$generador=\Mockery::mock(\App\Services\Nutricion\GeneradorPlanSemanalService::class);$generador->shouldReceive('generarDesdeRecomendacion')->once()->andThrow(new \RuntimeException('Falla controlada'));$servicio=new CicloPlanAlimentarioService(app(\App\Services\Nutricion\ContextoAjustePlanService::class),$generador);try{$servicio->finalizarYGenerarSiguiente($plan,$u);$this->fail('Debió fallar');}catch(\RuntimeException){$this->assertSame('activo',$plan->fresh()->estado_plan);$this->assertSame(1,$p->planesAlimentarios()->count());}}
 public function test_ruta_protegida_y_ejecuta_flujo():void{[$u,$p,$plan]=$this->escenario('activo');$this->actingAs($u)->post(route('nutricionista.planes.finalizar-y-generar-siguiente',$plan),['fecha_inicio'=>'2026-09-10'])->assertRedirect()->assertSessionHas('success');$this->assertSame('finalizado',$plan->fresh()->estado_plan);$this->assertDatabaseHas('planes_alimentarios',['id_paciente'=>$p->getKey(),'estado_plan'=>'sugerido','fecha_inicio'=>'2026-09-10']);}
 public function test_ruta_bloquea_anonimo_y_otro_rol():void{[,,$plan]=$this->escenario('activo');$url=route('nutricionista.planes.finalizar-y-generar-siguiente',$plan);$this->post($url)->assertRedirect(route('login'));$this->actingAs($this->usuario('endocrinologo'))->post($url)->assertForbidden();}
 private function escenario(string $estado,bool $aprobada=true):array{$u=$this->usuario('nutricionista');$pu=User::factory()->create();$p=Paciente::query()->create(['user_id'=>$pu->getKey(),'nombres'=>'Paciente','apellido_paterno'=>'Ciclo','ci'=>fake()->unique()->numerify('########'),'fecha_nacimiento'=>'1990-01-01','sexo'=>'femenino','estado'=>'activo']);if($aprobada)RecomendacionNutricionalExperta::query()->create(['id_paciente'=>$p->getKey(),'id_nutricionista'=>$u->getKey(),'enfoque_nutricional_experto'=>'alto_fibra','calorias_sugeridas'=>1600,'proteinas_porcentaje'=>30,'carbohidratos_porcentaje'=>40,'grasas_porcentaje'=>30,'fibra_sugerida'=>28,'estado_validacion_experta'=>'aprobado','estado'=>'activo']);$plan=PlanAlimentario::query()->create(['id_paciente'=>$p->getKey(),'id_nutricionista'=>$u->getKey(),'nombre'=>'Plan actual','estado_plan'=>$estado,'fecha_inicio'=>'2026-08-25','fecha_fin'=>'2026-08-31','observaciones'=>'Observación previa.','estado'=>'activo']);return[$u,$p,$plan];}
 private function usuario(string $rol):User{$r=Role::query()->firstOrCreate(['nombre'=>$rol],['descripcion'=>$rol,'estado'=>'activo']);$u=User::factory()->create(['estado'=>'activo']);UserRole::query()->create(['user_id'=>$u->getKey(),'id_rol'=>$r->getKey(),'estado'=>'activo']);return$u;}
}
