<?php
namespace Tests\Feature\Nutricion;

use App\Models\ComidaPlanAlimentario;use App\Models\ComponenteComidaPlan;use App\Models\DiaPlanAlimentario;use App\Models\Paciente;use App\Models\PlanAlimentario;use App\Models\Receta;use App\Models\SeguimientoComida;use App\Models\User;
use App\Services\Nutricion\HistorialPlanesAlimentariosService;use App\Services\Nutricion\PerfilNutricionalService;use App\Services\Paciente\PortalPacienteService;use Illuminate\Foundation\Testing\RefreshDatabase;use Tests\TestCase;

class HistorialPlanesAlimentariosServiceTest extends TestCase
{
 use RefreshDatabase;
 public function test_nutricionista_ve_todos_los_estados_y_totales():void{$p=$this->paciente();foreach(['sugerido','en_revision','aprobado','activo','rechazado','finalizado'] as $e)$this->plan($p,$e);$h=$this->service()->obtenerParaNutricionista($p);$this->assertCount(6,$h['planes']);$this->assertEqualsCanonicalizing(['sugerido','en_revision','aprobado','activo','rechazado','finalizado'],collect($h['planes'])->pluck('estado_plan')->all());$x=$h['planes'][0];$this->assertSame(1,$x['total_dias']);$this->assertSame(1,$x['total_comidas']);$this->assertSame(2,$x['total_componentes']);$this->assertSame(1,$x['total_componentes_receta']);$this->assertSame(1,$x['total_componentes_manual']);}
 public function test_paciente_solo_ve_estados_publicables_y_no_datos_internos():void{$p=$this->paciente();foreach(['sugerido','en_revision','rechazado','aprobado','activo','finalizado'] as $e)$this->plan($p,$e);$planes=$this->service()->obtenerParaPaciente($p)['planes'];$this->assertEqualsCanonicalizing(['aprobado','activo','finalizado'],collect($planes)->pluck('estado_plan')->all());$this->assertSame('activo',$planes[0]['estado_plan']);$this->assertArrayNotHasKey('observaciones',$planes[0]);$this->assertArrayNotHasKey('recomendacion_origen',$planes[0]);}
 public function test_calcula_adherencia_y_compara_plan_actual_con_anterior():void{$p=$this->paciente();$a=$this->plan($p,'finalizado',1200);$b=$this->plan($p,'activo',1500);$comida=$b->dias->first()->comidas->first();SeguimientoComida::query()->create(['id_paciente'=>$p->getKey(),'id_plan_alimentario'=>$b->getKey(),'id_dia_plan_alimentario'=>$comida->id_dia_plan_alimentario,'id_comida_plan_alimentario'=>$comida->getKey(),'fecha_seguimiento'=>today(),'estado_cumplimiento'=>'completada','porcentaje_consumido'=>100]);$h=$this->service()->obtenerParaPaciente($p);$this->assertSame(100.0,$h['planes'][0]['porcentaje_adherencia']);$this->assertTrue($h['comparacion']['tiene_plan_anterior']);$this->assertSame(300.0,$h['comparacion']['cambios']['calorias']);$this->assertNotEmpty($h['comparacion']['mensaje']);}
 public function test_integraciones_exponen_historial_y_no_mezclan_pacientes():void{$p=$this->paciente();$otro=$this->paciente();$this->plan($p,'activo');$this->plan($otro,'activo');$this->assertCount(1,app(PerfilNutricionalService::class)->historialPlanes($p)['planes']);$dashboard=app(PortalPacienteService::class)->obtenerDashboard($p->user);$this->assertCount(1,$dashboard['historialPlanes']['planes']);$this->assertSame($p->planesAlimentarios()->first()->getKey(),$dashboard['historialPlanes']['planes'][0]['id_plan_alimentario']);}
 public function test_no_falla_sin_planes():void{$h=$this->service()->obtenerParaPaciente($this->paciente());$this->assertSame([],$h['planes']);$this->assertFalse($h['comparacion']['tiene_plan_anterior']);}
 private function service(){return app(HistorialPlanesAlimentariosService::class);}
 private function paciente():Paciente{$u=User::factory()->create();return Paciente::query()->create(['user_id'=>$u->getKey(),'nombres'=>'Paciente','apellido_paterno'=>'Historial','ci'=>fake()->unique()->numerify('########'),'fecha_nacimiento'=>'1994-01-01','sexo'=>'femenino','estado'=>'activo']);}
 private function plan(Paciente $p,string $estado,float $calorias=1400):PlanAlimentario{$plan=PlanAlimentario::query()->create(['id_paciente'=>$p->getKey(),'nombre'=>'Plan '.$estado,'fecha_inicio'=>today(),'estado_plan'=>$estado,'calorias_objetivo'=>$calorias,'calorias_totales'=>$calorias,'proteinas_totales'=>100,'carbohidratos_totales'=>150,'grasas_totales'=>50,'fibra_total'=>25,'estado'=>'activo']);$d=DiaPlanAlimentario::query()->create(['id_plan_alimentario'=>$plan->getKey(),'numero_dia'=>1,'nombre_dia'=>'Día 1','estado'=>'activo']);$c=ComidaPlanAlimentario::query()->create(['id_dia_plan_alimentario'=>$d->getKey(),'tipo_comida'=>'desayuno','nombre_comida'=>'Desayuno','orden'=>1,'calorias_totales'=>300,'estado'=>'activo']);$r=Receta::query()->create(['nombre'=>'Receta '.$plan->getKey(),'tipo_comida'=>'desayuno','porciones'=>1,'estado'=>'activo']);ComponenteComidaPlan::query()->create(['id_comida_plan_alimentario'=>$c->getKey(),'tipo_componente'=>'receta','id_receta'=>$r->getKey(),'cantidad'=>1,'unidad'=>'porción','orden'=>1,'estado'=>'activo']);ComponenteComidaPlan::query()->create(['id_comida_plan_alimentario'=>$c->getKey(),'tipo_componente'=>'manual','nombre_manual'=>'Alternativa','cantidad'=>1,'unidad'=>'porción','orden'=>2,'estado'=>'activo']);return $plan->fresh()->load('dias.comidas.componentes');}
}
