import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, Link } from '@inertiajs/react';
import { ArrowLeft, Activity, CalendarDays, Download, Info, Ruler, Scale, TrendingDown, TrendingUp } from 'lucide-react';
import clsx from 'clsx';
import type { AnaliticaEvolucion } from '@/Components/nutricionista/analitica/AnaliticaEvolucionPanel';

type Paciente = { id_paciente:number; nombres:string; apellido_paterno?:string|null; apellido_materno?:string|null };
const num=(v:number|null|undefined,s='')=>v===null||v===undefined?'—':`${Number(v).toLocaleString('es-BO',{maximumFractionDigits:2})}${s}`;
const fecha=(v:string|null)=>v?new Intl.DateTimeFormat('es-BO',{day:'2-digit',month:'short',year:'numeric',timeZone:'America/La_Paz'}).format(new Date(`${v}T12:00:00-04:00`)):'Sin fecha';

export default function Index({paciente,analitica}:{paciente:Paciente;analitica:AnaliticaEvolucion}){
 const r=analitica.evolucion_antropometrica.resumen; const registros=analitica.evolucion_antropometrica.registros;
 const nombre=[paciente.nombres,paciente.apellido_paterno,paciente.apellido_materno].filter(Boolean).join(' ');
 const inicial=registros[0]; const actual=registros[registros.length-1];
 return <AuthenticatedLayout title="Evolución antropométrica"><Head title={`Evolución - ${nombre}`}/><main className="space-y-4">
  <section className="card-elevated overflow-hidden"><div className="border-b border-surface-border/60 bg-gradient-to-r from-brand-green/[.06] to-transparent p-5 dark:border-surface-border-dark/60"><div className="flex flex-wrap items-center justify-between gap-4"><div><div className="mb-2 flex items-center gap-2 text-[9px] font-bold uppercase tracking-wider text-brand-green-dark dark:text-brand-green"><Activity size={13}/> Seguimiento corporal</div><h1 className="text-[18px] font-bold text-ink dark:text-ink-dark">Evolución antropométrica</h1><p className="mt-1 text-[11px] text-ink-muted dark:text-ink-muted-dark">{nombre} · {r.total_evaluaciones} controles entre {fecha(inicial?.fecha??null)} y {fecha(actual?.fecha??null)}</p></div><div className="flex flex-wrap gap-2"><a href={`/nutricionista/pacientes/${paciente.id_paciente}/perfil-nutricional/historial/evaluaciones/reporte-pdf`} target="_blank" className="inline-flex items-center gap-2 rounded-xl bg-brand-green px-3.5 py-2.5 text-[11px] font-bold text-white"><Download size={13}/> Reporte de cambios PDF</a><Link href={`/nutricionista/pacientes/${paciente.id_paciente}/perfil-nutricional?step=adherencia`} className="inline-flex items-center gap-2 rounded-xl border border-surface-border bg-surface-card px-3.5 py-2.5 text-[11px] font-bold text-ink dark:border-surface-border-dark dark:bg-surface-card-dark dark:text-ink-dark"><ArrowLeft size={13}/> Volver</Link></div></div></div><div className="flex gap-2 px-5 py-3 text-[10px] text-ink-muted dark:text-ink-muted-dark"><Info size={13} className="mt-0.5 shrink-0 text-info"/><p>Los cambios muestran la diferencia entre el primer y el último control. Una disminución no siempre es positiva por sí sola: debe compararse con el objetivo nutricional, la composición corporal y el criterio profesional.</p></div></section>
  <section className="grid gap-3 md:grid-cols-3"><Metrica icon={Scale} titulo="Peso" inicial={inicial?.peso} actual={r.peso_actual} unidad=" kg" cambio={r.cambio_peso}/><Metrica icon={Activity} titulo="IMC" inicial={inicial?.imc} actual={r.imc_actual} unidad="" cambio={r.cambio_imc}/><Metrica icon={Ruler} titulo="Cintura" inicial={inicial?.cintura} actual={r.cintura_actual} unidad=" cm" cambio={r.cambio_cintura}/></section>
  <section className="card-elevated p-5"><div className="flex flex-wrap items-center justify-between gap-2"><div><h2 className="text-[13px] font-bold text-ink dark:text-ink-dark">Cambios entre controles</h2><p className="mt-1 text-[10.5px] text-ink-muted dark:text-ink-muted-dark">La línea permite reconocer la dirección y estabilidad de cada indicador.</p></div><span className="inline-flex items-center gap-1.5 rounded-lg bg-info/10 px-2.5 py-1 text-[9px] font-bold text-info"><CalendarDays size={11}/>{registros.length} mediciones</span></div><div className="mt-4 grid gap-3 lg:grid-cols-3"><Grafico titulo="Peso" unidad="kg" valores={registros.map(x=>({fecha:x.fecha,valor:x.peso}))}/><Grafico titulo="IMC" unidad="kg/m²" valores={registros.map(x=>({fecha:x.fecha,valor:x.imc}))}/><Grafico titulo="Cintura" unidad="cm" valores={registros.map(x=>({fecha:x.fecha,valor:x.cintura}))}/></div></section>
  <section className="card-elevated p-5"><h2 className="text-[13px] font-bold text-ink dark:text-ink-dark">Historial de controles</h2><p className="mt-1 text-[10.5px] text-ink-muted dark:text-ink-muted-dark">Los cambios deben interpretarse junto con el objetivo nutricional y el criterio profesional.</p><div className="mt-4 overflow-x-auto rounded-xl border border-surface-border dark:border-surface-border-dark"><table className="w-full min-w-[760px] text-[11px]"><thead className="bg-black/[.025] dark:bg-white/[.03]"><tr>{['Fecha','Peso (kg)','IMC','Cintura (cm)','Cadera (cm)','ICC','Grasa (%)','Músculo (kg)'].map(x=><th key={x} className="px-3 py-3 text-left text-[9px] font-bold uppercase tracking-wide text-ink-muted dark:text-ink-muted-dark">{x}</th>)}</tr></thead><tbody>{registros.map((x,i)=><tr key={`${x.fecha}-${i}`} className="border-t border-surface-border/50 dark:border-surface-border-dark/50"><td className="px-3 py-3 font-semibold text-ink dark:text-ink-dark">{fecha(x.fecha)}</td><td className="px-3 py-3">{num(x.peso)}</td><td className="px-3 py-3">{num(x.imc)}</td><td className="px-3 py-3">{num(x.cintura)}</td><td className="px-3 py-3">{num(x.cadera)}</td><td className="px-3 py-3">{num(x.icc)}</td><td className="px-3 py-3">{num(x.grasa_corporal)}</td><td className="px-3 py-3">{num(x.masa_muscular)}</td></tr>)}</tbody></table>{registros.length===0&&<p className="p-8 text-center text-[11px] text-ink-muted">Sin evaluaciones registradas.</p>}</div></section>
 </main></AuthenticatedLayout>
}
function Metrica({icon:Icon,titulo,inicial,actual,unidad,cambio}:{icon:typeof Scale;titulo:string;inicial:number|null|undefined;actual:number|null;unidad:string;cambio:number|null}){const baja=(cambio??0)<0;return <article className="card-elevated p-4"><div className="flex items-center justify-between"><div className="flex items-center gap-2 text-brand-green-dark dark:text-brand-green"><Icon size={16}/><p className="text-[10px] font-bold uppercase tracking-wide">{titulo}</p></div><div className={clsx('inline-flex items-center gap-1 rounded-lg px-2 py-1 text-[9.5px] font-bold',cambio===null?'bg-black/[.04] text-ink-muted':baja?'bg-brand-green/10 text-brand-green-dark':'bg-brand-orange/10 text-brand-orange')}>{cambio===null?'Sin cambio':<>{baja?<TrendingDown size={12}/>:<TrendingUp size={12}/>} {cambio>0?'+':''}{num(cambio,unidad)}</>}</div></div><div className="mt-4 grid grid-cols-[1fr_auto_1fr] items-end gap-3"><div><p className="text-[8.5px] font-bold uppercase text-ink-muted">Inicial</p><p className="mt-1 text-[14px] font-semibold text-ink-muted dark:text-ink-muted-dark">{num(inicial,unidad)}</p></div><span className="pb-1 text-ink-muted/40">→</span><div className="text-right"><p className="text-[8.5px] font-bold uppercase text-brand-green-dark dark:text-brand-green">Actual</p><p className="mt-1 text-[22px] font-bold text-ink dark:text-ink-dark">{num(actual,unidad)}</p></div></div></article>}

function Grafico({titulo,unidad,valores}:{titulo:string;unidad:string;valores:Array<{fecha:string|null;valor:number|null}>}) {
 const validos=valores.filter((x):x is {fecha:string|null;valor:number}=>x.valor!==null);
 if(!validos.length)return <div className="rounded-xl border border-dashed border-surface-border p-5 text-center text-[10px] text-ink-muted dark:border-surface-border-dark">Sin datos de {titulo.toLowerCase()}.</div>;
 const min=Math.min(...validos.map(x=>x.valor)),max=Math.max(...validos.map(x=>x.valor)),rango=max-min||1;
 const posiciones=validos.map((x,i)=>({ ...x, cx:validos.length===1?50:(i/(validos.length-1))*100, cy:76-((x.valor-min)/rango)*48 }));
 const puntos=posiciones.map(x=>`${x.cx},${x.cy}`).join(' ');
 const cambio=validos.at(-1)!.valor-validos[0].valor;
 const direccion=cambio>0?'aumentó':cambio<0?'disminuyó':'se mantuvo estable';
 return <article className="rounded-xl border border-surface-border p-4 dark:border-surface-border-dark">
  <div className="flex items-start justify-between gap-3"><div><p className="text-[11px] font-bold text-ink dark:text-ink-dark">{titulo}</p><p className="mt-0.5 text-[9px] text-ink-muted">{validos.length} medición(es) representadas</p></div><span className="rounded-lg bg-brand-green/10 px-2 py-1 text-[10px] font-bold text-brand-green-dark dark:text-brand-green">{cambio>0?'+':''}{num(cambio,` ${unidad}`)}</span></div>
  <div className="relative mt-5 h-28 px-3">
   <svg className="absolute inset-0 h-full w-full overflow-visible" viewBox="0 0 100 92" preserveAspectRatio="none"><line x1="0" y1="76" x2="100" y2="76" className="stroke-black/10 dark:stroke-white/10" strokeWidth="1"/><polyline points={puntos} fill="none" className="stroke-brand-green" strokeWidth="2" vectorEffect="non-scaling-stroke"/>{posiciones.map((x,i)=><circle key={`${x.fecha}-${i}`} cx={x.cx} cy={x.cy} r="2.3" className="fill-brand-green"/>)}</svg>
   {posiciones.map((x,i)=><div key={`label-${x.fecha}-${i}`} className="absolute -translate-x-1/2 text-center" style={{left:`${Math.max(8,Math.min(92,x.cx))}%`,top:`${Math.max(0,(x.cy/92)*100-15)}%`}}><span className="inline-flex whitespace-nowrap rounded-md border border-brand-green/20 bg-surface-card px-1.5 py-0.5 text-[8.5px] font-bold text-brand-green-dark shadow-sm dark:bg-surface-card-dark dark:text-brand-green">{num(x.valor,` ${unidad}`)}</span></div>)}
  </div>
  <div className="flex justify-between text-[8px] text-ink-muted"><span>{fecha(validos[0].fecha)}</span><span>{fecha(validos.at(-1)!.fecha)}</span></div>
  <div className="mt-3 rounded-lg bg-black/[.025] px-3 py-2 dark:bg-white/[.03]"><p className="text-[9.5px] leading-relaxed text-ink-muted dark:text-ink-muted-dark"><b className="text-ink dark:text-ink-dark">Lectura:</b> {titulo} {direccion}{cambio===0?'':` ${num(Math.abs(cambio),` ${unidad}`)}`} entre el primer y el último control. Este cambio requiere interpretación profesional.</p></div>
 </article>
}
