import { Activity, AlertTriangle, ChartNoAxesCombined, Ruler, Scale, Utensils } from 'lucide-react';

interface ResumenAntropometrico {peso_actual:number|null;cambio_peso:number|null;imc_actual:number|null;cambio_imc:number|null;cintura_actual:number|null;cambio_cintura:number|null;total_evaluaciones:number}
interface Registro {fecha:string|null;peso:number|null;imc:number|null;cintura:number|null;cadera:number|null;icc:number|null;grasa_corporal:number|null;masa_muscular:number|null}
interface Tipo {tipo_comida:string;total:number;registradas:number;porcentaje_adherencia:number;principal_problema:string}
interface Receta {id_receta:number;nombre:string;tipo_comida:string;puntaje_aceptacion:number;motivos?:string[];frecuencia?:number}
export interface AnaliticaEvolucion {evolucion_antropometrica:{registros:Registro[];resumen:ResumenAntropometrico};evolucion_adherencia:{por_plan:Array<{id_plan_alimentario:number;nombre_plan:string;estado_plan:string;porcentaje_adherencia:number;registradas:number;comidas_totales:number}>;resumen:{promedio_adherencia:number;mejor_plan:{nombre_plan:string;porcentaje_adherencia:number}|null;peor_plan:{nombre_plan:string;porcentaje_adherencia:number}|null;tendencia_adherencia:string}};cumplimiento_por_tipo_comida:Tipo[];analitica_sintomas:Record<string,unknown>;recetas_aceptadas:Receta[];recetas_problematicas:Receta[];problemas_practicos:{ingredientes_no_conseguidos:Array<{nombre:string}>;recetas_dificiles:Array<{nombre:string}>;comidas_reemplazadas:number;motivos_no_cumplimiento_frecuentes:Record<string,number>;horarios_problematicos:Record<string,number>};alertas:Array<{tipo:string;severidad:string;mensaje:string;recomendacion:string}>;recomendaciones_siguiente_plan:Array<{texto:string;origen:string}>}
const n=(v:number|null|undefined)=>v===null||v===undefined?'—':Number(v).toLocaleString('es-BO',{maximumFractionDigits:2});
const etiqueta=(v:string)=>v.replaceAll('_',' ');

export default function AnaliticaEvolucionPanel({analitica}:{analitica:AnaliticaEvolucion}){
 const a=analitica.evolucion_antropometrica,res=a.resumen,adh=analitica.evolucion_adherencia;
 const sintomas=Object.entries(analitica.analitica_sintomas).filter(([k,v])=>k.endsWith('_frecuente')&&v===true).map(([k])=>etiqueta(k));
 return <div className="space-y-4">
  <div className="flex items-center gap-2"><ChartNoAxesCombined className="text-primary"/><div><h2 className="text-xl font-bold">Analítica de evolución</h2><p className="text-sm text-base-content/60">Resumen histórico para apoyar decisiones del siguiente plan.</p></div></div>
  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metrica icon={<Scale size={17}/>} titulo="Peso actual" valor={`${n(res.peso_actual)} kg`} cambio={res.cambio_peso}/><Metrica icon={<Activity size={17}/>} titulo="IMC actual" valor={n(res.imc_actual)} cambio={res.cambio_imc}/><Metrica icon={<Ruler size={17}/>} titulo="Cintura actual" valor={`${n(res.cintura_actual)} cm`} cambio={res.cambio_cintura}/><Metrica icon={<ChartNoAxesCombined size={17}/>} titulo="Adherencia promedio" valor={`${n(adh.resumen.promedio_adherencia)}%`} detalle={`Tendencia: ${etiqueta(adh.resumen.tendencia_adherencia)}`}/><Metrica icon={<Activity size={17}/>} titulo="Síntomas frecuentes" valor={String(sintomas.length)} detalle={sintomas[0]??'Sin alertas frecuentes'}/></div>
  {analitica.alertas.length>0&&<div className="space-y-2">{analitica.alertas.map((x,i)=><div className={`alert items-start ${x.severidad==='alta'?'alert-error':x.severidad==='media'?'alert-warning':'alert-info'}`} key={`${x.tipo}-${i}`}><AlertTriangle size={18}/><div><b>{x.mensaje}</b><p className="text-sm">{x.recomendacion}</p></div></div>)}</div>}
  <div className="grid gap-4 xl:grid-cols-2"><section className="card-elevated p-5"><h3 className="font-bold">Evolución antropométrica</h3>{a.registros.length===0?<Vacio/>:<div className="mt-3 overflow-x-auto"><table className="table table-sm"><thead><tr><th>Fecha</th><th>Peso</th><th>IMC</th><th>Cintura</th><th>Grasa</th><th>Músculo</th></tr></thead><tbody>{a.registros.map((x,i)=><tr key={`${x.fecha}-${i}`}><td>{x.fecha}</td><td>{n(x.peso)}</td><td>{n(x.imc)}</td><td>{n(x.cintura)}</td><td>{n(x.grasa_corporal)}</td><td>{n(x.masa_muscular)}</td></tr>)}</tbody></table></div>}</section><section className="card-elevated p-5"><h3 className="font-bold">Adherencia por plan</h3>{adh.por_plan.length===0?<Vacio/>:<div className="mt-3 space-y-3">{adh.por_plan.map(x=><div key={x.id_plan_alimentario}><div className="flex justify-between text-sm"><span>{x.nombre_plan}</span><b>{n(x.porcentaje_adherencia)}%</b></div><progress className="progress progress-primary w-full" value={x.porcentaje_adherencia} max="100"/><p className="text-xs text-base-content/45">{x.registradas}/{x.comidas_totales} registradas · {etiqueta(x.estado_plan)}</p></div>)}</div>}<div className="mt-4 grid grid-cols-2 gap-2 text-xs"><p><b>Mejor:</b> {adh.resumen.mejor_plan?.nombre_plan??'—'}</p><p><b>A revisar:</b> {adh.resumen.peor_plan?.nombre_plan??'—'}</p></div></section></div>
  <section className="card-elevated p-5"><h3 className="font-bold">Cumplimiento por tipo de comida</h3><div className="mt-3 grid gap-3 md:grid-cols-4">{analitica.cumplimiento_por_tipo_comida.map(x=><div className="rounded-xl bg-base-200 p-4" key={x.tipo_comida}><div className="flex items-center gap-2"><Utensils size={15}/><b className="capitalize">{etiqueta(x.tipo_comida)}</b></div><p className="mt-2 text-2xl font-black">{n(x.porcentaje_adherencia)}%</p><progress className="progress progress-primary w-full" value={x.porcentaje_adherencia} max="100"/><p className="mt-2 text-xs">{x.principal_problema}</p></div>)}</div></section>
  <div className="grid gap-4 lg:grid-cols-2"><Recetas titulo="Mejor aceptadas" recetas={analitica.recetas_aceptadas}/><Recetas titulo="A revisar o evitar temporalmente" recetas={analitica.recetas_problematicas} problemas/></div>
  <div className="grid gap-4 lg:grid-cols-2"><section className="card-elevated p-5"><h3 className="font-bold">Problemas prácticos</h3><Lista titulo="Ingredientes no conseguidos" items={analitica.problemas_practicos.ingredientes_no_conseguidos.map(x=>x.nombre)}/><Lista titulo="Recetas difíciles" items={analitica.problemas_practicos.recetas_dificiles.map(x=>x.nombre)}/><Lista titulo="Motivos frecuentes" items={Object.entries(analitica.problemas_practicos.motivos_no_cumplimiento_frecuentes).map(([k,v])=>`${etiqueta(k)} (${v})`)}/></section><section className="card-elevated p-5"><h3 className="font-bold">Recomendaciones para el siguiente plan</h3>{analitica.recomendaciones_siguiente_plan.length===0?<Vacio/>:<ul className="mt-3 space-y-2">{analitica.recomendaciones_siguiente_plan.map((x,i)=><li className="rounded-xl bg-primary/5 p-3 text-sm" key={`${x.texto}-${i}`}><p>{x.texto}</p><span className="mt-1 badge badge-ghost badge-sm">{x.origen}</span></li>)}</ul>}</section></div>
 </div>
}
function Metrica({icon,titulo,valor,cambio,detalle}:{icon:React.ReactNode;titulo:string;valor:string;cambio?:number|null;detalle?:string}){return <div className="card-elevated p-4"><div className="flex items-center gap-2 text-base-content/55">{icon}<span className="text-xs font-bold uppercase">{titulo}</span></div><p className="mt-2 text-2xl font-black">{valor}</p>{cambio!==undefined&&cambio!==null?<p className={`text-xs ${cambio<=0?'text-success':'text-warning'}`}>{cambio>0?'+':''}{n(cambio)} desde el inicio</p>:detalle&&<p className="text-xs capitalize text-base-content/50">{detalle}</p>}</div>}
function Recetas({titulo,recetas,problemas=false}:{titulo:string;recetas:Receta[];problemas?:boolean}){return <section className="card-elevated p-5"><h3 className="font-bold">{titulo}</h3>{recetas.length===0?<Vacio/>:<div className="mt-3 space-y-2">{recetas.slice(0,8).map(x=><div className="rounded-xl border border-base-300 p-3" key={x.id_receta}><div className="flex justify-between"><b>{x.nombre}</b><span className={`badge ${problemas?'badge-warning':'badge-success'}`}>{problemas?`${x.frecuencia??0} motivo(s)`:x.puntaje_aceptacion}</span></div><p className="text-xs capitalize text-base-content/50">{etiqueta(x.tipo_comida)}</p>{problemas&&<p className="mt-1 text-xs">{x.motivos?.map(etiqueta).join(', ')}</p>}</div>)}</div>}</section>}
function Lista({titulo,items}:{titulo:string;items:string[]}){return <div className="mt-4"><p className="text-xs font-bold uppercase text-base-content/50">{titulo}</p><div className="mt-2 flex flex-wrap gap-2">{items.length?items.map(x=><span className="badge badge-outline h-auto py-2" key={x}>{x}</span>):<span className="text-sm text-base-content/45">Sin registros.</span>}</div></div>}
function Vacio(){return <p className="mt-3 text-sm text-base-content/45">Sin datos suficientes.</p>}
