<!doctype html><html lang="es"><head><meta charset="utf-8"><title>Mi plan alimentario semanal</title><style>
@page{margin:28px 30px 44px}*{box-sizing:border-box}body{font-family:DejaVu Sans,sans-serif;color:#263238;font-size:9px;line-height:1.4}h1{font-size:21px;color:#174d3b;margin:3px 0}h2{font-size:12px;color:#174d3b;border-bottom:1px solid #a9c7bc;padding-bottom:4px;margin:17px 0 7px}h3{font-size:11px;color:#174d3b;margin:9px 0 4px}.head{border-bottom:3px solid #2f8066;padding-bottom:11px}.brand{font-size:9px;font-weight:bold;color:#2f8066;margin-bottom:5px;text-transform:uppercase;letter-spacing:1.2px}.brand-mark{display:inline-block;color:#2f8066;margin-right:4px}.eyebrow{color:#607d75;font-size:8px;letter-spacing:.6px;text-transform:uppercase}.right{float:right;text-align:right}.clear{clear:both}.box{background:#f2f7f5;border:1px solid #d7e5df;padding:9px;margin:7px 0}.notice{background:#fff4dc;border-left:3px solid #d99b21;padding:8px}.grid{width:100%;border-collapse:collapse}.grid th,.grid td{border:1px solid #d9e1de;padding:5px;vertical-align:top}.grid th{background:#e8f1ed;color:#174d3b;text-align:left}.day{page-break-inside:avoid;margin-bottom:14px}.meal{margin:5px 0;padding:7px;border:1px solid #d9e1de;border-left:3px solid #2f8066}.tag{display:inline-block;background:#e8f1ed;color:#174d3b;border-radius:8px;padding:2px 6px;margin:1px}.muted{color:#78908a}.page{page-break-before:always}ul{margin:4px 0;padding-left:16px}.footer{position:fixed;left:0;right:0;bottom:-30px;border-top:1px solid #aaa;padding-top:7px;color:#78908a;font-size:7px}.footer b{color:#2f8066}
</style></head><body>
@php
$rec=$plan->recomendacionNutricionalExperta;$nombre=trim(implode(' ',array_filter([$paciente->nombres,$paciente->apellido_paterno,$paciente->apellido_materno])));$fmt=fn($v,$u='')=>$v===null?'Sin registro':number_format((float)$v,1,',','.').$u;$lista=fn($v)=>is_array($v)?array_values(array_filter($v)):[];
@endphp
<div class="head"><div class="right"><span class="eyebrow">Documento personal</span><br><b>{{ $fechaDescarga->format('d/m/Y') }}</b><br><span class="muted">Validado por nutrición</span></div><div class="brand"><span class="brand-mark">●</span>Nutrigo · Salud integral</div><div class="eyebrow">TU PLAN, TUS HÁBITOS, TU PROGRESO</div><h1>Mi plan alimentario semanal</h1><span class="muted">Una guía práctica preparada especialmente para ti</span><div class="clear"></div></div>
<h2>Información de tu plan</h2><table class="grid"><tr><th>Paciente</th><th>Periodo</th><th>Estado</th><th>Nutricionista</th></tr><tr><td>{{ $nombre }}</td><td>{{ $plan->fecha_inicio?->format('d/m/Y') ?? 'Por definir' }} al {{ $plan->fecha_fin?->format('d/m/Y') ?? 'Por definir' }}</td><td>{{ ucfirst($plan->estado_plan) }}</td><td>{{ $plan->nutricionista?->name ?? 'Equipo de nutrición' }}</td></tr></table>
<div class="box">Este plan fue elaborado y validado por el equipo de nutrición. Sigue las indicaciones según tus horarios y registra tu seguimiento en el sistema para que tu nutricionista pueda ajustar futuros planes.</div>
<h2>Restricciones consideradas</h2>@forelse($lista($rec?->restricciones) as $x)<span class="tag">{{ $x }}</span>@empty<p>Sin restricciones registradas.</p>@endforelse
<h2>Recomendaciones simples</h2><ul>@forelse($lista($rec?->recomendaciones) as $x)<li>{{ $x }}</li>@empty<li>Mantén horarios regulares y sigue las cantidades indicadas.</li>@endforelse</ul>@foreach($lista($rec?->alertas) as $x)<div class="notice">{{ $x }}</div>@endforeach @if($rec?->conclusion)<p>{{ $rec->conclusion }}</p>@endif
<h2>Resumen nutricional semanal</h2><table class="grid"><tr><th>Nutriente</th><th>Objetivo diario</th><th>Total planificado</th></tr>@foreach(['calorias'=>'Calorías','proteinas'=>'Proteínas','carbohidratos'=>'Carbohidratos','grasas'=>'Grasas','fibra'=>'Fibra'] as $campo=>$etiqueta)@php $objetivo=$campo==='fibra'?$plan->fibra_objetivo:$plan->{$campo.'_objetivo'};$total=$campo==='fibra'?$plan->fibra_total:$plan->{$campo.'_totales'}; @endphp<tr><td>{{ $etiqueta }}</td><td>{{ $fmt($objetivo,$campo==='calorias'?' kcal':' g') }}</td><td>{{ $fmt($total,$campo==='calorias'?' kcal':' g') }}</td></tr>@endforeach</table>
<div class="page"></div><h2>Tu planificación semanal</h2>
@foreach($plan->dias as $dia)<div class="day"><h3>Día {{ $dia->numero_dia }} · {{ ucfirst($dia->nombre_dia) }} @if($dia->fecha) — {{ $dia->fecha->format('d/m/Y') }} @endif</h3><table class="grid"><tr><th>Calorías</th><th>Proteínas</th><th>Carbohidratos</th><th>Grasas</th><th>Fibra</th></tr><tr><td>{{ $fmt($dia->calorias_totales,' kcal') }}</td><td>{{ $fmt($dia->proteinas_totales,' g') }}</td><td>{{ $fmt($dia->carbohidratos_totales,' g') }}</td><td>{{ $fmt($dia->grasas_totales,' g') }}</td><td>{{ $fmt($dia->fibra_total,' g') }}</td></tr></table>
@foreach($dia->comidas as $comida)<div class="meal"><b>{{ ucfirst(str_replace('_',' ',$comida->tipo_comida)) }} · {{ $comida->nombre_comida }}</b><span class="right">{{ substr((string)$comida->hora_sugerida,0,5) ?: 'Sin hora' }} · {{ $fmt($comida->calorias_totales,' kcal') }}</span><div class="clear"></div>
@foreach($comida->componentes as $c)<p><b>{{ $c->receta?->nombre ?? $c->alimento?->nombre ?? $c->nombre_manual ?? 'Componente' }}</b> — {{ $fmt($c->cantidad) }} {{ $c->unidad ?: '' }}</p>
@if($c->receta)<p class="muted">{{ $c->receta->descripcion ?: 'Receta indicada por nutrición.' }}</p><b>Ingredientes:</b><ul>@forelse($c->receta->recetaAlimentos as $i)<li>{{ $i->alimento?->nombre ?? 'Ingrediente' }}: {{ $fmt($i->cantidad) }} {{ $i->unidad }}</li>@empty<li>Consultar ingredientes con nutrición.</li>@endforelse</ul><b>Preparación:</b><p>{{ $c->receta->preparacion ?: 'Sigue las indicaciones entregadas por nutrición.' }}</p>
@elseif($c->tipo_componente==='manual')<p>Indicaciones definidas por nutrición.@if($c->observaciones) {{ $c->observaciones }}@endif</p>@endif @endforeach</div>@endforeach</div>@endforeach
<div class="page"></div><h2>Lista de compras semanal</h2>@forelse($listaCompras['categorias'] as $categoria)<h3>{{ ucfirst($categoria['nombre']) }}</h3><table class="grid"><tr><th>Alimento</th><th>Cantidad</th><th>Unidad</th></tr>@foreach($categoria['items'] as $item)<tr><td>{{ $item['nombre'] }}</td><td>{{ $fmt($item['cantidad']) }}</td><td>{{ $item['unidad'] }}</td></tr>@endforeach</table>@empty<p>Sin alimentos registrados en la lista de compras.</p>@endforelse
@if(!empty($listaCompras['indicaciones_manuales']))<h3>Indicaciones manuales</h3><ul>@foreach($listaCompras['indicaciones_manuales'] as $m)<li>{{ $m['nombre'] }} — {{ $fmt($m['cantidad']) }} {{ $m['unidad'] }}</li>@endforeach</ul>@endif
<h2>Recuerda</h2><ul><li>Mantén horarios regulares.</li><li>Toma agua durante el día.</li><li>Registra tu seguimiento.</li><li>Si una comida te causa molestias, anótalo en el sistema.</li><li>Consulta con tu nutricionista antes de hacer cambios importantes.</li></ul>
<div class="footer"><b>Nutrigo</b> · Esta guía práctica no reemplaza la evaluación ni las indicaciones personalizadas de tu nutricionista.</div>
</body></html>
