<!doctype html>
<html lang="es"><head><meta charset="utf-8"><style>
@page { margin: 28px 30px; } body{font-family:DejaVu Sans,sans-serif;color:#16322a;font-size:10px}.head{border-bottom:3px solid #25964e;padding-bottom:12px}.brand{color:#25964e;font-weight:bold;font-size:10px;letter-spacing:1px}.title{font-size:22px;font-weight:bold;margin:5px 0}.muted{color:#648078}.right{float:right;text-align:right;font-size:8px}.section{margin-top:18px}.section h2{font-size:13px;margin:0 0 8px;color:#174d35}.grid{width:100%;border-collapse:separate;border-spacing:7px 0}.metric{background:#f2f8f4;border:1px solid #d6e9dc;border-radius:7px;padding:10px}.metric .label{font-size:8px;color:#648078;text-transform:uppercase}.metric .value{font-size:16px;font-weight:bold;color:#174d35;margin-top:3px}.metric .small{font-size:8px;color:#648078;margin-top:3px}.positive{color:#208544}.warning{color:#c8780b}.table{width:100%;border-collapse:collapse;margin-top:6px}.table th{background:#e9f4ec;color:#28523f;font-size:8px;text-transform:uppercase;text-align:left;padding:8px}.table td{border-bottom:1px solid #dbe9df;padding:8px}.bar-bg{height:9px;background:#e4eee7;border-radius:8px;width:100%}.bar{height:9px;background:#2eae58;border-radius:8px}.note{background:#f6faf7;border-left:3px solid #2eae58;padding:10px;line-height:1.55}.footer{position:fixed;bottom:0;color:#7b9189;font-size:8px;width:100%;text-align:center}
</style></head><body>
<div class="head"><div class="right">Generado el {{ $fechaGeneracion->format('d/m/Y H:i') }}<br>Hora de Bolivia</div><div class="brand">Almendra Nutrición · PORTAL DEL PACIENTE</div><div class="title">Mi evolución nutricional</div><div class="muted">Resumen personal de medidas, constancia y objetivo nutricional.</div></div>
<div class="section"><h2>{{ trim($paciente->nombres.' '.$paciente->apellido_paterno.' '.$paciente->apellido_materno) }}</h2><div class="muted">CI: {{ $paciente->ci ?? '—' }} · {{ count($historial) }} medición(es) registrada(s)</div></div>
@php($e = $resumen['evaluacion']) @php($a = $resumen['adherencia']) @php($o = $resumen['objetivo'])
<div class="section"><h2>Resumen de cambio</h2><table class="grid"><tr>
<td class="metric"><div class="label">Peso actual</div><div class="value">{{ $e['peso_actual'] !== null ? number_format($e['peso_actual'],1,',','.') . ' kg' : '—' }}</div><div class="small">Cambio: <span class="{{ ($e['cambio_peso'] ?? 0) <= 0 ? 'positive' : 'warning' }}">{{ $e['cambio_peso'] !== null ? (($e['cambio_peso'] > 0 ? '+' : '') . number_format($e['cambio_peso'],1,',','.') . ' kg') : 'Sin comparación' }}</span></div></td>
<td class="metric"><div class="label">Cintura actual</div><div class="value">{{ $e['cintura_actual'] !== null ? number_format($e['cintura_actual'],1,',','.') . ' cm' : '—' }}</div><div class="small">Cambio: <span class="{{ ($e['cambio_cintura'] ?? 0) <= 0 ? 'positive' : 'warning' }}">{{ $e['cambio_cintura'] !== null ? (($e['cambio_cintura'] > 0 ? '+' : '') . number_format($e['cambio_cintura'],1,',','.') . ' cm') : 'Sin comparación' }}</span></div></td>
<td class="metric"><div class="label">IMC actual</div><div class="value">{{ $e['imc_actual'] !== null ? number_format($e['imc_actual'],2,',','.') : '—' }}</div><div class="small">{{ $e['clasificacion_imc'] ?? 'Sin clasificación' }}</div></td>
<td class="metric"><div class="label">Adherencia actual</div><div class="value">{{ number_format($a['porcentaje_adherencia'] ?? 0,1,',','.') }}%</div><div class="small">{{ $a['registradas'] ?? 0 }} comidas registradas</div></td>
</tr></table></div>
<div class="section"><h2>Constancia del plan vigente</h2><div class="bar-bg"><div class="bar" style="width: {{ min(100,max(0,$a['porcentaje_adherencia'] ?? 0)) }}%"></div></div><div class="muted" style="margin-top:5px">Completadas: {{ $a['completadas'] ?? 0 }} · Parciales: {{ $a['parciales'] ?? 0 }} · Reemplazadas: {{ $a['reemplazadas'] ?? 0 }} · Pendientes: {{ $a['pendientes'] ?? 0 }}</div></div>
<div class="section"><h2>Historial de mediciones</h2><table class="table"><thead><tr><th>Fecha</th><th>Peso</th><th>IMC</th><th>Cintura</th><th>Cadera</th><th>% grasa</th><th>Masa muscular</th></tr></thead><tbody>@foreach($historial as $registro)<tr><td>{{ !empty($registro['fecha']) ? \Carbon\Carbon::parse($registro['fecha'])->format('d/m/Y') : '—' }}</td><td>{{ $registro['peso'] !== null ? number_format($registro['peso'],1,',','.') . ' kg' : '—' }}</td><td>{{ $registro['imc'] !== null ? number_format($registro['imc'],2,',','.') : '—' }}</td><td>{{ $registro['cintura'] !== null ? number_format($registro['cintura'],1,',','.') . ' cm' : '—' }}</td><td>{{ $registro['cadera'] !== null ? number_format($registro['cadera'],1,',','.') . ' cm' : '—' }}</td><td>{{ $registro['porcentaje_grasa'] !== null ? number_format($registro['porcentaje_grasa'],1,',','.') . '%' : '—' }}</td><td>{{ $registro['masa_muscular'] !== null ? number_format($registro['masa_muscular'],1,',','.') . ' kg' : '—' }}</td></tr>@endforeach</tbody></table></div>
<div class="section note"><b>Tu objetivo actual:</b> {{ $o['objetivo_principal'] ? ucfirst(str_replace('_',' ',$o['objetivo_principal'])) : 'Por definir con nutrición' }}. Este reporte muestra cambios registrados y acompaña la conversación con tu nutricionista; no reemplaza su valoración profesional.</div>
<div class="footer">Reporte personal confidencial · Almendra Nutrición</div></body></html>
