import { Link, router, usePage } from '@inertiajs/react';
import { Bell, Menu, Search } from 'lucide-react';
import { useState } from 'react';
import ThemeToggle from './theme-toggle';
import type { PageProps } from '@/types';
interface TopbarProps { title: string; onMenuClick?: () => void }
export default function Topbar({ title, onMenuClick }: TopbarProps) {
 const {auth,notificaciones}=usePage<PageProps>().props; const [open,setOpen]=useState(false); const name=auth?.user?.name?.trim()||'Usuario'; const avatar=auth?.user?.avatar; const roles=auth?.user?.roles?.map(r=>r.nombre)??[]; const path=typeof window!=='undefined'?location.pathname:'';
 const rol=path.startsWith('/admin')||roles.includes('administrador')?'Administrador':path.startsWith('/nutricionista')||roles.includes('nutricionista')?'Nutricionista':path.startsWith('/paciente')||roles.includes('paciente')?'Paciente':'Endocrinólogo'; const initials=name.replace(/^(lic\.?|dra?\.?|nut\.?)\s+/i,'').split(/\s+/).slice(0,2).map(p=>p[0]).join('').toUpperCase();
 return <div className="mb-5 flex items-center justify-between rounded-card border border-brand-green/10 bg-brand-green-soft/[0.18] px-4 py-3.5 shadow-card dark:border-surface-border-dark dark:bg-surface-card-dark md:px-5"><div className="flex items-center gap-3"><button className="flex h-9 w-9 items-center justify-center rounded-full border lg:hidden" onClick={onMenuClick}><Menu size={16}/></button><h1 className="truncate text-xl font-bold">{title}</h1></div><div className="flex items-center gap-3"><ThemeToggle/><button className="hidden h-9 w-9 items-center justify-center rounded-full border sm:flex"><Search size={16}/></button><div className="relative"><button onClick={()=>setOpen(v=>!v)} className="relative flex h-9 w-9 items-center justify-center rounded-full border bg-white dark:bg-surface-card-dark"><Bell size={16}/>{!!notificaciones?.total_no_leidas&&<span className="absolute -right-1 -top-1 min-w-4 rounded-full bg-red-500 px-1 text-[9px] font-bold text-white">{notificaciones.total_no_leidas}</span>}</button>{open&&<div className="absolute right-0 top-11 z-50 w-80 overflow-hidden rounded-2xl border bg-surface-card shadow-xl dark:border-surface-border-dark dark:bg-surface-card-dark"><div className="flex justify-between border-b p-3 dark:border-surface-border-dark"><b className="text-xs">Notificaciones</b>{!!notificaciones?.total_no_leidas&&<button className="text-[10px] text-brand-green" onClick={()=>router.post('/notificaciones/leer-todas')}>Marcar todas</button>}</div><div className="max-h-80 overflow-y-auto">{notificaciones?.ultimas?.length?notificaciones.ultimas.map(n=><button key={n.id_notificacion_interna} onClick={()=>router.post(`/notificaciones/${n.id_notificacion_interna}/leer`)} className="block w-full border-b p-3 text-left hover:bg-brand-green/5 dark:border-surface-border-dark"><p className="text-[11px] font-bold">{n.titulo}</p><p className="mt-1 text-[10px] text-ink-muted">{n.mensaje}</p></button>):<p className="p-5 text-center text-[11px] text-ink-muted">Sin notificaciones</p>}</div><Link href="/notificaciones" className="block p-3 text-center text-[10px] font-bold text-brand-green">Ver todas</Link></div>}</div><div className="flex items-center gap-2">{avatar?<img src={avatar} alt="" className="h-8 w-8 rounded-full object-cover"/>:<div className="flex h-8 w-8 items-center justify-center rounded-full bg-[#E7E4DC] text-[11px] font-bold">{initials}</div>}<div className="hidden sm:block"><div className="text-[12px] font-semibold">{name}</div><div className="text-[10px] text-ink-muted">{rol}</div></div></div></div></div>;
}
