declare const route: any;
import { Link } from '@inertiajs/react';
import { Eye, FileSearch } from 'lucide-react';
import AvatarIniciales from '@/Components/ui/avatar-iniciales';
import AuditoriaPill from './AuditoriaPill';
import type { EstadoFlujoPaciente, PacienteAuditoria } from './types';
const tonoFlujo=(f?:EstadoFlujoPaciente|null):'verde'|'naranja'|'azul'|'neutro'=>f==='completo'?'verde':f==='en_seguimiento'?'azul':f?.startsWith('pendiente')?'naranja':'neutro';
export default function AuditoriaTabla({pacientes}:{pacientes:PacienteAuditoria[]}) {
 if(!pacientes.length)return <div className="flex flex-col items-center gap-2 px-5 py-16 text-center"><FileSearch size={29} strokeWidth={1.2} className="text-ink-muted/40 dark:text-ink-muted-dark/40"/><p className="text-[13px] text-ink-muted dark:text-ink-muted-dark">No se encontraron pacientes</p><p className="text-[11px] text-ink-muted/60 dark:text-ink-muted-dark/60">Prueba con otros criterios de auditoría</p></div>;
 return <div className="overflow-x-auto"><table className="w-full min-w-[1120px] border-collapse"><thead><tr className="border-b border-surface-border text-left text-[10.5px] font-semibold text-ink-muted dark:border-surface-border-dark dark:text-ink-muted-dark"><th className="px-5 py-2.5">Paciente</th><th className="px-3">Estado</th><th className="px-3">Flujo clínico</th><th className="px-3">Origen</th><th className="px-3">Creado por</th><th className="px-3">Actualizado por</th><th className="px-3">Último cambio</th><th className="px-5 text-right">Actividad</th></tr></thead>
 <tbody>{pacientes.map((p,i)=><tr key={p.id_paciente} className={`${i%2?'bg-[#FDFCFA] dark:bg-[#1A1D24]':''} border-b border-[#F5F2EB] transition-colors hover:bg-[#FAFAF8] dark:border-[#262A32] dark:hover:bg-white/[0.02]`}><td className="px-5 py-3"><div className="flex items-center gap-2.5"><AvatarIniciales nombre={p.nombre_completo||p.user?.name||'P'} size={32}/><div><p className="text-[12.5px] font-semibold text-ink dark:text-ink-dark">{p.nombre_completo||p.user?.name||'Sin nombre'}</p><p className="text-[10.5px] text-ink-muted dark:text-ink-muted-dark">CI {p.ci} · {p.user?.email||'Sin correo'}</p></div></div></td><td className="px-3"><AuditoriaPill texto={p.estado} tono={p.estado==='activo'?'verde':'naranja'}/></td><td className="px-3"><AuditoriaPill texto={p.estado_flujo} tono={tonoFlujo(p.estado_flujo)}/></td><td className="px-3"><AuditoriaPill texto={p.origen_registro}/></td><td className="px-3 text-[11.5px] text-ink dark:text-ink-dark">{p.creado_por_user?.name||'—'}</td><td className="px-3 text-[11.5px] text-ink dark:text-ink-dark">{p.actualizado_por_user?.name||'—'}</td><td className="px-3 text-[11px] text-ink-muted dark:text-ink-muted-dark">{p.updated_at||p.created_at||'—'}</td><td className="px-5"><div className="flex justify-end"><Link href={route('admin.auditoria.actividad',{paciente:p.id_paciente})} title="Ver actividad" className="flex h-7 w-7 items-center justify-center rounded-lg text-ink-muted hover:bg-category-others/10 hover:text-category-others dark:text-ink-muted-dark"><Eye size={13}/></Link></div></td></tr>)}</tbody></table></div>;
}
