declare const route: any;
import { Link } from '@inertiajs/react';
import { Eye, FileSearch } from 'lucide-react';
import AvatarIniciales from '@/Components/ui/avatar-iniciales';
import AuditoriaPill from './AuditoriaPill';
import type { PacienteAuditoria, UsuarioAuditoria } from './types';

function Responsable({usuario,fecha,vacio}:{usuario?:UsuarioAuditoria|null;fecha?:string|null;vacio:string}) {
 if(!usuario)return <div><p className="text-[11px] font-semibold text-ink-muted">{vacio}</p><p className="text-[9px] text-ink-muted/70">Sin actor registrado</p></div>;
 return <div className="min-w-[150px]"><p className="text-[11.5px] font-semibold text-ink dark:text-ink-dark">{usuario.name}</p><p className="text-[9.5px] text-ink-muted dark:text-ink-muted-dark">{usuario.email||'Sin correo'}</p><div className="mt-1 flex flex-wrap gap-1">{usuario.roles?.map(r=><span key={r} className="rounded bg-brand-green/10 px-1.5 py-0.5 text-[8px] font-bold capitalize text-brand-green-dark dark:text-brand-green">{r}</span>)}</div>{fecha&&<p className="mt-1 text-[9px] text-ink-muted/70">{fecha}</p>}</div>;
}

export default function AuditoriaTabla({pacientes}:{pacientes:PacienteAuditoria[]}) {
 if(!pacientes.length)return <div className="flex flex-col items-center gap-2 px-5 py-16 text-center"><FileSearch size={29} className="text-ink-muted/40"/><p className="text-[13px] text-ink-muted">No se encontraron pacientes</p><p className="text-[11px] text-ink-muted/60">Prueba con otros criterios de auditoría</p></div>;
 return <div className="overflow-x-auto"><table className="w-full min-w-[1280px] border-collapse"><thead><tr className="border-b border-surface-border text-left text-[10px] font-semibold uppercase tracking-wider text-ink-muted dark:border-surface-border-dark"><th className="px-5 py-3">Paciente</th><th className="px-3">Estado</th><th className="px-3">Origen</th><th className="px-3">Creado por</th><th className="px-3">Última modificación por</th><th className="px-3">Registro</th><th className="px-5 text-right">Detalle</th></tr></thead><tbody>{pacientes.map((p,i)=><tr key={p.id_paciente} className={`${i%2?'bg-[#FDFCFA] dark:bg-[#1A1D24]':''} border-b border-[#F5F2EB] align-top hover:bg-[#FAFAF8] dark:border-[#262A32] dark:hover:bg-white/[0.02]`}><td className="px-5 py-4"><div className="flex items-center gap-2.5"><AvatarIniciales nombre={p.nombre_completo||p.user?.name||'P'} size={34}/><div><p className="text-[12.5px] font-semibold">{p.nombre_completo||p.user?.name||'Sin nombre'}</p><p className="text-[10px] text-ink-muted">CI {p.ci} · {p.user?.email||'Sin correo'}</p><p className="mt-1 text-[9px] text-ink-muted/70">Expediente #{p.id_paciente}</p></div></div></td><td className="px-3 py-4"><AuditoriaPill texto={p.estado} tono={p.estado==='activo'?'verde':'naranja'}/></td><td className="px-3 py-4"><AuditoriaPill texto={p.origen_registro||'histórico'}/></td><td className="px-3 py-4"><Responsable usuario={p.creado_por_user} fecha={p.auditoria_creacion?.fecha} vacio="Registro histórico"/></td><td className="px-3 py-4"><Responsable usuario={p.actualizado_por_user} fecha={p.auditoria_actualizacion?.fecha} vacio="Sin modificaciones auditadas"/></td><td className="px-3 py-4 text-[10px] text-ink-muted"><p>Creado: {p.created_at||'—'}</p><p className="mt-1">Actualizado: {p.updated_at||'—'}</p><p className="mt-2 max-w-[180px] text-[9px]">{p.auditoria_actualizacion?.descripcion||'Sin evento detallado'}</p></td><td className="px-5 py-4"><div className="flex justify-end"><Link href={route('admin.auditoria.actividad',{paciente:p.id_paciente})} title="Ver historial completo" className="flex items-center gap-1.5 rounded-lg border px-2.5 py-1.5 text-[10px] font-semibold text-category-others hover:bg-category-others/10"><Eye size={13}/> Historial</Link></div></td></tr>)}</tbody></table></div>;
}
