import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import AvatarPaciente from '@/Components/ui/avatar-paciente';
import { Head, Link, router } from '@inertiajs/react';
import { AlertTriangle, ArrowUpRight, CalendarClock, ChevronLeft, ChevronRight, Clock3 } from 'lucide-react';
import clsx from 'clsx';

type Evento = { id_plan_alimentario:number; nombre_plan:string; fecha_inicio:string|null; fecha_fin:string; dias_restantes:number; estado_vigencia:string; paciente:{ id_paciente:number; nombre:string; ci:string|null; avatar_url:string|null } };
type Props = { mes:string; fecha_actual_bolivia:string; resumen:{vencidos:number;vencen_hoy:number;proximos_2_dias:number;proximos_7_dias:number}; eventos_mes:Evento[]; requieren_atencion:Evento[] };
const dias = ['Lun','Mar','Mié','Jue','Vie','Sáb','Dom'];
const fechaUtc=(v:string)=>new Date(`${v}T12:00:00Z`);
const etiqueta=(e:Evento)=>e.estado_vigencia==='vencido'?`Venció hace ${Math.abs(e.dias_restantes)} día(s)`:e.estado_vigencia==='vence_hoy'?'Vence hoy':`Vence en ${e.dias_restantes} día(s)`;

export default function Index({mes,fecha_actual_bolivia,resumen,eventos_mes,requieren_atencion}:Props){
 const [anio,numeroMes]=mes.split('-').map(Number), inicio=new Date(Date.UTC(anio,numeroMes-1,1)), total=new Date(Date.UTC(anio,numeroMes,0)).getUTCDate();
 const vacios=(inicio.getUTCDay()+6)%7, celdas=Array.from({length:Math.ceil((vacios+total)/7)*7},(_,i)=>{const d=i-vacios+1;return d>=1&&d<=total?d:null});
 const mover=(delta:number)=>{const d=new Date(Date.UTC(anio,numeroMes-1+delta,1));router.get(route('nutricionista.vigencia-planes'),{mes:`${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,'0')}`},{preserveState:false});};
 const nombreMes=new Intl.DateTimeFormat('es-BO',{month:'long',year:'numeric',timeZone:'UTC'}).format(inicio);
 const porDia=(dia:number)=>eventos_mes.filter(e=>fechaUtc(e.fecha_fin).getUTCDate()===dia);
 return <AuthenticatedLayout title="Vigencia de planes"><Head title="Vigencia de planes"/><main className="space-y-5">
  <section className="card-elevated overflow-hidden"><div className="h-1.5 bg-gradient-to-r from-brand-orange via-brand-orange/50 to-transparent"/><div className="flex flex-wrap items-center justify-between gap-4 p-5"><div><p className="text-[9px] font-bold uppercase tracking-[.16em] text-brand-orange">Continuidad nutricional</p><h1 className="mt-1 text-[19px] font-bold text-ink dark:text-ink-dark">Calendario de vencimiento de planes</h1><p className="mt-1 text-[10.5px] text-ink-muted">Consulta cuándo termina cada planificación y anticipa la siguiente sin dejar periodos descubiertos.</p></div><span className="rounded-xl bg-brand-orange/10 px-3 py-2 text-[9.5px] font-bold text-brand-orange">Hora y fecha de Bolivia · {fecha_actual_bolivia}</span></div></section>
  <section className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Metrica label="Planes vencidos" valor={resumen.vencidos}/><Metrica label="Vencen hoy" valor={resumen.vencen_hoy}/><Metrica label="Próximos 2 días" valor={resumen.proximos_2_dias}/><Metrica label="Próximos 7 días" valor={resumen.proximos_7_dias}/></section>
  <section className="grid gap-4 xl:grid-cols-[minmax(0,1.55fr)_minmax(340px,.75fr)]">
   <div className="card-elevated overflow-hidden"><div className="flex items-center justify-between border-b border-surface-border p-4 dark:border-surface-border-dark"><button onClick={()=>mover(-1)} className="rounded-lg border border-surface-border p-2 dark:border-surface-border-dark"><ChevronLeft size={14}/></button><h2 className="capitalize text-[14px] font-bold text-ink dark:text-ink-dark">{nombreMes}</h2><button onClick={()=>mover(1)} className="rounded-lg border border-surface-border p-2 dark:border-surface-border-dark"><ChevronRight size={14}/></button></div><div className="grid grid-cols-7 border-b border-surface-border bg-black/[.02] dark:border-surface-border-dark dark:bg-white/[.02]">{dias.map(d=><div key={d} className="p-2 text-center text-[8.5px] font-bold uppercase text-ink-muted">{d}</div>)}</div><div className="grid grid-cols-7">{celdas.map((d,i)=><div key={i} className={clsx('min-h-24 border-b border-r border-surface-border p-2 dark:border-surface-border-dark',!d&&'bg-black/[.012] dark:bg-white/[.01]')}><span className={clsx('inline-flex h-6 w-6 items-center justify-center rounded-full text-[9px] font-bold',d&&`${anio}-${String(numeroMes).padStart(2,'0')}-${String(d).padStart(2,'0')}`===fecha_actual_bolivia?'bg-brand-green text-white':'text-ink dark:text-ink-dark')}>{d}</span>{d&&porDia(d).slice(0,3).map(e=><Link key={e.id_plan_alimentario} href={`/nutricionista/pacientes/${e.paciente.id_paciente}/perfil-nutricional?step=planificacion`} className="mt-1 block truncate rounded-md bg-brand-orange/10 px-1.5 py-1 text-[8px] font-semibold text-brand-orange" title={`${e.paciente.nombre} · ${e.nombre_plan}`}>{e.paciente.nombre}</Link>)}{d&&porDia(d).length>3&&<p className="mt-1 text-[8px] text-ink-muted">+{porDia(d).length-3} más</p>}</div>)}</div></div>
   <aside className="card-elevated overflow-hidden"><div className="border-b border-surface-border p-4 dark:border-surface-border-dark"><h2 className="flex items-center gap-2 text-[13px] font-bold text-ink dark:text-ink-dark"><AlertTriangle size={15} className="text-brand-orange"/> Requieren atención</h2><p className="mt-1 text-[9.5px] text-ink-muted">Planes vencidos o que finalizan durante los próximos siete días.</p></div><div className="max-h-[590px] space-y-2 overflow-y-auto p-3">{requieren_atencion.length?requieren_atencion.map(e=><article key={e.id_plan_alimentario} className="rounded-xl border border-surface-border p-3 dark:border-surface-border-dark"><div className="flex items-center gap-2.5"><AvatarPaciente nombre={e.paciente.nombre} avatarUrl={e.paciente.avatar_url} size="sm"/><div className="min-w-0 flex-1"><p className="truncate text-[10.5px] font-bold text-ink dark:text-ink-dark">{e.paciente.nombre}</p><p className="truncate text-[8.5px] text-ink-muted">{e.nombre_plan}</p></div></div><div className="mt-2 flex items-center justify-between gap-2"><span className="inline-flex items-center gap-1 text-[8.5px] font-bold text-brand-orange"><Clock3 size={9}/>{etiqueta(e)}</span><Link href={`/nutricionista/pacientes/${e.paciente.id_paciente}/perfil-nutricional?step=planificacion`} className="inline-flex items-center gap-1 text-[8.5px] font-bold text-brand-green-dark dark:text-brand-green">Ver plan <ArrowUpRight size={9}/></Link></div></article>):<div className="py-12 text-center"><CalendarClock className="mx-auto text-brand-green"/><p className="mt-2 text-[10px] text-ink-muted">No hay vencimientos próximos.</p></div>}</div></aside>
  </section>
 </main></AuthenticatedLayout>;
}
function Metrica({label,valor}:{label:string;valor:number}){return <div className="card-elevated p-4"><p className="text-[21px] font-black text-ink dark:text-ink-dark">{valor}</p><p className="mt-1 text-[9px] font-semibold uppercase tracking-wide text-ink-muted">{label}</p></div>}
