import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, Link, usePage } from '@inertiajs/react';
import { ArrowLeft, CheckCircle2, DatabaseBackup, Download, Info, ShieldCheck } from 'lucide-react';

export default function Index({ motor, baseDatos }: { motor: string; baseDatos: string }) {
    const error = (usePage().props as { flash?: { error?: string | null } }).flash?.error;
    return <AuthenticatedLayout header={<h2>Base de datos</h2>}><Head title="Respaldo de base de datos"/><main className="mx-auto max-w-4xl space-y-5">
        <header className="relative overflow-hidden rounded-2xl border border-surface-border bg-white p-6 dark:border-surface-border-dark dark:bg-[#1c2027]"><div className="absolute inset-y-0 left-0 w-1 bg-category-dairy"/><div className="flex items-center gap-4"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-category-dairy/10 text-category-dairy"><DatabaseBackup size={23}/></div><div><p className="text-[9.5px] font-bold uppercase tracking-[.18em] text-category-dairy">Seguridad de la información</p><h1 className="mt-1 text-xl font-bold">Respaldo de base de datos</h1><p className="mt-1 text-[11px] text-ink-muted">Genera y descarga una copia completa para recuperación administrativa.</p></div></div></header>
        {error && <div className="rounded-xl border border-category-fruits/20 bg-category-fruits/5 px-4 py-3 text-[11.5px] font-semibold text-category-fruits">{error}</div>}
        <section className="grid gap-4 md:grid-cols-[1.2fr_.8fr]">
            <article className="rounded-2xl border border-surface-border p-6 dark:border-surface-border-dark"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-brand-green/10 text-brand-green"><Download size={19}/></div><div><h2 className="text-[14px] font-bold">Crear respaldo ahora</h2><p className="text-[10.5px] text-ink-muted">El archivo se genera en formato PostgreSQL personalizado.</p></div></div><div className="mt-5 rounded-xl bg-black/[.025] p-4 dark:bg-white/[.035]"><Fila label="Motor" valor={motor.toUpperCase()}/><Fila label="Base de datos" valor={baseDatos}/><Fila label="Formato" valor=".backup"/></div><a href={route('admin.base-datos.respaldo')} className="mt-5 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-category-dairy px-4 py-3 text-[11.5px] font-bold text-white transition hover:brightness-95"><Download size={16}/> Generar y descargar respaldo</a><p className="mt-3 text-center text-[9.5px] text-ink-muted">La descarga puede tardar según el tamaño de la base de datos.</p></article>
            <aside className="space-y-3"><div className="rounded-2xl border border-brand-green/15 bg-brand-green/[.035] p-5"><div className="flex items-center gap-2 text-brand-green-dark dark:text-brand-green"><ShieldCheck size={17}/><h2 className="text-[12px] font-bold">Proceso seguro</h2></div><ul className="mt-3 space-y-2 text-[10.5px] text-ink-muted"><li className="flex gap-2"><CheckCircle2 size={13} className="shrink-0 text-brand-green"/>La contraseña no aparece en el comando.</li><li className="flex gap-2"><CheckCircle2 size={13} className="shrink-0 text-brand-green"/>El archivo temporal se elimina al descargar.</li><li className="flex gap-2"><CheckCircle2 size={13} className="shrink-0 text-brand-green"/>La operación queda registrada.</li></ul></div><div className="rounded-2xl border border-info/15 bg-info/[.035] p-5"><div className="flex items-center gap-2 text-info"><Info size={16}/><h2 className="text-[12px] font-bold">Recomendación</h2></div><p className="mt-2 text-[10.5px] leading-relaxed text-ink-muted">Guarda el archivo en una ubicación segura. Para restaurarlo se utiliza <b>pg_restore</b>.</p></div></aside>
        </section>
        <Link href={route('admin.dashboard')} className="inline-flex items-center gap-2 text-[11px] font-bold text-ink-muted hover:text-category-dairy"><ArrowLeft size={14}/> Volver al dashboard</Link>
    </main></AuthenticatedLayout>;
}
function Fila({ label, valor }: { label: string; valor: string }) { return <div className="flex justify-between border-b border-surface-border/50 py-2 text-[11px] last:border-0 dark:border-surface-border-dark"><span className="text-ink-muted">{label}</span><b>{valor}</b></div>; }
