<!doctype html><html lang="es"><head><meta charset="utf-8"><title>{{ $reporte['titulo'] }}</title><style>
@page{margin:28px 32px 42px}body{font-family:DejaVu Sans,sans-serif;color:#263238;font-size:9px;line-height:1.4}h1{font-size:21px;color:#174d3b;margin:4px 0}h2{font-size:12px;color:#174d3b;border-bottom:1px solid #a9c7bc;padding-bottom:4px;margin:16px 0 7px}.head{border-bottom:3px solid #2f8066;padding-bottom:11px}.brand{color:#2f8066;font-size:9px;font-weight:bold;letter-spacing:1.2px;text-transform:uppercase}.right{float:right;text-align:right}.clear{clear:both}.muted{color:#607d75}.grid{width:100%;border-collapse:collapse;margin:7px 0}.grid th,.grid td{border:1px solid #d9e1de;padding:5px;vertical-align:top}.grid th{background:#e8f1ed;color:#174d3b;text-align:left}.summary td{text-align:center}.summary b{display:block;font-size:14px;color:#174d3b}.badge{display:inline-block;background:#e8f1ed;color:#174d3b;border-radius:8px;padding:2px 6px;margin:1px}.empty{padding:22px;text-align:center;border:1px dashed #a9c7bc;color:#607d75}.box{border:1px solid #c9ddd6;background:#f5f9f7;padding:8px;margin:6px 0}.charts{width:100%;border-collapse:collapse}.charts>tbody>tr>td{width:50%;vertical-align:top;padding:0 5px}.chart{border:1px solid #d9e1de;padding:8px}.chart-title{font-weight:bold;color:#174d3b;margin-bottom:7px}.bar-row{margin:5px 0}.bar-label{display:inline-block;width:105px;color:#455e56}.track{display:inline-block;width:180px;height:7px;background:#e8edeb;vertical-align:middle}.fill{display:block;height:7px;background:#2f8066}.bar-value{display:inline-block;width:48px;text-align:right;font-weight:bold;color:#174d3b}.criteria{font-size:8px;color:#607d75}.footer{position:fixed;bottom:-28px;left:0;right:0;border-top:1px solid #aaa;padding-top:6px;color:#78908a;font-size:7px}.footer b{color:#2f8066}
</style></head><body><header class="head"><div class="right"><b>{{ $fechaGeneracion->format('d/m/Y H:i') }}</b><br><span class="muted">Generado por {{ $nutricionista->name }}</span></div><div class="brand">● Almendra Nutrición</div><h1>{{ $reporte['titulo'] }}</h1><div class="muted">{{ $reporte['descripcion'] }}</div><div class="clear"></div></header>
<h2>Resumen</h2><table class="grid summary"><tr>@foreach($reporte['resumen'] as $item)<td><b>{{ $item['valor'] }}</b>{{ $item['etiqueta'] }}</td>@endforeach</tr></table>
@if(($reporte['tipo'] ?? null)==='pacientes')
<h2>Lectura ejecutiva de la cartera</h2>
<div class="box"><b>Interpretación:</b> {{ $reporte['interpretacion'] ?? 'La información resume el estado actual de los pacientes incluidos.' }}</div>
<table class="charts"><tr>
<td><div class="chart"><div class="chart-title">Estado del seguimiento</div>@foreach(data_get($reporte,'graficos.seguimiento',[]) as $dato)<div class="bar-row"><span class="bar-label">{{ $dato['etiqueta'] }}</span><span class="track"><span class="fill" style="width:{{ min(100,$dato['porcentaje']) }}%"></span></span><span class="bar-value">{{ $dato['cantidad'] }} ({{ $dato['porcentaje'] }}%)</span></div>@endforeach</div></td>
<td><div class="chart"><div class="chart-title">Nivel de adherencia</div>@foreach(data_get($reporte,'graficos.adherencia',[]) as $dato)<div class="bar-row"><span class="bar-label">{{ $dato['etiqueta'] }}</span><span class="track"><span class="fill" style="width:{{ min(100,$dato['porcentaje']) }}%"></span></span><span class="bar-value">{{ $dato['cantidad'] }} ({{ $dato['porcentaje'] }}%)</span></div>@endforeach</div></td>
</tr></table>
<p class="criteria"><b>Criterios de lectura:</b> adherencia alta 85–100%; media 50–84%; baja menor a 50%. “Sin registros” indica ausencia de respuestas evaluables y no confirma por sí sola un incumplimiento.</p>
@endif
@if(($reporte['tipo'] ?? null)==='adherencia')
<h2>Lectura ejecutiva del cumplimiento semanal</h2>
<div class="box"><b>Interpretación:</b> {{ $reporte['interpretacion'] ?? 'La información resume el cumplimiento registrado durante el periodo de cada plan.' }}</div>
<table class="charts"><tr>
<td><div class="chart"><div class="chart-title">Pacientes por nivel de adherencia</div>@foreach(data_get($reporte,'graficos.niveles',[]) as $dato)<div class="bar-row"><span class="bar-label">{{ $dato['etiqueta'] }}</span><span class="track"><span class="fill" style="width:{{ min(100,$dato['porcentaje']) }}%"></span></span><span class="bar-value">{{ $dato['cantidad'] }} ({{ $dato['porcentaje'] }}%)</span></div>@endforeach</div></td>
<td><div class="chart"><div class="chart-title">Composición de las comidas planificadas</div>@foreach(data_get($reporte,'graficos.cumplimiento',[]) as $dato)<div class="bar-row"><span class="bar-label">{{ $dato['etiqueta'] }}</span><span class="track"><span class="fill" style="width:{{ min(100,$dato['porcentaje']) }}%"></span></span><span class="bar-value">{{ $dato['cantidad'] }} ({{ $dato['porcentaje'] }}%)</span></div>@endforeach</div></td>
</tr></table>
<p class="criteria"><b>Cómo se interpreta:</b> una comida completada aporta el total; una parcial aporta el porcentaje consumido; una reemplazada aporta parcialmente y una no realizada no aporta. Las comidas futuras pendientes no deben interpretarse como incumplimiento.</p>
@endif
@if(($reporte['tipo'] ?? null)==='planes')
<h2>Lectura ejecutiva de las planificaciones</h2>
<div class="box"><b>Interpretación:</b> {{ $reporte['interpretacion'] ?? 'La información resume el estado documental de los planes incluidos.' }}</div>
<table class="charts"><tr>
<td><div class="chart"><div class="chart-title">Distribución por estado</div>@foreach(data_get($reporte,'graficos.estados',[]) as $dato)<div class="bar-row"><span class="bar-label">{{ $dato['etiqueta'] }}</span><span class="track"><span class="fill" style="width:{{ min(100,$dato['porcentaje']) }}%"></span></span><span class="bar-value">{{ $dato['cantidad'] }} ({{ $dato['porcentaje'] }}%)</span></div>@endforeach</div></td>
<td><div class="chart"><div class="chart-title">Origen de la planificación</div>@foreach(data_get($reporte,'graficos.origen',[]) as $dato)<div class="bar-row"><span class="bar-label">{{ $dato['etiqueta'] }}</span><span class="track"><span class="fill" style="width:{{ min(100,$dato['porcentaje']) }}%"></span></span><span class="bar-value">{{ $dato['cantidad'] }} ({{ $dato['porcentaje'] }}%)</span></div>@endforeach</div></td>
</tr></table>
<p class="criteria"><b>Uso recomendado:</b> revisar vigencias y estados permite reconocer planes pendientes de validación, activos y finalizados. El origen indica si hubo asistencia experta, pero la aprobación continúa siendo responsabilidad profesional.</p>
@endif
@if(($reporte['tipo'] ?? null)==='incidencias')
<h2>Lectura ejecutiva de las incidencias</h2>
<div class="box"><b>Interpretación:</b> {{ $reporte['interpretacion'] ?? 'La información resume las dificultades registradas en el seguimiento.' }}</div>
<table class="charts"><tr>
<td><div class="chart"><div class="chart-title">Incidencias por tipo</div>@foreach(data_get($reporte,'graficos.tipos',[]) as $dato)<div class="bar-row"><span class="bar-label">{{ $dato['etiqueta'] }}</span><span class="track"><span class="fill" style="width:{{ min(100,$dato['porcentaje']) }}%"></span></span><span class="bar-value">{{ $dato['cantidad'] }} ({{ $dato['porcentaje'] }}%)</span></div>@endforeach</div></td>
<td><div class="chart"><div class="chart-title">Pacientes por prioridad</div>@foreach(data_get($reporte,'graficos.prioridad',[]) as $dato)<div class="bar-row"><span class="bar-label">{{ $dato['etiqueta'] }}</span><span class="track"><span class="fill" style="width:{{ min(100,$dato['porcentaje']) }}%"></span></span><span class="bar-value">{{ $dato['cantidad'] }} ({{ $dato['porcentaje'] }}%)</span></div>@endforeach</div></td>
</tr></table>
<p class="criteria"><b>Criterio profesional:</b> una incidencia identifica una señal para revisar; no demuestra por sí sola rechazo del plan. Debe contrastarse con comentarios, síntomas, saciedad y disponibilidad de ingredientes.</p>
@endif
<p><b>Filtros aplicados:</b> @forelse(collect($filtros)->except('tipo')->filter() as $clave=>$valor)<span class="badge">{{ ucfirst(str_replace('_',' ',$clave)) }}: {{ str_replace('_',' ',$valor) }}</span>@empty<span class="badge">Sin filtros adicionales</span>@endforelse</p>
<h2>Resultados</h2>@if(count($reporte['filas'])===0)<div class="empty">No existen resultados que coincidan con los filtros.</div>@else<table class="grid"><thead><tr>@foreach($reporte['columnas'] as $titulo)<th>{{ $titulo }}</th>@endforeach</tr></thead><tbody>@foreach($reporte['filas'] as $fila)<tr>@foreach(array_keys($reporte['columnas']) as $campo)<td>{{ $fila[$campo] ?? '—' }}</td>@endforeach</tr>@endforeach</tbody></table>@endif
<footer class="footer"><b>Almendra Nutrición</b> · Reporte generado según la selección profesional. Los resultados dependen de la información registrada en el sistema.</footer></body></html>
