<!doctype html>
<html lang="es"><head><meta charset="utf-8"><title>Reporte de seguimiento y evolución nutricional</title>
<style>
@page{margin:26px 30px}body{font-family:DejaVu Sans,sans-serif;color:#263238;font-size:9px;line-height:1.35}h1{font-size:19px;color:#174d3b;margin:0}h2{font-size:12px;color:#174d3b;border-bottom:1px solid #a9c7bc;padding-bottom:4px;margin:17px 0 7px}.sub{color:#607d75}.head{border-bottom:3px solid #2f8066;padding-bottom:10px}.right{float:right;text-align:right}.clear{clear:both}.box{background:#f2f7f5;border:1px solid #d7e5df;padding:8px;margin:6px 0}.grid{width:100%;border-collapse:collapse}.grid td,.grid th{border:1px solid #d9e1de;padding:4px;vertical-align:top}.grid th{background:#e8f1ed;color:#174d3b;text-align:left;font-size:8px}.mini td{border:0;padding:2px 8px 2px 0}.badge{display:inline-block;padding:2px 5px;border-radius:8px;background:#e8f1ed;color:#174d3b}.warn{background:#fff4dc;border-left:3px solid #d99b21;padding:6px;margin:4px 0}.high{border-left-color:#b83b3b;background:#fbeaea}.good{background:#e7f5ec}.muted{color:#78908a}.page-break{page-break-before:always}ul{margin:4px 0;padding-left:16px}.footer{margin-top:20px;border-top:1px solid #aaa;padding-top:8px}.avoid-break{page-break-inside:avoid}
</style></head><body>
@php
$ant=$analitica['evolucion_antropometrica'];$adh=$analitica['evolucion_adherencia'];$sint=$analitica['analitica_sintomas'];$problemas=$analitica['problemas_practicos'];
$nombre=trim($paciente->nombres.' '.$paciente->apellido_paterno.' '.$paciente->apellido_materno);
$fmt=fn($v,$s='')=>$v===null||$v===''?'Sin registro':number_format((float)$v,1,',','.').$s;
$siNo=fn($v)=>$v?'Sí':'No';$alerta=$analitica['alertas'][0]??null;$recomendacion=$analitica['recomendaciones_siguiente_plan'][0]??null;
$tipos=collect($analitica['cumplimiento_por_tipo_comida']);$mejor=$tipos->sortByDesc('porcentaje_adherencia')->first();$menor=$tipos->filter(fn($x)=>$x['total']>0)->sortBy('porcentaje_adherencia')->first();
@endphp
<div class="head"><div class="right"><b>{{ $fechaGeneracion->format('d/m/Y H:i') }}</b><br><span class="sub">Generado por {{ $profesional->name }}</span></div><h1>Reporte de seguimiento y evolución nutricional</h1><div class="sub">Sistema experto nutricional PMOS/RI</div><div class="clear"></div></div>

<h2>Datos generales del paciente</h2><table class="grid"><tr><th>Paciente</th><th>CI / código</th><th>Edad</th><th>Sexo</th><th>Teléfono</th></tr><tr><td>{{ $nombre }}</td><td>{{ $paciente->ci ?: 'Sin registro' }}</td><td>{{ $paciente->fecha_nacimiento?->age ?? 'Sin registro' }}</td><td>{{ ucfirst($paciente->sexo ?: 'Sin registro') }}</td><td>{{ $paciente->telefono ?: 'Sin registro' }}</td></tr><tr><th>Estado</th><th colspan="2">Fecha de registro</th><th colspan="2">Plan actual</th></tr><tr><td>{{ ucfirst((string)$paciente->estado) }}</td><td colspan="2">{{ $paciente->fecha_registro?->format('d/m/Y') ?? $paciente->created_at?->format('d/m/Y') ?? 'Sin registro' }}</td><td colspan="2">{{ $planActual?->nombre ?? 'Sin plan activo o aprobado' }}</td></tr></table>

<h2>Resumen ejecutivo</h2><div class="box">Se registraron <b>{{ $ant['resumen']['total_evaluaciones'] }}</b> evaluaciones nutricionales. La adherencia promedio es <b>{{ $fmt($adh['resumen']['promedio_adherencia'],'%') }}</b>@if($mejor && $mejor['total']>0), con mejor cumplimiento en <b>{{ $mejor['tipo_comida'] }}</b>@endif @if($menor), y menor cumplimiento en <b>{{ $menor['tipo_comida'] }}</b>@endif. {{ $alerta['mensaje'] ?? 'No se identificaron alertas automáticas prioritarias.' }} {{ $recomendacion['texto'] ?? 'Se recomienda continuar el seguimiento periódico.' }}</div>

<h2>Evolución antropométrica</h2>
@if(empty($ant['registros']))<p class="muted">Sin evaluaciones antropométricas registradas.</p>@else<table class="grid"><thead><tr><th>Fecha</th><th>Peso</th><th>IMC</th><th>Cintura</th><th>Cadera</th><th>ICC</th><th>Grasa</th><th>Músculo</th></tr></thead><tbody>@foreach($ant['registros'] as $r)<tr><td>{{ $r['fecha'] ?? 'Sin registro' }}</td><td>{{ $fmt($r['peso'],' kg') }}</td><td>{{ $fmt($r['imc']) }}</td><td>{{ $fmt($r['cintura'],' cm') }}</td><td>{{ $fmt($r['cadera'],' cm') }}</td><td>{{ $fmt($r['icc']) }}</td><td>{{ $fmt($r['grasa_corporal'],'%') }}</td><td>{{ $fmt($r['masa_muscular'],' kg') }}</td></tr>@endforeach</tbody></table>
<div class="box">Peso: {{ $fmt($ant['resumen']['peso_inicial'],' kg') }} → {{ $fmt($ant['resumen']['peso_actual'],' kg') }} (cambio {{ $fmt($ant['resumen']['cambio_peso'],' kg') }}). IMC: {{ $fmt($ant['resumen']['imc_inicial']) }} → {{ $fmt($ant['resumen']['imc_actual']) }}. Cintura: {{ $fmt($ant['resumen']['cintura_inicial'],' cm') }} → {{ $fmt($ant['resumen']['cintura_actual'],' cm') }}.</div>@endif

<h2>Adherencia por plan</h2>@if(empty($adh['por_plan']))<p class="muted">Sin planes o seguimientos registrados.</p>@else<table class="grid"><tr><th>Plan</th><th>Estado</th><th>Inicio / fin</th><th>Total</th><th>Registradas</th><th>Completas</th><th>Parciales</th><th>Reemplazadas</th><th>No realizadas</th><th>Pendientes</th><th>Adherencia</th></tr>@foreach($adh['por_plan'] as $p)<tr><td>{{ $p['nombre_plan'] }}</td><td>{{ $p['estado_plan'] }}</td><td>{{ $p['fecha_inicio'] ?: '—' }}<br>{{ $p['fecha_fin'] ?: '—' }}</td><td>{{ $p['comidas_totales'] }}</td><td>{{ $p['registradas'] }}</td><td>{{ $p['completadas'] }}</td><td>{{ $p['parciales'] }}</td><td>{{ $p['reemplazadas'] }}</td><td>{{ $p['no_realizadas'] }}</td><td>{{ $p['pendientes'] }}</td><td>{{ $fmt($p['porcentaje_adherencia'],'%') }}</td></tr>@endforeach</table>@endif

<h2>Cumplimiento por tipo de comida</h2><table class="grid"><tr><th>Comida</th><th>Total</th><th>Completas</th><th>Parciales</th><th>Reemplazadas</th><th>No realizadas</th><th>Pendientes</th><th>Adherencia</th><th>Principal problema</th></tr>@foreach($analitica['cumplimiento_por_tipo_comida'] as $t)<tr><td>{{ ucfirst($t['tipo_comida']) }}</td><td>{{ $t['total'] }}</td><td>{{ $t['completadas'] }}</td><td>{{ $t['parciales'] }}</td><td>{{ $t['reemplazadas'] }}</td><td>{{ $t['no_realizadas'] }}</td><td>{{ $t['pendientes'] }}</td><td>{{ $fmt($t['porcentaje_adherencia'],'%') }}</td><td>{{ $t['principal_problema'] }}</td></tr>@endforeach</table>

<div class="page-break"></div><h2>Seguimiento de síntomas PMOS / RI</h2><div class="box">Total: {{ $sint['total_registros'] }} · Últimos 7 días: {{ $sint['ultimos_7'] }} · Últimos 30 días: {{ $sint['ultimos_30'] }}</div><table class="grid"><tr>@foreach(['hambre_nocturna_frecuente'=>'Hambre nocturna','ansiedad_comida_frecuente'=>'Ansiedad','antojos_dulces_frecuentes'=>'Antojos dulces','hinchazon_frecuente'=>'Hinchazón','baja_energia_frecuente'=>'Baja energía','sueno_deficiente_frecuente'=>'Sueño deficiente','actividad_fisica_baja'=>'Actividad baja'] as $k=>$l)<th>{{ $l }}</th>@endforeach</tr><tr>@foreach(array_keys(['hambre_nocturna_frecuente'=>1,'ansiedad_comida_frecuente'=>1,'antojos_dulces_frecuentes'=>1,'hinchazon_frecuente'=>1,'baja_energia_frecuente'=>1,'sueno_deficiente_frecuente'=>1,'actividad_fisica_baja'=>1]) as $k)<td>{{ $siNo($sint[$k]??false) }}</td>@endforeach</tr></table>
@if(!empty($sint['registros_recientes']))<h3>Registros recientes</h3><table class="grid"><tr><th>Fecha</th><th>Energía</th><th>Ansiedad</th><th>Antojos</th><th>Hambre nocturna</th><th>Hinchazón</th><th>Sueño</th><th>Actividad</th></tr>@foreach(array_slice($sint['registros_recientes'],0,7) as $r)<tr><td>{{ $r['fecha'] }}</td><td>{{ $r['energia']??'—' }}</td><td>{{ $r['ansiedad']??'—' }}</td><td>{{ $r['antojos']??'—' }}</td><td>{{ $siNo($r['hambre_nocturna']??false) }}</td><td>{{ $r['hinchazon']??'—' }}</td><td>{{ $r['sueno']??'—' }}</td><td>{{ $r['actividad']??'—' }}</td></tr>@endforeach</table>@endif

<h2>Recetas aceptadas</h2>@if(empty($analitica['recetas_aceptadas']))<p class="muted">Sin registros.</p>@else<table class="grid"><tr><th>Receta</th><th>Comida</th><th>Consumida</th><th>Me gustó</th><th>Desea repetir</th><th>Sin molestias</th><th>Puntaje</th></tr>@foreach($analitica['recetas_aceptadas'] as $r)<tr><td>{{ $r['nombre'] }}</td><td>{{ $r['tipo_comida'] }}</td><td>{{ $r['veces_consumida'] }}</td><td>{{ $r['veces_me_gusto'] }}</td><td>{{ $r['desea_repetir'] }}</td><td>{{ $r['sin_molestias'] }}</td><td>{{ $r['puntaje_aceptacion'] }}</td></tr>@endforeach</table>@endif
<h2>Recetas problemáticas o a revisar</h2>@if(empty($analitica['recetas_problematicas']))<p class="muted">Sin registros.</p>@else<table class="grid"><tr><th>Receta</th><th>Comida</th><th>Motivos</th><th>Frecuencia</th></tr>@foreach($analitica['recetas_problematicas'] as $r)<tr><td>{{ $r['nombre'] }}</td><td>{{ $r['tipo_comida'] }}</td><td>{{ implode(', ',array_map(fn($x)=>str_replace('_',' ',$x),$r['motivos'])) }}</td><td>{{ $r['frecuencia'] }}</td></tr>@endforeach</table>@endif

<h2>Problemas prácticos detectados</h2><table class="grid"><tr><th>Ingredientes no conseguidos</th><th>Recetas difíciles</th><th>Comidas reemplazadas</th><th>Motivos frecuentes</th><th>Horarios problemáticos</th></tr><tr><td>{{ collect($problemas['ingredientes_no_conseguidos'])->pluck('nombre')->join(', ') ?: 'Sin registros' }}</td><td>{{ collect($problemas['recetas_dificiles'])->pluck('nombre')->join(', ') ?: 'Sin registros' }}</td><td>{{ $problemas['comidas_reemplazadas'] }}</td><td>@forelse($problemas['motivos_no_cumplimiento_frecuentes'] as $k=>$v){{ str_replace('_',' ',$k) }} ({{ $v }})@if(!$loop->last), @endif @empty Sin registros @endforelse</td><td>@forelse($problemas['horarios_problematicos'] as $k=>$v){{ $k }} ({{ $v }})@if(!$loop->last), @endif @empty Sin registros @endforelse</td></tr></table>

<h2>Retroalimentaciones recientes</h2>@if($retroalimentaciones->isEmpty())<p class="muted">Sin registros.</p>@else<table class="grid"><tr><th>Fecha</th><th>Tipo</th><th>Prioridad</th><th>Mensaje</th><th>Leído por paciente</th></tr>@foreach($retroalimentaciones as $r)<tr><td>{{ $r->created_at?->format('d/m/Y') }}</td><td>{{ str_replace('_',' ',$r->tipo_retroalimentacion) }}</td><td>{{ $r->prioridad ?: 'normal' }}</td><td>{{ $r->mensaje }}</td><td>{{ $siNo($r->leido_por_paciente) }}</td></tr>@endforeach</table>@endif

<h2>Alertas automáticas</h2>@forelse($analitica['alertas'] as $a)<div class="warn {{ $a['severidad']==='alta'?'high':'' }}"><b>{{ ucfirst($a['tipo']) }} · {{ ucfirst($a['severidad']) }}</b><br>{{ $a['mensaje'] }} <span class="muted">{{ $a['recomendacion'] }}</span></div>@empty<p class="muted">Sin alertas automáticas.</p>@endforelse
<h2>Recomendaciones para el siguiente plan</h2>@forelse($analitica['recomendaciones_siguiente_plan'] as $r)<div class="box"><span class="badge">{{ str_replace('_',' ',$r['origen']) }}</span> {{ $r['texto'] }}</div>@empty<p class="muted">Sin recomendaciones adicionales.</p>@endforelse

<h2>Conclusión de seguimiento</h2><p>El seguimiento registrado permite identificar patrones de adherencia, tolerancia alimentaria y síntomas asociados que pueden orientar la siguiente planificación nutricional. Se recomienda considerar las recetas mejor aceptadas, evitar temporalmente preparaciones problemáticas y ajustar los tiempos de comida con menor cumplimiento.</p>
<div class="footer"><b>Generado por:</b> {{ $profesional->name }} &nbsp; <b>Fecha:</b> {{ $fechaGeneracion->format('d/m/Y H:i') }}<br><span class="muted">Documento de apoyo para revisión nutricional. No constituye un diagnóstico médico definitivo.</span></div>
</body></html>
