<!doctype html><html lang="es"><head><meta charset="utf-8"><title>Reporte de cambios del plan</title><style>@page{margin:28px}body{font-family:DejaVu Sans,sans-serif;color:#243b35;font-size:10px;line-height:1.4}h1{color:#175b46;font-size:20px}h2{color:#175b46;font-size:13px;border-bottom:1px solid #b9d4ca;padding-bottom:4px;margin-top:18px}.box{background:#f1f7f5;border:1px solid #d6e5df;padding:9px;margin:6px 0}.grid{width:100%;border-collapse:collapse}.grid th,.grid td{border:1px solid #d5dfdc;padding:5px}.grid th{background:#e6f0ec;text-align:left}.tag{display:inline-block;background:#e6f0ec;padding:2px 6px;margin:2px;border-radius:8px}.muted{color:#687d76}ul{padding-left:17px}</style></head><body>
@php $nombre=trim($paciente->nombres.' '.$paciente->apellido_paterno.' '.$paciente->apellido_materno); @endphp
<h1>Reporte de cambios del plan alimentario</h1><p class="muted">Generado {{ $fechaGeneracion->format('d/m/Y H:i') }} por {{ $profesional->name }}</p>
<h2>Paciente y planes comparados</h2><table class="grid"><tr><th>Paciente</th><th>Plan anterior</th><th>Plan nuevo</th></tr><tr><td>{{ $nombre }}</td><td>{{ $planAnterior?->nombre ?? 'Sin plan anterior' }}</td><td>{{ $planNuevo->nombre }}</td></tr></table>
<div class="box">{{ $reporte['resumen'] }}</div>
<h2>Cambios nutricionales</h2>@if(empty($reporte['cambios_nutricionales']))<p>Sin plan anterior para calcular diferencias.</p>@else<table class="grid"><tr><th>Indicador</th><th>Antes</th><th>Después</th><th>Diferencia</th></tr>@foreach($reporte['cambios_nutricionales'] as $k=>$c)<tr><td>{{ ucfirst($k) }}</td><td>{{ number_format($c['antes'],1) }}</td><td>{{ number_format($c['despues'],1) }}</td><td>{{ $c['diferencia']>0?'+':'' }}{{ number_format($c['diferencia'],1) }}</td></tr>@endforeach</table>@endif
<h2>Cambios de recetas</h2><p><b>Mantenidas:</b> {{ implode(', ',$reporte['cambios_recetas']['recetas_mantenidas']) ?: 'Ninguna' }}</p><p><b>Nuevas:</b> {{ implode(', ',$reporte['cambios_recetas']['recetas_nuevas']) ?: 'Ninguna' }}</p><p><b>Retiradas:</b> {{ implode(', ',$reporte['cambios_recetas']['recetas_retiradas']) ?: 'Ninguna' }}</p><p>Componentes manuales: {{ $reporte['cambios_recetas']['manuales_antes'] }} → {{ $reporte['cambios_recetas']['manuales_despues'] }}</p>
<h2>Motivos y sugerencias consideradas</h2><ul>@forelse($reporte['motivos_cambio'] as $m)<li>{{ $m }}</li>@empty<li>Sin motivos automáticos adicionales.</li>@endforelse</ul>
<h2>Alertas, síntomas y seguimiento</h2><p>@forelse($reporte['alertas_consideradas'] as $a)<span class="tag">{{ $a }}</span>@empty Sin alertas automáticas relevantes. @endforelse</p><p><b>Adherencia del plan anterior:</b> {{ $reporte['adherencia_plan_anterior']===null?'Sin registro':$reporte['adherencia_plan_anterior'].'%' }}</p>
<h2>Fuentes consideradas</h2><ul>@foreach($reporte['datos_considerados'] as $d)<li>{{ $d }}</li>@endforeach</ul>
<h2>Conclusión</h2><div class="box">El nuevo plan fue ajustado considerando seguimiento del paciente, aceptación alimentaria, síntomas recientes y retroalimentación profesional.</div>
</body></html>
