import axios, { AxiosError } from 'axios';
import { LoaderCircle, Search, X } from 'lucide-react';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import type { CatalogoAlimento, CatalogoReceta, ComidaPlan, ComponentePlan } from '@/Pages/Nutricionista/Pacientes/PerfilNutricional/tipos';

interface Props { abierto:boolean; cerrar:()=>void; comida:ComidaPlan|null; componente?:ComponentePlan|null; alimentos:CatalogoAlimento[]; recetas:CatalogoReceta[]; onSuccess:()=>void }
type Tipo='receta'|'alimento'|'manual';
const num=(v:unknown)=>Number(v??0);
const errorDe=(e:unknown)=>{const d=(e as AxiosError<{message?:string;errors?:Record<string,string[]>}>).response?.data;return Object.values(d?.errors??{})[0]?.[0]??d?.message??'No se pudo guardar el componente.'};

export default function ModalComponentePlan({abierto,cerrar,comida,componente,alimentos,recetas,onSuccess}:Props){
 const [tipo,setTipo]=useState<Tipo>('receta'); const [seleccion,setSeleccion]=useState(''); const [buscar,setBuscar]=useState('');
 const [nombre,setNombre]=useState(''); const [cantidad,setCantidad]=useState('1'); const [unidad,setUnidad]=useState('porción');
 const [calorias,setCalorias]=useState('0'); const [proteinas,setProteinas]=useState('0'); const [carbohidratos,setCarbohidratos]=useState('0'); const [grasas,setGrasas]=useState('0'); const [fibra,setFibra]=useState('0'); const [observaciones,setObservaciones]=useState('');
 const [guardando,setGuardando]=useState(false); const [error,setError]=useState('');
 useEffect(()=>{if(!abierto)return;const t=(componente?.tipo_componente??'receta') as Tipo;setTipo(t);setSeleccion(String(t==='receta'?componente?.id_receta??'':t==='alimento'?componente?.id_alimento??'':''));setNombre(componente?.nombre_manual??'');setCantidad(String(componente?.cantidad??1));setUnidad(componente?.unidad??'porción');setCalorias(String(componente?.calorias??0));setProteinas(String(componente?.proteinas??0));setCarbohidratos(String(componente?.carbohidratos??0));setGrasas(String(componente?.grasas??0));setFibra(String(componente?.fibra??0));setObservaciones(componente?.observaciones??'');setBuscar('');setError('')},[abierto,componente]);
 const recetasFiltradas=useMemo(()=>recetas.filter(r=>r.nombre.toLowerCase().includes(buscar.toLowerCase())).sort((a,b)=>Number(b.tipo_comida===comida?.tipo_comida)-Number(a.tipo_comida===comida?.tipo_comida)),[recetas,buscar,comida]);
 const alimentosFiltrados=useMemo(()=>alimentos.filter(a=>a.nombre.toLowerCase().includes(buscar.toLowerCase())),[alimentos,buscar]);
 const origen=tipo==='receta'?recetas.find(r=>r.id_receta===Number(seleccion)):tipo==='alimento'?alimentos.find(a=>a.id_alimento===Number(seleccion)):null;
 const factor=tipo==='receta'?num(cantidad):tipo==='alimento'?num(cantidad)/Math.max(num((origen as CatalogoAlimento|undefined)?.cantidad_base),.01):1;
 const vista=tipo==='manual'?{calorias:num(calorias),proteinas:num(proteinas),carbohidratos:num(carbohidratos),grasas:num(grasas),fibra:num(fibra)}:tipo==='receta'?{calorias:num((origen as CatalogoReceta|undefined)?.calorias_totales)*factor,proteinas:num((origen as CatalogoReceta|undefined)?.proteinas_totales)*factor,carbohidratos:num((origen as CatalogoReceta|undefined)?.carbohidratos_totales)*factor,grasas:num((origen as CatalogoReceta|undefined)?.grasas_totales)*factor,fibra:num((origen as CatalogoReceta|undefined)?.fibra_total)*factor}:{calorias:num((origen as CatalogoAlimento|undefined)?.calorias)*factor,proteinas:num((origen as CatalogoAlimento|undefined)?.proteinas)*factor,carbohidratos:num((origen as CatalogoAlimento|undefined)?.carbohidratos)*factor,grasas:num((origen as CatalogoAlimento|undefined)?.grasas)*factor,fibra:num((origen as CatalogoAlimento|undefined)?.fibra)*factor};
 if(!abierto||!comida)return null;
 const guardar=async(e:FormEvent)=>{e.preventDefault();setGuardando(true);setError('');const data:Record<string,unknown>={tipo_componente:tipo,cantidad:num(cantidad),unidad,observaciones:observaciones||null};if(tipo==='receta')data.id_receta=Number(seleccion);if(tipo==='alimento')data.id_alimento=Number(seleccion);if(tipo==='manual')Object.assign(data,{nombre_manual:nombre,calorias:num(calorias),proteinas:num(proteinas),carbohidratos:num(carbohidratos),grasas:num(grasas),fibra:num(fibra)});try{if(componente)await axios.patch(`/nutricionista/componentes-plan/${componente.id_componente_comida_plan}`,data,{headers:{Accept:'application/json'}});else await axios.post(`/nutricionista/comidas-plan/${comida.id_comida_plan_alimentario}/componentes`,data,{headers:{Accept:'application/json'}});cerrar();onSuccess()}catch(x){setError(errorDe(x))}finally{setGuardando(false)}};
 return <dialog className="modal modal-open"><div className="modal-box max-w-3xl"><div className="flex justify-between gap-3"><div><h3 className="text-lg font-bold">{componente?'Editar':'Agregar'} componente</h3><p className="text-sm text-base-content/60">{comida.nombre_comida} · el cálculo definitivo se realiza en el servidor.</p></div><button className="btn btn-circle btn-ghost btn-sm" onClick={cerrar}><X size={17}/></button></div><form className="mt-5 space-y-4" onSubmit={guardar}>
  <div className="tabs tabs-boxed grid grid-cols-3">{(['receta','alimento','manual'] as Tipo[]).map(t=><button type="button" key={t} className={`tab capitalize ${tipo===t?'tab-active':''}`} onClick={()=>{setTipo(t);setSeleccion('')}}>{t}</button>)}</div>
  {tipo!=='manual'&&<><label className="input input-bordered flex items-center gap-2"><Search size={16}/><input className="grow" placeholder={`Buscar ${tipo}...`} value={buscar} onChange={e=>setBuscar(e.target.value)}/></label><label className="form-control"><span className="label-text mb-1 font-semibold">{tipo==='receta'?'Receta':'Alimento'}</span><select className="select select-bordered" required value={seleccion} onChange={e=>{setSeleccion(e.target.value);const a=alimentos.find(x=>x.id_alimento===Number(e.target.value));if(tipo==='alimento'&&a)setUnidad(a.unidad_base)}}><option value="">Seleccionar…</option>{tipo==='receta'?recetasFiltradas.map(r=><option key={r.id_receta} value={r.id_receta}>{r.nombre} · {r.tipo_comida} · {r.calorias_totales} kcal · P {r.proteinas_totales} · C {r.carbohidratos_totales} · G {r.grasas_totales} · F {r.fibra_total}</option>):alimentosFiltrados.map(a=><option key={a.id_alimento} value={a.id_alimento}>{a.nombre} · {a.grupo_alimentario??'sin grupo'} · {a.calorias} kcal · P {a.proteinas} · C {a.carbohidratos} · G {a.grasas} · F {a.fibra}</option>)}</select></label></>}
  {tipo==='manual'&&<label className="form-control"><span className="label-text mb-1 font-semibold">Nombre</span><input className="input input-bordered" required value={nombre} onChange={e=>setNombre(e.target.value)}/></label>}
  <div className="grid gap-3 sm:grid-cols-2"><label className="form-control"><span className="label-text mb-1">Cantidad</span><input className="input input-bordered" required type="number" min="0.01" step="0.01" value={cantidad} onChange={e=>setCantidad(e.target.value)}/></label><label className="form-control"><span className="label-text mb-1">Unidad</span><input className="input input-bordered" required value={unidad} onChange={e=>setUnidad(e.target.value)}/></label></div>
  {tipo==='manual'&&<div className="grid grid-cols-2 gap-3 sm:grid-cols-5">{([['Calorías',calorias,setCalorias],['Proteínas',proteinas,setProteinas],['Carbohidratos',carbohidratos,setCarbohidratos],['Grasas',grasas,setGrasas],['Fibra',fibra,setFibra]] as const).map(([l,v,s])=><label className="form-control" key={l}><span className="label-text mb-1 text-xs">{l}</span><input className="input input-bordered input-sm" required type="number" min="0" step="0.01" value={v} onChange={e=>s(e.target.value)}/></label>)}</div>}
  <div className="rounded-xl bg-base-200 p-3"><p className="mb-2 text-xs font-bold uppercase text-base-content/50">Vista previa nutricional</p><div className="grid grid-cols-5 gap-2 text-center text-xs">{Object.entries(vista).map(([k,v])=><div key={k}><p className="capitalize text-base-content/50">{k}</p><b>{v.toFixed(1)}</b></div>)}</div></div>
  <label className="form-control"><span className="label-text mb-1">Observaciones</span><textarea className="textarea textarea-bordered" maxLength={1000} value={observaciones} onChange={e=>setObservaciones(e.target.value)}/></label>{error&&<div className="alert alert-error py-2 text-sm">{error}</div>}<div className="modal-action"><button type="button" className="btn btn-ghost" onClick={cerrar}>Cancelar</button><button className="btn btn-primary" disabled={guardando}>{guardando&&<LoaderCircle className="animate-spin" size={16}/>}Guardar componente</button></div>
 </form></div><button className="modal-backdrop" onClick={cerrar}>Cerrar</button></dialog>
}
