import axios, { AxiosError } from 'axios';
import { router } from '@inertiajs/react';
import { AlertTriangle, CalendarDays, CheckCircle2, ChevronDown, ChevronUp, FileDown, LoaderCircle, Pencil, Plus, Sparkles, Trash2, XCircle } from 'lucide-react';
import { useState } from 'react';
import type { CatalogoAlimento, CatalogoReceta, ComidaPlan, ComponentePlan, DiaPlan, PlanAlimentario, RecomendacionNutricionalExperta } from '@/Pages/Nutricionista/Pacientes/PerfilNutricional/tipos';
import ModalComponentePlan from './ModalComponentePlan';
import ModalEditarComidaPlan from './ModalEditarComidaPlan';

interface Props { plan:PlanAlimentario|null; recomendacion:RecomendacionNutricionalExperta|null; puedeGenerar:boolean; alimentos:CatalogoAlimento[]; recetas:CatalogoReceta[] }
type Accion=(clave:string,fn:()=>Promise<unknown>)=>void;
const num=(v:unknown)=>Number(v??0); const n=(v:unknown)=>num(v).toLocaleString('es-BO',{maximumFractionDigits:2}); const etiqueta=(v:string|null|undefined)=>v?.replaceAll('_',' ')??'No definido';
const errorDe=(e:unknown)=>{const d=(e as AxiosError<{message?:string;errors?:Record<string,string[]>}>).response?.data;return Object.values(d?.errors??{})[0]?.[0]??d?.message??'No se pudo completar la operación.'};

export default function PlanAlimentarioCard({plan,recomendacion,puedeGenerar,alimentos,recetas}:Props){
 const [detalle,setDetalle]=useState(false),[cargando,setCargando]=useState(''),[mensaje,setMensaje]=useState(''),[esError,setEsError]=useState(false),[modalCiclo,setModalCiclo]=useState(false),[fechaNuevo,setFechaNuevo]=useState(''),[observacion,setObservacion]=useState('');
 const recargar=()=>router.reload({only:['planAlimentarioPrincipal','recomendacionExpertaAprobada','puedeGenerarPlanSemanal','historialPlanes','analiticaEvolucion','seguimientoPaciente']});
 const accion:Accion=async(clave,fn)=>{setCargando(clave);setMensaje('');try{await fn();setEsError(false);setMensaje('Operación realizada correctamente.');recargar()}catch(e){setEsError(true);setMensaje(errorDe(e))}finally{setCargando('')}};
 const generar=()=>recomendacion&&accion('generar',()=>axios.post(`/nutricionista/recomendaciones-expertas/${recomendacion.id_recomendacion_nutricional_experta}/generar-plan`,{},{headers:{Accept:'application/json'}}));
 const cambiarEstado=(estado:'aprobado'|'rechazado')=>plan&&accion(estado,()=>axios.patch(`/nutricionista/planes-alimentarios/${plan.id_plan_alimentario}/estado`,{estado_plan:estado},{headers:{Accept:'application/json'}}));
 const editable=!!plan&&['sugerido','en_revision'].includes(plan.estado_plan);
 const finalizable=!!plan&&['aprobado','activo'].includes(plan.estado_plan);
 const finalizar=()=>plan&&router.post(route('nutricionista.planes.finalizar-y-generar-siguiente',plan.id_plan_alimentario),{fecha_inicio:fechaNuevo||null,observacion_finalizacion:observacion||null},{preserveScroll:true,onStart:()=>setCargando('finalizar'),onSuccess:()=>{setModalCiclo(false);setEsError(false);setMensaje('Plan finalizado y nueva planificación generada correctamente.');recargar()},onError:e=>{setEsError(true);setMensaje(Object.values(e)[0]??'No se pudo finalizar el plan.')},onFinish:()=>setCargando('')});
 return <article className="card overflow-hidden border border-base-300 bg-base-100 shadow-sm"><div className="h-1.5 bg-gradient-to-r from-primary via-secondary to-success"/><div className="card-body gap-5 p-4 sm:p-6">
  <header className="flex flex-wrap justify-between gap-3"><div className="flex gap-3"><span className="rounded-2xl bg-success/10 p-3 text-success"><CalendarDays size={22}/></span><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-primary">Planificación profesional</p><h3 className="text-lg font-bold">Plan alimentario semanal</h3><p className="text-xs text-base-content/60">7 días · desayuno, almuerzo, merienda y cena</p></div></div>{plan&&<span className="badge badge-outline capitalize">{etiqueta(plan.estado_plan)}</span>}</header>
  {!plan&&!puedeGenerar&&<div className="alert alert-warning text-sm"><AlertTriangle size={17}/>Primero debe existir una recomendación nutricional aprobada.</div>}
  {!plan&&puedeGenerar&&<div className="rounded-2xl border border-dashed p-6 text-center"><p className="text-sm text-base-content/60">La recomendación está lista para convertirse en un plan semanal.</p><button className="btn btn-primary btn-sm mt-4" onClick={generar} disabled={!!cargando}>{cargando==='generar'?<LoaderCircle className="animate-spin" size={15}/>:<Plus size={15}/>}Generar plan</button></div>}
  {finalizable&&<button className="btn btn-warning btn-sm self-start" onClick={()=>setModalCiclo(true)}><CalendarDays size={15}/>Finalizar plan y generar siguiente planificación</button>}
  {plan&&<><Origen plan={plan} recomendacion={plan.recomendacion_nutricional_experta??recomendacion}/><div className="grid gap-3 md:grid-cols-3"><Dato l="Plan" v={plan.nombre}/><Dato l="Vigencia" v={`${plan.fecha_inicio??'—'} — ${plan.fecha_fin??'—'}`}/><Dato l="Energía semanal" v={`${n(plan.calorias_totales)} kcal`}/></div><Resumen plan={plan}/><div className="flex flex-wrap gap-2"><button className="btn btn-primary btn-sm" onClick={()=>setDetalle(!detalle)}>{detalle?<ChevronUp size={15}/>:<ChevronDown size={15}/>} {detalle?'Ocultar detalle':'Ver planificación completa'}</button><a className="btn btn-outline btn-sm" href={route('nutricionista.planes.reporte-pdf',plan.id_plan_alimentario)} target="_blank" rel="noreferrer"><FileDown size={15}/>Descargar reporte PDF</a>{editable&&<><button className="btn btn-success btn-sm" onClick={()=>cambiarEstado('aprobado')}><CheckCircle2 size={15}/>Aprobar</button><button className="btn btn-error btn-outline btn-sm" onClick={()=>cambiarEstado('rechazado')}><XCircle size={15}/>Rechazar</button></>}</div>{!editable&&<div className="alert py-2 text-sm"><CheckCircle2 size={16}/>Este plan ya fue validado y no puede editarse.</div>}{detalle&&<div className="space-y-4">{plan.dias.map(d=><Dia key={d.id_dia_plan_alimentario} dia={d} editable={editable} alimentos={alimentos} recetas={recetas} accion={accion} recargar={recargar}/>)}</div>}</>}
  {mensaje&&<div className={`alert py-2 text-xs ${esError?'alert-error':'alert-success'}`}>{mensaje}</div>}
  {modalCiclo&&<div className="modal modal-open"><div className="modal-box"><h3 className="text-lg font-bold">Finalizar plan actual</h3><p className="mt-2 text-sm text-base-content/65">Esta acción cerrará el plan actual y generará una nueva planificación utilizando el seguimiento, síntomas y retroalimentación registrados.</p><label className="form-control mt-4"><span className="label-text">Fecha de inicio del nuevo plan (opcional)</span><input className="input input-bordered mt-1" type="date" value={fechaNuevo} onChange={e=>setFechaNuevo(e.target.value)}/></label><label className="form-control mt-3"><span className="label-text">Observación de finalización (opcional)</span><textarea className="textarea textarea-bordered mt-1" maxLength={1000} value={observacion} onChange={e=>setObservacion(e.target.value)}/></label><div className="modal-action"><button className="btn" disabled={!!cargando} onClick={()=>setModalCiclo(false)}>Cancelar</button><button className="btn btn-warning" disabled={!!cargando} onClick={finalizar}>{cargando==='finalizar'&&<LoaderCircle className="animate-spin" size={15}/>}Finalizar y generar</button></div></div></div>}
 </div></article>
}
function Origen({plan,recomendacion}:{plan:PlanAlimentario;recomendacion:RecomendacionNutricionalExperta|null}){return <section className="rounded-2xl border border-primary/20 bg-primary/5 p-4"><div className="flex flex-wrap justify-between gap-2"><div><h4 className="font-bold">Origen del plan</h4><p className="text-xs text-base-content/60">{plan.generado_por_sistema_experto?'Generado desde una recomendación nutricional experta aprobada.':'Elaborado manualmente por nutricionista.'}</p></div>{plan.generado_por_sistema_experto&&<span className="badge badge-primary gap-1"><Sparkles size={12}/>Sistema experto</span>}</div>{recomendacion&&<div className="mt-3 grid gap-2 text-xs sm:grid-cols-3"><DatoMini l="Enfoque" v={etiqueta(recomendacion.enfoque_nutricional_experto)}/><DatoMini l="Prioridad" v={etiqueta(recomendacion.prioridad_nutricional)}/><DatoMini l="Validación" v={etiqueta(recomendacion.estado_validacion_experta)}/></div>}</section>}
function Resumen({plan}:{plan:PlanAlimentario}){const dias=Math.max(plan.duracion_dias||7,1);const datos=[['Calorías',plan.calorias_objetivo,plan.calorias_totales,'kcal'],['Proteínas',plan.proteinas_objetivo,plan.proteinas_totales,'g'],['Carbohidratos',plan.carbohidratos_objetivo,plan.carbohidratos_totales,'g'],['Grasas',plan.grasas_objetivo,plan.grasas_totales,'g'],['Fibra',plan.fibra_objetivo,plan.fibra_total,'g']] as const;return <section><h4 className="mb-2 text-sm font-bold">Balance semanal</h4><div className="grid gap-2 md:grid-cols-5">{datos.map(([l,o,p,u])=>{const objetivo=num(o)*dias,pct=objetivo?num(p)/objetivo*100:0,alerta=Math.abs(pct-100)>15;return <div className={`rounded-xl border p-3 ${alerta?'border-warning/50 bg-warning/5':'border-base-300'}`} key={l}><b className="text-xs">{l}</b><p className="mt-1 text-xs">{n(p)} / {n(objetivo)} {u}</p><progress className={`progress mt-2 w-full ${alerta?'progress-warning':'progress-success'}`} value={Math.min(pct,100)} max="100"/></div>})}</div></section>}
function Dia({dia,editable,alimentos,recetas,accion,recargar}:{dia:DiaPlan;editable:boolean;alimentos:CatalogoAlimento[];recetas:CatalogoReceta[];accion:Accion;recargar:()=>void}){return <details className="collapse collapse-arrow border border-base-300"><summary className="collapse-title"><b>{dia.nombre_dia}</b><span className="badge badge-ghost badge-sm ml-2">{n(dia.calorias_totales)} kcal</span></summary><div className="collapse-content grid gap-3 xl:grid-cols-2">{dia.comidas.map(c=><Comida key={c.id_comida_plan_alimentario} comida={c} editable={editable} alimentos={alimentos} recetas={recetas} accion={accion} recargar={recargar}/>)}</div></details>}
function Comida({comida,editable,alimentos,recetas,accion,recargar}:{comida:ComidaPlan;editable:boolean;alimentos:CatalogoAlimento[];recetas:CatalogoReceta[];accion:Accion;recargar:()=>void}){const [editarComida,setEditarComida]=useState(false),[modalComponente,setModalComponente]=useState(false),[seleccionado,setSeleccionado]=useState<ComponentePlan|null>(null);const manual=comida.componentes.some(c=>c.tipo_componente==='manual');return <section className={`rounded-2xl border p-4 ${manual?'border-warning/50 bg-warning/5':'border-base-300'}`}><div className="flex justify-between gap-2"><div><span className="badge badge-primary badge-outline badge-sm capitalize">{etiqueta(comida.tipo_comida)}</span><h5 className="mt-2 font-bold">{comida.nombre_comida}</h5><p className="text-xs text-base-content/55">{String(comida.hora_sugerida??'').slice(0,5)||'Sin hora'}</p></div>{editable&&<button className="btn btn-ghost btn-xs gap-1" onClick={()=>setEditarComida(true)}><Pencil size={13}/>Editar comida</button>}</div><Macros valores={[comida.calorias_totales,comida.proteinas_totales,comida.carbohidratos_totales,comida.grasas_totales,comida.fibra_total]}/>{manual&&<div className="alert alert-warning mt-3 py-2 text-xs"><AlertTriangle size={14}/>Esta comida requiere revisión.</div>}{comida.componentes.length===0&&<div className="alert alert-warning mt-3 py-2 text-xs">Esta comida no tiene componentes.</div>}<div className="mt-3 space-y-3">{comida.componentes.map(c=><Componente key={c.id_componente_comida_plan} c={c} editable={editable} editar={()=>{setSeleccionado(c);setModalComponente(true)}} eliminar={()=>confirm('¿Eliminar este componente?')&&accion(`eliminar-${c.id_componente_comida_plan}`,()=>axios.delete(`/nutricionista/componentes-plan/${c.id_componente_comida_plan}`,{headers:{Accept:'application/json'}}))}/>)}</div>{editable&&<button className="btn btn-ghost btn-xs mt-3" onClick={()=>{setSeleccionado(null);setModalComponente(true)}}><Plus size={13}/>Agregar componente</button>}<ModalEditarComidaPlan abierto={editarComida} comida={comida} cerrar={()=>setEditarComida(false)} onSuccess={recargar}/><ModalComponentePlan abierto={modalComponente} cerrar={()=>setModalComponente(false)} comida={comida} componente={seleccionado} alimentos={alimentos} recetas={recetas} onSuccess={recargar}/></section>}
function Componente({c,editable,editar,eliminar}:{c:ComponentePlan;editable:boolean;editar:()=>void;eliminar:()=>void}){const modificado=c.observaciones?.includes('Modificado manualmente por nutricionista.');return <article className="rounded-xl border border-base-300 bg-base-200/40 p-3 text-xs"><div className="flex justify-between gap-2"><div><div className="flex gap-1"><span className="badge badge-sm capitalize">{c.tipo_componente}</span>{c.tipo_componente==='receta'&&!modificado&&<span className="badge badge-secondary badge-sm">Sistema experto</span>}{modificado&&<span className="badge badge-info badge-sm">Modificado</span>}</div><h6 className="mt-2 font-bold">{c.receta?.nombre??c.alimento?.nombre??c.nombre_manual}</h6><p>{n(c.cantidad)} {c.unidad}</p></div>{editable&&<div><button className="btn btn-ghost btn-xs" onClick={editar}><Pencil size={13}/></button><button className="btn btn-error btn-ghost btn-xs" onClick={eliminar}><Trash2 size={13}/></button></div>}</div><Macros valores={[c.calorias,c.proteinas,c.carbohidratos,c.grasas,c.fibra]}/>{c.observaciones&&<p className="mt-2 text-base-content/60">{c.observaciones}</p>}</article>}
function Macros({valores}:{valores:unknown[]}){return <div className="mt-3 grid grid-cols-5 gap-1 rounded-xl bg-base-100 p-2 text-center text-[10px]">{['kcal','Proteína','Carbos','Grasas','Fibra'].map((l,i)=><div key={l}><p className="text-base-content/45">{l}</p><b>{n(valores[i])}</b></div>)}</div>}
function Dato({l,v}:{l:string;v:string}){return <div className="rounded-xl bg-base-200/50 p-3"><p className="text-[10px] font-bold uppercase text-base-content/45">{l}</p><p className="mt-1 text-sm font-semibold">{v}</p></div>}
function DatoMini({l,v}:{l:string;v:string}){return <div><p className="text-[9px] font-bold uppercase text-base-content/45">{l}</p><p className="font-semibold capitalize">{v}</p></div>}
