import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import AvatarPaciente from '@/Components/ui/avatar-paciente';
import { Head, Link, router, usePage } from '@inertiajs/react';
import { Bell, CalendarClock, CheckCheck, Clock3 } from 'lucide-react';
import type { PageProps } from '@/types';

type N={id_notificacion_interna:number;titulo:string;mensaje:string;prioridad:string;leida:boolean;url_destino:string|null;created_at:string};
export default function Index({listadoNotificaciones}:{listadoNotificaciones:{data:N[]}}){
 const {alertas_vigencia}=usePage<PageProps>().props, alertas=alertas_vigencia?.items??[];
 return <AuthenticatedLayout title="Notificaciones"><Head title="Notificaciones"/><main className="mx-auto max-w-5xl space-y-4">
  <section className="card-elevated overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-surface-border p-4 dark:border-surface-border-dark"><div><h2 className="flex items-center gap-2 text-[13px] font-bold text-ink dark:text-ink-dark"><CalendarClock size={16} className="text-brand-orange"/> Vigencia de planes</h2><p className="mt-1 text-[9.5px] text-ink-muted">Avisos activos que permanecen hasta renovar o finalizar la planificación.</p></div><Link href="/nutricionista/vigencia-planes" className="rounded-lg bg-brand-orange/10 px-3 py-2 text-[9.5px] font-bold text-brand-orange">Abrir calendario</Link></div>
   {alertas.length?<div className="grid gap-2 p-3 md:grid-cols-2">{alertas.map(a=><Link key={a.id_plan_alimentario} href={`/nutricionista/pacientes/${a.paciente.id_paciente}/perfil-nutricional?step=planificacion`} className="rounded-xl border border-brand-orange/20 bg-brand-orange/[.025] p-3 hover:border-brand-orange/40"><div className="flex items-center gap-3"><AvatarPaciente nombre={a.paciente.nombre} avatarUrl={a.paciente.avatar_url} size="sm"/><div className="min-w-0 flex-1"><p className="truncate text-[10.5px] font-bold text-ink dark:text-ink-dark">{a.paciente.nombre}</p><p className="truncate text-[8.5px] text-ink-muted">{a.nombre_plan}</p></div><span className="inline-flex shrink-0 items-center gap-1 text-[8.5px] font-bold text-brand-orange"><Clock3 size={9}/>{a.dias_restantes<0?`Venció hace ${Math.abs(a.dias_restantes)} d.`:a.dias_restantes===0?'Vence hoy':`Faltan ${a.dias_restantes} d.`}</span></div></Link>)}</div>:<p className="p-6 text-center text-[10px] text-ink-muted">No hay planes vencidos ni próximos a vencer.</p>}
  </section>
  <div className="flex items-center justify-between"><div><h2 className="text-[13px] font-bold text-ink dark:text-ink-dark">Mensajes del sistema</h2><p className="text-[9.5px] text-ink-muted">Comunicaciones y eventos registrados.</p></div>{listadoNotificaciones.data.length>0&&<button onClick={()=>router.post('/notificaciones/leer-todas')} className="flex items-center gap-2 rounded-xl border px-4 py-2 text-xs"><CheckCheck size={15}/>Marcar todas como leídas</button>}</div>
  {listadoNotificaciones.data.length?listadoNotificaciones.data.map(n=><button key={n.id_notificacion_interna} onClick={()=>router.post(`/notificaciones/${n.id_notificacion_interna}/leer`)} className="card-elevated flex w-full gap-3 p-4 text-left"><Bell size={18} className={n.leida?'text-ink-muted':'text-brand-green'}/><div><p className="text-xs font-bold text-ink dark:text-ink-dark">{n.titulo}</p><p className="mt-1 text-[11px] text-ink-muted">{n.mensaje}</p><p className="mt-2 text-[9px] uppercase text-ink-muted">Prioridad {n.prioridad}</p></div></button>):<div className="card-elevated p-8 text-center text-[11px] text-ink-muted">No hay otros mensajes pendientes.</div>}
 </main></AuthenticatedLayout>;
}
