import { CalendarDays, Clock3, History, MapPin, UserRound } from 'lucide-react';

interface CitaPaciente {id_cita:number;fecha:string;hora_inicio:string;hora_fin:string;profesional:string;area:string;motivo:string|null;tipo_cita:string|null;modalidad:string|null;estado:string;observaciones:string|null}
export interface CitasPaciente {proxima_cita:CitaPaciente|null;citas_pendientes:CitaPaciente[];citas_historial:CitaPaciente[];resumen:{total_citas:number;pendientes:number;realizadas:number;canceladas:number;ultima_cita:string|null;proxima_fecha:string|null}}
const etiqueta=(estado:string)=>({programada:'Programada',confirmada:'Confirmada',atendida:'Realizada',cancelada:'Cancelada',reprogramada:'Reprogramada',no_asistio:'No asistió'}[estado]??estado.replaceAll('_',' '));
const badge=(estado:string)=>['programada','confirmada'].includes(estado)?'badge-info':['atendida'].includes(estado)?'badge-success':['cancelada','no_asistio'].includes(estado)?'badge-error':'badge-ghost';

export default function CitasPacienteCard({citas}:{citas:CitasPaciente|null}){
 if(!citas)return null;const proxima=citas.proxima_cita;
 return <section className="space-y-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-primary">Agenda personal</p><h2 className="text-2xl font-extrabold">Mis citas</h2><p className="text-sm text-base-content/60">Consulta tus próximos controles y el historial de atención.</p></div>
  {proxima?<article className="card overflow-hidden border border-info/30 bg-gradient-to-br from-info/10 to-base-100"><div className="card-body p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><span className="badge badge-info badge-outline mb-2">Tu próxima cita</span><h3 className="text-xl font-extrabold">{proxima.area}</h3><p className="mt-1 flex items-center gap-2 text-sm"><UserRound size={16}/>{proxima.profesional}</p></div><span className={`badge ${badge(proxima.estado)}`}>{etiqueta(proxima.estado)}</span></div><div className="mt-3 grid gap-3 sm:grid-cols-3"><Dato icono={<CalendarDays/>} titulo="Fecha" valor={proxima.fecha}/><Dato icono={<Clock3/>} titulo="Horario" valor={`${proxima.hora_inicio} – ${proxima.hora_fin}`}/><Dato icono={<MapPin/>} titulo="Modalidad" valor={proxima.modalidad?.replaceAll('_',' ')??'Por confirmar'}/></div>{proxima.motivo&&<p className="mt-3"><b>Motivo:</b> {proxima.motivo}</p>}{proxima.observaciones&&<div className="alert mt-3 text-sm">{proxima.observaciones}</div>}</div></article>:<div className="rounded-2xl border border-dashed border-base-300 p-7 text-center"><CalendarDays className="mx-auto text-base-content/35"/><p className="mt-2 font-semibold">No tienes citas próximas programadas.</p></div>}
  {citas.citas_pendientes.length>0&&<article className="card border border-base-300 bg-base-100"><div className="card-body p-5"><h3 className="font-bold">Citas pendientes</h3><div className="grid gap-3 md:grid-cols-2">{citas.citas_pendientes.map(c=><div className="rounded-xl bg-base-200/60 p-3" key={c.id_cita}><div className="flex justify-between gap-2"><b>{c.fecha} · {c.hora_inicio}</b><span className={`badge badge-sm ${badge(c.estado)}`}>{etiqueta(c.estado)}</span></div><p className="mt-1 text-sm">{c.profesional}</p><p className="text-xs text-base-content/55">{c.area}</p></div>)}</div></div></article>}
  <article className="card border border-base-300 bg-base-100"><div className="card-body p-5"><h3 className="flex items-center gap-2 font-bold"><History size={18}/>Historial de citas</h3>{citas.citas_historial.length===0?<p className="text-sm text-base-content/55">Aún no tienes citas en el historial.</p>:<div className="overflow-x-auto"><table className="table table-sm"><thead><tr><th>Fecha</th><th>Profesional</th><th>Motivo</th><th>Estado</th></tr></thead><tbody>{citas.citas_historial.map(c=><tr key={c.id_cita}><td>{c.fecha} · {c.hora_inicio}</td><td><b>{c.profesional}</b><br/><span className="text-xs">{c.area}</span></td><td>{c.motivo??'Sin motivo registrado'}</td><td><span className={`badge badge-sm ${badge(c.estado)}`}>{etiqueta(c.estado)}</span></td></tr>)}</tbody></table></div>}<div className="mt-3 flex flex-wrap gap-2 text-xs"><span className="badge badge-ghost">Total: {citas.resumen.total_citas}</span><span className="badge badge-success badge-outline">Realizadas: {citas.resumen.realizadas}</span><span className="badge badge-error badge-outline">Canceladas: {citas.resumen.canceladas}</span></div></div></article>
 </section>
}
function Dato({icono,titulo,valor}:{icono:React.ReactNode;titulo:string;valor:string}){return <div className="flex gap-2 rounded-xl bg-base-100/70 p-3"><span className="text-info [&>svg]:size-5">{icono}</span><div><p className="text-xs text-base-content/50">{titulo}</p><p className="font-semibold capitalize">{valor}</p></div></div>}
