import axios, { AxiosError } from 'axios';
import { LoaderCircle, X } from 'lucide-react';
import { FormEvent, useEffect, useState } from 'react';

export interface SeguimientoComida {
 estado_cumplimiento:string;porcentaje_consumido:number|null;nivel_agrado:string|null;desea_repetir:boolean|null;nivel_saciedad:string|null;nivel_hambre_posterior:string|null;ansiedad_posterior:boolean|null;presento_molestia:boolean|null;tipo_molestia:string|null;intensidad_molestia:string|null;dificultad_preparacion:string|null;consiguio_ingredientes:boolean|null;motivo_no_cumplimiento:string|null;comida_reemplazo:string|null;motivo_reemplazo:string|null;comentario_paciente:string|null;sugerencia_paciente:string|null;observacion_para_siguiente_plan:string|null;updated_at:string|null
}
interface Props{abierto:boolean;cerrar:()=>void;comidaId:number;nombre:string;seguimiento:SeguimientoComida;onSuccess:()=>void}
const opciones=(items:[string,string][])=>items.map(([v,l])=><option key={v} value={v}>{l}</option>);
const errorDe=(e:unknown)=>{const d=(e as AxiosError<{message?:string;errors?:Record<string,string[]>}>).response?.data;return Object.values(d?.errors??{})[0]?.[0]??d?.message??'No se pudo guardar el seguimiento.'};

export default function ModalSeguimientoComida({abierto,cerrar,comidaId,nombre,seguimiento,onSuccess}:Props){
 const [form,setForm]=useState<SeguimientoComida>(seguimiento),[guardando,setGuardando]=useState(false),[error,setError]=useState('');
 useEffect(()=>{setForm(seguimiento);setError('')},[seguimiento,abierto]); if(!abierto)return null;
 const set=<K extends keyof SeguimientoComida>(k:K,v:SeguimientoComida[K])=>setForm(f=>({...f,[k]:v}));
 const guardar=async(e:FormEvent)=>{e.preventDefault();setGuardando(true);setError('');try{await axios.post(`/paciente/comidas-plan/${comidaId}/seguimiento`,{...form,ansiedad_posterior:!!form.ansiedad_posterior,presento_molestia:!!form.presento_molestia},{headers:{Accept:'application/json'}});cerrar();onSuccess()}catch(x){setError(errorDe(x))}finally{setGuardando(false)}};
 const noCumple=['no_realizada','reemplazada'].includes(form.estado_cumplimiento);
 return <dialog className="modal modal-open"><div className="modal-box max-w-3xl"><div className="flex justify-between gap-3"><div><h3 className="text-lg font-bold">Registrar seguimiento</h3><p className="text-sm text-base-content/60">{nombre}</p></div><button className="btn btn-circle btn-ghost btn-sm" onClick={cerrar}><X size={17}/></button></div><form className="mt-5 space-y-5" onSubmit={guardar}>
  <Campo label="¿Cómo te fue con esta comida?"><select className="select select-bordered w-full" value={form.estado_cumplimiento} onChange={e=>set('estado_cumplimiento',e.target.value)}>{opciones([['completada','Completada'],['parcial','Parcial'],['no_realizada','No la realicé'],['reemplazada','La reemplacé']])}</select></Campo>
  {['parcial','reemplazada'].includes(form.estado_cumplimiento)&&<Campo label="Porcentaje consumido"><input className="range range-primary" type="range" min="0" max="100" value={form.porcentaje_consumido??50} onChange={e=>set('porcentaje_consumido',Number(e.target.value))}/><p className="text-center font-bold">{form.porcentaje_consumido??50}%</p></Campo>}
  <div className="grid gap-4 sm:grid-cols-2"><Select label="¿Te gustó?" value={form.nivel_agrado} onChange={v=>set('nivel_agrado',v)} items={[['','Seleccionar'],['me_gusto','Me gustó'],['neutral','Normal'],['no_me_gusto','No me gustó']]}/><SiNo label="¿La repetirías?" value={form.desea_repetir} onChange={v=>set('desea_repetir',v)}/><Select label="Saciedad después de comer" value={form.nivel_saciedad} onChange={v=>set('nivel_saciedad',v)} items={[['','Seleccionar'],['baja','Baja'],['media','Media'],['alta','Alta']]}/><Select label="Hambre después" value={form.nivel_hambre_posterior} onChange={v=>set('nivel_hambre_posterior',v)} items={[['','Seleccionar'],['baja','Baja'],['media','Media'],['alta','Alta']]}/><SiNo label="¿Sentiste ansiedad después?" value={form.ansiedad_posterior} onChange={v=>set('ansiedad_posterior',v)}/><SiNo label="¿Presentaste alguna molestia?" value={form.presento_molestia} onChange={v=>set('presento_molestia',v)}/></div>
  {form.presento_molestia&&<div className="grid gap-4 sm:grid-cols-2"><Select label="Tipo de molestia" value={form.tipo_molestia} onChange={v=>set('tipo_molestia',v)} items={[['','Seleccionar'],['hinchazon','Hinchazón'],['nausea','Náusea'],['dolor_estomacal','Dolor estomacal'],['acidez','Acidez'],['diarrea','Diarrea'],['estreñimiento','Estreñimiento'],['hambre','Hambre'],['ansiedad','Ansiedad'],['otro','Otro']]}/><Select label="Intensidad" value={form.intensidad_molestia} onChange={v=>set('intensidad_molestia',v)} items={[['','Seleccionar'],['leve','Leve'],['moderada','Moderada'],['severa','Severa']]}/></div>}
  <div className="grid gap-4 sm:grid-cols-2"><Select label="Dificultad de preparación" value={form.dificultad_preparacion} onChange={v=>set('dificultad_preparacion',v)} items={[['','Seleccionar'],['facil','Fácil'],['media','Media'],['dificil','Difícil']]}/><SiNo label="¿Conseguiste los ingredientes?" value={form.consiguio_ingredientes} onChange={v=>set('consiguio_ingredientes',v)}/></div>
  {noCumple&&<Select label="Motivo de no cumplimiento" value={form.motivo_no_cumplimiento} onChange={v=>set('motivo_no_cumplimiento',v)} items={[['','Seleccionar'],['falta_tiempo','Falta de tiempo'],['no_tenia_ingredientes','No tenía ingredientes'],['no_me_gusto','No me gustó'],['me_cayo_mal','Me cayó mal'],['no_tenia_hambre','No tenía hambre'],['comi_fuera','Comí fuera'],['olvido','Lo olvidé'],['otro','Otro']]}/>} 
  {form.estado_cumplimiento==='reemplazada'&&<div className="grid gap-4 sm:grid-cols-2"><Texto label="¿Qué comiste en su lugar?" value={form.comida_reemplazo} onChange={v=>set('comida_reemplazo',v)} max={500}/><Texto label="¿Por qué la reemplazaste?" value={form.motivo_reemplazo} onChange={v=>set('motivo_reemplazo',v)} max={500}/></div>}
  <Texto label="Comentario para tu nutricionista" value={form.comentario_paciente} onChange={v=>set('comentario_paciente',v)} max={1000}/><Texto label="Sugerencia para el siguiente plan" value={form.sugerencia_paciente} onChange={v=>set('sugerencia_paciente',v)} max={1000}/>
  {error&&<div className="alert alert-error py-2 text-sm">{error}</div>}<div className="modal-action"><button type="button" className="btn btn-ghost" onClick={cerrar}>Cancelar</button><button className="btn btn-primary" disabled={guardando}>{guardando&&<LoaderCircle className="animate-spin" size={16}/>}Guardar seguimiento</button></div>
 </form></div><button className="modal-backdrop" onClick={cerrar}>Cerrar</button></dialog>
}
function Campo({label,children}:{label:string;children:React.ReactNode}){return <label className="form-control"><span className="label-text mb-1 font-semibold">{label}</span>{children}</label>}
function Select({label,value,onChange,items}:{label:string;value:string|null;onChange:(v:string|null)=>void;items:[string,string][]}){return <Campo label={label}><select className="select select-bordered w-full" value={value??''} onChange={e=>onChange(e.target.value||null)}>{opciones(items)}</select></Campo>}
function SiNo({label,value,onChange}:{label:string;value:boolean|null;onChange:(v:boolean|null)=>void}){return <Campo label={label}><select className="select select-bordered w-full" value={value===null?'':value?'1':'0'} onChange={e=>onChange(e.target.value===''?null:e.target.value==='1')}><option value="">Seleccionar</option><option value="1">Sí</option><option value="0">No</option></select></Campo>}
function Texto({label,value,onChange,max}:{label:string;value:string|null;onChange:(v:string)=>void;max:number}){return <Campo label={label}><textarea className="textarea textarea-bordered min-h-24" maxLength={max} value={value??''} onChange={e=>onChange(e.target.value)}/></Campo>}
