import { Activity, Ruler, Scale, Target, TrendingDown, TrendingUp } from 'lucide-react';

interface Progreso {evaluacion:{fecha_ultima_evaluacion:string|null;peso_inicial:number|null;peso_actual:number|null;cambio_peso:number|null;imc_actual:number|null;clasificacion_imc:string|null;cambio_imc:number|null;cintura_inicial:number|null;cintura_actual:number|null;cambio_cintura:number|null};objetivo:{objetivo_principal:string|null;calorias_objetivo:number|null;proteinas_objetivo:number|null;carbohidratos_objetivo:number|null;grasas_objetivo:number|null;fibra_objetivo:number|null};adherencia:{comidas_totales:number;completadas:number;parciales:number;no_realizadas:number;reemplazadas:number;pendientes:number;porcentaje_adherencia:number};mensaje:string}
export type { Progreso };
const n=(v:number|null,unidad='')=>v===null?'Sin registro':`${v.toLocaleString('es-BO',{maximumFractionDigits:2})}${unidad}`;
const cambio=(v:number|null)=>v===null?'Sin historial':v===0?'Se mantiene':`${v>0?'+':''}${n(v)}`;

export default function ProgresoPacienteCard({progreso}:{progreso:Progreso|null}){
 if(!progreso)return null;const e=progreso.evaluacion,a=progreso.adherencia,o=progreso.objetivo;
 const indicador=(valor:number|null)=>valor===null?null:valor<0?<TrendingDown size={15}/>:valor>0?<TrendingUp size={15}/>:null;
 return <section className="space-y-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-primary">Seguimiento personal</p><h2 className="text-2xl font-extrabold">Mi progreso</h2><p className="mt-1 text-sm text-base-content/60">{progreso.mensaje}</p></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">
  <article className="card border border-base-300 bg-base-100"><div className="card-body p-4"><Scale className="text-primary"/><h3 className="font-bold">Peso</h3><p className="text-2xl font-extrabold">{n(e.peso_actual,' kg')}</p><p className="text-xs text-base-content/55">Inicial: {n(e.peso_inicial,' kg')}</p><span className="badge badge-outline gap-1">{indicador(e.cambio_peso)}{cambio(e.cambio_peso)} kg</span></div></article>
  <article className="card border border-base-300 bg-base-100"><div className="card-body p-4"><Activity className="text-secondary"/><h3 className="font-bold">IMC actual</h3><p className="text-2xl font-extrabold">{n(e.imc_actual)}</p><span className="badge badge-secondary badge-outline">{e.clasificacion_imc??'Sin clasificación'}</span><p className="text-xs text-base-content/55">Cambio: {cambio(e.cambio_imc)}</p></div></article>
  <article className="card border border-base-300 bg-base-100"><div className="card-body p-4"><Ruler className="text-accent"/><h3 className="font-bold">Cintura</h3><p className="text-2xl font-extrabold">{n(e.cintura_actual,' cm')}</p><p className="text-xs text-base-content/55">Inicial: {n(e.cintura_inicial,' cm')}</p><span className="badge badge-outline gap-1">{indicador(e.cambio_cintura)}{cambio(e.cambio_cintura)} cm</span></div></article>
  <article className="card border border-base-300 bg-base-100"><div className="card-body p-4"><Activity className="text-success"/><h3 className="font-bold">Adherencia semanal</h3><p className="text-2xl font-extrabold text-success">{n(a.porcentaje_adherencia,'%')}</p><progress className="progress progress-success" value={a.porcentaje_adherencia} max="100"/><p className="text-xs text-base-content/55">{a.completadas} completas · {a.parciales} parciales · {a.no_realizadas} no realizadas · {a.pendientes} pendientes</p></div></article>
  <article className="card border border-base-300 bg-base-100"><div className="card-body p-4"><Target className="text-warning"/><h3 className="font-bold">Objetivo actual</h3><p className="font-semibold capitalize">{o.objetivo_principal?.replaceAll('_',' ')??'Por definir'}</p><p className="text-sm">{n(o.calorias_objetivo,' kcal/día')}</p><p className="text-xs text-base-content/55">P {n(o.proteinas_objetivo,' g')} · C {n(o.carbohidratos_objetivo,' g')} · G {n(o.grasas_objetivo,' g')} · Fibra {n(o.fibra_objetivo,' g')}</p></div></article>
 </div>{e.fecha_ultima_evaluacion&&<p className="text-xs text-base-content/45">Último registro nutricional: {e.fecha_ultima_evaluacion}</p>}</section>
}
