import { router } from '@inertiajs/react';
import { Check, MessageSquareText } from 'lucide-react';
import { useState } from 'react';

export interface RetroalimentacionPacienteItem {id_retroalimentacion_paciente:number;tipo_retroalimentacion:string;prioridad:string;mensaje:string;leido_por_paciente:boolean;fecha_lectura_paciente:string|null;created_at:string|null;profesional:string|null;contexto:{plan:string|null;comida:string|null;sintoma_fecha:string|null}}
export interface RetroalimentacionesPaciente {items:RetroalimentacionPacienteItem[];total_no_leidas:number}
export default function RetroalimentacionesNutricionistaCard({retroalimentaciones}:{retroalimentaciones:RetroalimentacionesPaciente|null}){
 const [procesando,setProcesando]=useState<number|null>(null);const items=retroalimentaciones?.items??[];
 const leer=async(id:number)=>{setProcesando(id);try{const token=document.querySelector<HTMLMetaElement>('meta[name="csrf-token"]')?.content??'';const r=await fetch(`/paciente/retroalimentaciones/${id}/marcar-leida`,{method:'POST',headers:{'Accept':'application/json','X-CSRF-TOKEN':token}});if(r.ok)router.reload({only:['retroalimentaciones']});}finally{setProcesando(null)}};
 return <section className="card border border-base-300 bg-base-100 shadow-sm"><div className="card-body p-5"><div className="flex flex-wrap items-center justify-between gap-2"><div className="flex items-center gap-2"><MessageSquareText className="text-primary"/><div><h2 className="text-lg font-bold">Mensajes de tu nutricionista</h2><p className="text-sm text-base-content/60">Orientaciones basadas en tu seguimiento.</p></div></div>{(retroalimentaciones?.total_no_leidas??0)>0&&<span className="badge badge-primary">{retroalimentaciones?.total_no_leidas} sin leer</span>}</div>{items.length===0?<p className="mt-4 rounded-xl bg-base-200 p-4 text-sm text-base-content/60">Tu nutricionista aún no te ha enviado retroalimentaciones.</p>:<div className="mt-4 space-y-3">{items.map(x=><article className={`rounded-2xl border p-4 ${x.prioridad==='alta'?'border-error/40 bg-error/5':x.leido_por_paciente?'border-base-300':'border-primary/35 bg-primary/5'}`} key={x.id_retroalimentacion_paciente}><div className="flex flex-wrap justify-between gap-2"><div className="flex flex-wrap gap-2"><span className="badge badge-outline capitalize">{x.tipo_retroalimentacion.replaceAll('_',' ')}</span><span className={`badge ${x.prioridad==='alta'?'badge-error':x.prioridad==='baja'?'badge-ghost':'badge-warning'}`}>{x.prioridad}</span><span className={`badge ${x.leido_por_paciente?'badge-success':'badge-primary'}`}>{x.leido_por_paciente?'Leído':'Nuevo'}</span></div><time className="text-xs text-base-content/45">{x.created_at?new Date(x.created_at).toLocaleDateString('es-BO'):'Sin fecha'}</time></div><p className="mt-3 text-sm leading-relaxed">{x.mensaje}</p><p className="mt-3 text-xs text-base-content/50">{x.profesional??'Profesional de nutrición'}{x.contexto.comida?` · ${x.contexto.comida}`:x.contexto.plan?` · ${x.contexto.plan}`:''}</p>{!x.leido_por_paciente&&<button className="btn btn-primary btn-outline btn-sm mt-3" disabled={procesando===x.id_retroalimentacion_paciente} onClick={()=>leer(x.id_retroalimentacion_paciente)}><Check size={15}/>{procesando===x.id_retroalimentacion_paciente?'Procesando...':'Marcar como leído'}</button>}</article>)}</div>}</div></section>
}
