import { router } from '@inertiajs/react';
import { Activity, AlertCircle, CalendarDays, Save } from 'lucide-react';
import { useState } from 'react';

interface Registro {fecha_registro:string;nivel_energia:string|null;hambre_durante_dia:string|null;ansiedad_por_comida:string|null;antojos_dulces:string|null;hambre_nocturna:boolean;hinchazon_abdominal:string|null;fatiga_post_comida:string|null;mareos_o_debilidad:boolean;acne:string|null;dolor_menstrual:string|null;irregularidad_menstrual:boolean|null;cambios_estado_animo:string|null;calidad_sueno:string|null;horas_sueno:number|string|null;actividad_fisica:string|null;minutos_actividad:number|null;consumo_agua_litros:number|string|null;observaciones:string|null}
interface Indicadores {hambre_nocturna_frecuente:boolean;ansiedad_comida_frecuente:boolean;antojos_dulces_frecuentes:boolean;hinchazon_frecuente:boolean;baja_energia_frecuente:boolean;sueno_deficiente_frecuente:boolean;actividad_fisica_baja:boolean;recomendaciones_para_nutricionista:string[]}
export interface SeguimientoSintomas {registro_hoy:Registro|null;ultimos_registros:Registro[];indicadores:Indicadores}
type Form=Omit<Registro,'fecha_registro'>;
const vacio:Form={nivel_energia:null,hambre_durante_dia:null,ansiedad_por_comida:null,antojos_dulces:null,hambre_nocturna:false,hinchazon_abdominal:null,fatiga_post_comida:null,mareos_o_debilidad:false,acne:null,dolor_menstrual:null,irregularidad_menstrual:null,cambios_estado_animo:null,calidad_sueno:null,horas_sueno:null,actividad_fisica:null,minutos_actividad:null,consumo_agua_litros:null,observaciones:null};
const titulo=(v:string|null)=>v?.replaceAll('_',' ')??'Sin registro';

export default function SeguimientoSintomasCard({seguimiento}:{seguimiento:SeguimientoSintomas|null}){
 if(!seguimiento)return null;
 const [form,setForm]=useState<Form>(seguimiento.registro_hoy?Object.fromEntries(Object.keys(vacio).map(k=>[k,seguimiento.registro_hoy?.[k as keyof Registro]??vacio[k as keyof Form]])) as Form:vacio);
 const [guardando,setGuardando]=useState(false);const [error,setError]=useState<string|null>(null);
 const set=<K extends keyof Form>(k:K,v:Form[K])=>setForm(p=>({...p,[k]:v}));
 const guardar=async()=>{setGuardando(true);setError(null);try{const token=document.querySelector<HTMLMetaElement>('meta[name="csrf-token"]')?.content??'';const r=await fetch('/paciente/seguimiento-sintomas',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':token},body:JSON.stringify(form)});if(!r.ok){const data=await r.json();throw new Error(r.status===422?'Revisa los datos ingresados.':data.message??'No se pudo guardar el seguimiento.')}router.reload({only:['seguimientoSintomas']});}catch(e){setError(e instanceof Error?e.message:'No se pudo guardar el seguimiento.')}finally{setGuardando(false)}};
 const alertas=[seguimiento.indicadores.hambre_nocturna_frecuente&&'Has reportado hambre nocturna varias veces esta semana.',seguimiento.indicadores.antojos_dulces_frecuentes&&'Se registraron antojos dulces frecuentes.',seguimiento.indicadores.sueno_deficiente_frecuente&&'Tu sueño puede estar afectando tu energía.',seguimiento.indicadores.ansiedad_comida_frecuente&&'Tus registros de ansiedad ayudarán a ajustar mejor tu orientación.',seguimiento.indicadores.hinchazon_frecuente&&'Has reportado hinchazón varias veces; registra qué alimentos consumiste.'].filter(Boolean) as string[];
 return <section className="space-y-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-primary">Registro personal</p><h2 className="text-2xl font-extrabold">Seguimiento de síntomas</h2><p className="text-sm text-base-content/60">Tus registros ayudarán a tu nutricionista a ajustar el siguiente plan.</p></div>
  {alertas.length>0&&<div className="alert alert-info items-start"><AlertCircle/><ul className="space-y-1 text-sm">{alertas.map(x=><li key={x}>{x}</li>)}</ul></div>}
  <div className="card border border-base-300 bg-base-100"><div className="card-body p-5"><h3 className="card-title">¿Cómo te sientes hoy?</h3><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
   <Select label="Energía" value={form.nivel_energia} options={['baja','media','alta']} onChange={v=>set('nivel_energia',v)}/><Select label="Hambre durante el día" value={form.hambre_durante_dia} options={['baja','media','alta']} onChange={v=>set('hambre_durante_dia',v)}/><Select label="Ansiedad por comida" value={form.ansiedad_por_comida} options={['ninguna','leve','moderada','alta']} onChange={v=>set('ansiedad_por_comida',v)}/><Select label="Antojos dulces" value={form.antojos_dulces} options={['ninguno','leve','moderado','alto']} onChange={v=>set('antojos_dulces',v)}/><Select label="Hinchazón abdominal" value={form.hinchazon_abdominal} options={['ninguna','leve','moderada','severa']} onChange={v=>set('hinchazon_abdominal',v)}/><Select label="Fatiga después de comer" value={form.fatiga_post_comida} options={['ninguna','leve','moderada','severa']} onChange={v=>set('fatiga_post_comida',v)}/><Select label="Acné" value={form.acne} options={['ninguno','leve','moderado','severo']} onChange={v=>set('acne',v)}/><Select label="Dolor menstrual" value={form.dolor_menstrual} options={['ninguno','leve','moderado','severo']} onChange={v=>set('dolor_menstrual',v)}/><Select label="Estado de ánimo" value={form.cambios_estado_animo} options={['estable','irritable','bajo','ansioso']} onChange={v=>set('cambios_estado_animo',v)}/><Select label="Calidad de sueño" value={form.calidad_sueno} options={['mala','regular','buena']} onChange={v=>set('calidad_sueno',v)}/><Select label="Actividad física" value={form.actividad_fisica} options={['ninguna','ligera','moderada','intensa']} onChange={v=>set('actividad_fisica',v)}/><Numero label="Horas de sueño" value={form.horas_sueno} max={24} step="0.5" onChange={v=>set('horas_sueno',v)}/><Numero label="Minutos de actividad" value={form.minutos_actividad} max={600} onChange={v=>set('minutos_actividad',v)}/><Numero label="Agua tomada (litros)" value={form.consumo_agua_litros} max={10} step="0.1" onChange={v=>set('consumo_agua_litros',v)}/>
  </div><div className="mt-4 grid gap-3 sm:grid-cols-3"><Check label="Hambre nocturna" checked={form.hambre_nocturna} onChange={v=>set('hambre_nocturna',v)}/><Check label="Mareos o debilidad" checked={form.mareos_o_debilidad} onChange={v=>set('mareos_o_debilidad',v)}/><label className="label cursor-pointer justify-start gap-3"><input type="checkbox" className="checkbox checkbox-primary" checked={form.irregularidad_menstrual===true} onChange={e=>set('irregularidad_menstrual',e.target.checked)}/><span>Irregularidad menstrual</span></label></div><label className="form-control mt-4"><span className="label-text mb-1 font-semibold">Observaciones</span><textarea className="textarea textarea-bordered" maxLength={1000} value={form.observaciones??''} onChange={e=>set('observaciones',e.target.value||null)} placeholder="Cuéntanos algo importante sobre cómo te sentiste..."/></label>{error&&<div className="alert alert-error mt-4 text-sm">{error}</div>}<button className="btn btn-primary mt-4" disabled={guardando} onClick={guardar}>{guardando?<span className="loading loading-spinner loading-sm"/>:<Save size={17}/>} {guardando?'Guardando...':'Guardar seguimiento'}</button></div></div>
  <div className="card border border-base-300 bg-base-100"><div className="card-body p-5"><h3 className="flex items-center gap-2 font-bold"><CalendarDays size={18}/>Últimos registros</h3>{seguimiento.ultimos_registros.length===0?<p className="text-sm text-base-content/55">Aún no tienes registros de síntomas.</p>:<div className="overflow-x-auto"><table className="table table-sm"><thead><tr><th>Fecha</th><th>Energía</th><th>Ansiedad</th><th>Hambre nocturna</th><th>Hinchazón</th><th>Sueño</th><th>Actividad</th></tr></thead><tbody>{seguimiento.ultimos_registros.map(r=><tr key={r.fecha_registro}><td>{r.fecha_registro}</td><td className="capitalize">{titulo(r.nivel_energia)}</td><td className="capitalize">{titulo(r.ansiedad_por_comida)}</td><td>{r.hambre_nocturna?'Sí':'No'}</td><td className="capitalize">{titulo(r.hinchazon_abdominal)}</td><td className="capitalize">{titulo(r.calidad_sueno)}</td><td className="capitalize">{titulo(r.actividad_fisica)}</td></tr>)}</tbody></table></div>}</div></div>
 </section>
}
function Select({label,value,options,onChange}:{label:string;value:string|null;options:string[];onChange:(v:string|null)=>void}){return <label className="form-control"><span className="label-text mb-1 font-semibold">{label}</span><select className="select select-bordered" value={value??''} onChange={e=>onChange(e.target.value||null)}><option value="">Seleccionar</option>{options.map(x=><option value={x} key={x} className="capitalize">{titulo(x)}</option>)}</select></label>}
function Numero({label,value,max,step='1',onChange}:{label:string;value:number|string|null;max:number;step?:string;onChange:(v:number|null)=>void}){return <label className="form-control"><span className="label-text mb-1 font-semibold">{label}</span><input type="number" className="input input-bordered" min="0" max={max} step={step} value={value??''} onChange={e=>onChange(e.target.value===''?null:Number(e.target.value))}/></label>}
function Check({label,checked,onChange}:{label:string;checked:boolean;onChange:(v:boolean)=>void}){return <label className="label cursor-pointer justify-start gap-3"><input type="checkbox" className="checkbox checkbox-primary" checked={checked} onChange={e=>onChange(e.target.checked)}/><span>{label}</span></label>}
