import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, Link } from '@inertiajs/react';
import { AlertTriangle, CalendarDays, CheckCircle2, ClipboardCheck, Search, TrendingUp, Utensils, Users } from 'lucide-react';
import { useState } from 'react';
import clsx from 'clsx';

interface Estadisticas { total:number; registradas:number; completadas:number; parciales:number; reemplazadas:number; no_realizadas:number; pendientes:number; porcentaje:number }
interface PacienteProgreso { paciente:{id_paciente:number;nombre:string;ci:string|null};plan:{id_plan_alimentario:number;nombre:string;estado:string;fecha_inicio:string|null;fecha_fin:string|null};estado_seguimiento:string;adherencia_semanal:number;semana:Estadisticas;hoy:Estadisticas&{tiene_dia_planificado:boolean;nombre_dia:string|null;fecha:string|null};dias_transcurridos:number;dias_cumplidos:number;total_dias:number;ultima_actualizacion:string|null }
interface Props { resumen:{pacientes_con_plan:number;al_dia:number;en_progreso:number;requieren_atencion:number;adherencia_promedio:number};pacientes:PacienteProgreso[] }
const texto=(v:string)=>v.replaceAll('_',' '); const n=(v:number)=>v.toLocaleString('es-BO',{maximumFractionDigits:1});
const estados:Record<string,{label:string;clase:string}>={al_dia:{label:'Al día',clase:'bg-brand-green/15 text-brand-green-dark dark:text-brand-green'},en_progreso:{label:'En progreso',clase:'bg-info/10 text-info'},requiere_atencion:{label:'Requiere atención',clase:'bg-brand-orange/15 text-brand-orange'},sin_registros:{label:'Sin registros',clase:'bg-black/[0.06] text-ink-muted dark:bg-white/[0.07] dark:text-ink-muted-dark'}};

export default function Index({resumen,pacientes}:Props){
 const [busqueda,setBusqueda]=useState(''),[filtro,setFiltro]=useState('');
 const visibles=pacientes.filter(p=>(!filtro||p.estado_seguimiento===filtro)&&(`${p.paciente.nombre} ${p.paciente.ci??''}`.toLowerCase().includes(busqueda.toLowerCase())));
 return <AuthenticatedLayout title="Progreso de pacientes"><Head title="Progreso de pacientes"/><main className="space-y-5">
  <section className="card-elevated overflow-hidden"><div className="border-l-4 border-brand-green px-6 py-5"><p className="text-[10px] font-bold uppercase tracking-wider text-brand-green-dark dark:text-brand-green">Seguimiento nutricional</p><h1 className="mt-1 text-[20px] font-bold text-ink dark:text-ink-dark">Cumplimiento diario y semanal</h1><p className="mt-1 text-[11.5px] text-ink-muted dark:text-ink-muted-dark">Identifica quién está cumpliendo su plan y quién necesita acompañamiento.</p></div></section>
  <section className="grid grid-cols-2 gap-3 lg:grid-cols-5"><Metrica icon={Users} label="Con plan vigente" valor={resumen.pacientes_con_plan}/><Metrica icon={CheckCircle2} label="Al día" valor={resumen.al_dia} verde/><Metrica icon={TrendingUp} label="En progreso" valor={resumen.en_progreso}/><Metrica icon={AlertTriangle} label="Por revisar" valor={resumen.requieren_atencion} alerta/><Metrica icon={ClipboardCheck} label="Adherencia promedio" valor={`${n(resumen.adherencia_promedio)}%`} verde/></section>
  <section className="card-elevated p-5 space-y-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-[15px] font-bold text-ink dark:text-ink-dark">Pacientes y cumplimiento</h2><p className="text-[10.5px] text-ink-muted">{visibles.length} paciente(s) mostrados</p></div><div className="flex flex-wrap gap-2"><label className="relative"><Search size={13} className="absolute left-3 top-2.5 text-ink-muted"/><input value={busqueda} onChange={e=>setBusqueda(e.target.value)} placeholder="Buscar paciente..." className="rounded-lg border border-surface-border bg-transparent py-2 pl-8 pr-3 text-[11px] text-ink outline-none focus:border-brand-green/50 dark:border-surface-border-dark dark:text-ink-dark"/></label><select value={filtro} onChange={e=>setFiltro(e.target.value)} className="rounded-lg border border-surface-border bg-surface-card px-3 py-2 text-[11px] text-ink dark:border-surface-border-dark dark:bg-surface-card-dark dark:text-ink-dark"><option value="">Todos</option>{Object.entries(estados).map(([v,e])=><option key={v} value={v}>{e.label}</option>)}</select></div></div>
   {visibles.length===0?<div className="rounded-xl border border-dashed border-surface-border py-10 text-center text-[12px] text-ink-muted dark:border-surface-border-dark">No hay pacientes que coincidan con el filtro.</div>:<div className="grid gap-3 xl:grid-cols-2">{visibles.map(p=><PacienteCard key={p.paciente.id_paciente} dato={p}/>)}</div>}
  </section>
 </main></AuthenticatedLayout>
}
function Metrica({icon:Icon,label,valor,verde=false,alerta=false}:{icon:typeof Users;label:string;valor:number|string;verde?:boolean;alerta?:boolean}){return <div className="card-elevated p-4"><div className={clsx('mb-3 flex h-8 w-8 items-center justify-center rounded-lg',alerta?'bg-brand-orange/12 text-brand-orange':verde?'bg-brand-green/12 text-brand-green-dark dark:text-brand-green':'bg-info/10 text-info')}><Icon size={15}/></div><b className="text-[19px] text-ink dark:text-ink-dark">{valor}</b><p className="text-[9.5px] uppercase tracking-wide text-ink-muted">{label}</p></div>}
function PacienteCard({dato:p}:{dato:PacienteProgreso}){const e=estados[p.estado_seguimiento]??estados.sin_registros;return <article className="rounded-2xl border border-surface-border p-4 dark:border-surface-border-dark"><div className="flex items-start justify-between gap-3"><div><h3 className="text-[13px] font-bold text-ink dark:text-ink-dark">{p.paciente.nombre}</h3><p className="text-[9.5px] text-ink-muted">CI {p.paciente.ci||'sin registro'} · {p.plan.fecha_inicio||'—'} al {p.plan.fecha_fin||'—'}</p></div><span className={clsx('rounded-full px-2.5 py-1 text-[9px] font-bold capitalize',e.clase)}>{e.label}</span></div>
 <div className="mt-4 grid grid-cols-2 gap-3"><Progreso titulo={p.hoy.tiene_dia_planificado?`Hoy · ${p.hoy.nombre_dia}`:'Hoy'} valor={p.hoy.porcentaje} detalle={p.hoy.tiene_dia_planificado?`${p.hoy.completadas}/${p.hoy.total} comidas completadas`:'Sin día planificado para hoy'}/><Progreso titulo="Semana completa" valor={p.adherencia_semanal} detalle={`${p.semana.completadas}/${p.semana.total} comidas completadas`}/></div>
 <div className="mt-3 grid grid-cols-3 gap-2 rounded-xl bg-black/[0.02] p-3 text-center dark:bg-white/[0.025]"><Dato valor={`${p.dias_cumplidos}/${p.dias_transcurridos}`} label="días cumplidos"/><Dato valor={p.semana.parciales+p.semana.reemplazadas} label="parciales/cambios"/><Dato valor={p.semana.no_realizadas} label="no realizadas"/></div>
 <div className="mt-3 flex items-center justify-between gap-3"><p className="text-[9px] text-ink-muted">{p.ultima_actualizacion?`Último registro: ${new Date(p.ultima_actualizacion).toLocaleString('es-BO',{dateStyle:'short',timeStyle:'short'})}`:'La paciente todavía no registró comidas.'}</p><Link href={route('nutricionista.pacientes.perfil-nutricional',p.paciente.id_paciente)} className="shrink-0 text-[10px] font-bold text-brand-green-dark hover:underline dark:text-brand-green">Ver seguimiento →</Link></div></article>}
function Progreso({titulo,valor,detalle}:{titulo:string;valor:number;detalle:string}){return <div><div className="flex justify-between gap-2"><p className="text-[9.5px] font-bold text-ink dark:text-ink-dark">{titulo}</p><b className="text-[10px] text-brand-green-dark dark:text-brand-green">{n(valor)}%</b></div><div className="mt-1.5 h-2 overflow-hidden rounded-full bg-black/[0.07] dark:bg-white/[0.08]"><div className={clsx('h-full rounded-full',valor<50?'bg-brand-orange':'bg-brand-green')} style={{width:`${Math.min(Math.max(valor,0),100)}%`}}/></div><p className="mt-1 text-[9px] text-ink-muted">{detalle}</p></div>}
function Dato({valor,label}:{valor:number|string;label:string}){return <div><b className="text-[12px] text-ink dark:text-ink-dark">{valor}</b><p className="text-[8.5px] text-ink-muted">{label}</p></div>}
