import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, Link, usePage } from '@inertiajs/react';
import { Activity, AlertTriangle, CalendarDays, CheckCircle2, ChevronRight, ClipboardCheck, DatabaseBackup, HeartPulse, Salad, ShieldCheck, Stethoscope, UserCog, Users } from 'lucide-react';
import clsx from 'clsx';
import RoleWelcomePreloader from '@/Components/ui/RoleWelcomePreloader';

type N = Record<string, number>;
type Alerta = { titulo: string; mensaje: string; severidad: string; categoria: string };
type Diagnosticos = { pmos_confirmado:number; pmos_no_confirmado:number; pmos_en_estudio:number; ri_confirmada:number; ri_no_confirmada:number; ri_no_evaluada:number; pmos_fenotipos:N; ri_grados:N };
type Metricas = { resumen:N; diagnosticos:Diagnosticos; planes:N; recomendaciones_expertas:N; seguimiento:N; citas:N; actividad:N; alertas:N; alertas_admin:Alerta[]; prediccion_adherencia:N };
const VACIO: Metricas = { resumen:{}, diagnosticos:{pmos_confirmado:0,pmos_no_confirmado:0,pmos_en_estudio:0,ri_confirmada:0,ri_no_confirmada:0,ri_no_evaluada:0,pmos_fenotipos:{},ri_grados:{}}, planes:{}, recomendaciones_expertas:{}, seguimiento:{}, citas:{}, actividad:{}, alertas:{}, alertas_admin:[], prediccion_adherencia:{} };

export default function Dashboard({ metricasGenerales }: { metricasGenerales?: Metricas }) {
    const m = metricasGenerales ?? VACIO;
    const pagina = usePage().props as { auth?: { user?: { id?: number; name?: string } | null } };
    const nombre = pagina.auth?.user?.name?.trim().replace(/^(lic\.?|dra?\.?|nut\.?|ing\.?)\s+/i, '').split(/\s+/)[0] || 'Administrador';
    return <AuthenticatedLayout header={<h2>Administración</h2>}><Head title="Administración"/><RoleWelcomePreloader role="administrador" userName={pagina.auth?.user?.name} userId={pagina.auth?.user?.id}/><main className="mx-auto max-w-7xl space-y-5">
        <header className="relative overflow-hidden rounded-2xl border border-surface-border bg-white p-6 shadow-[0_8px_30px_rgba(16,24,20,.04)] dark:border-surface-border-dark dark:bg-[#1c2027] dark:shadow-none"><div className="absolute inset-y-0 left-0 w-1 bg-category-dairy"/><div className="flex flex-wrap items-center justify-between gap-5"><div className="flex items-center gap-4"><div className="hidden h-12 w-12 items-center justify-center rounded-2xl bg-category-dairy/10 text-category-dairy sm:flex"><ShieldCheck size={23}/></div><div><div className="flex items-center gap-2"><span className="h-1.5 w-1.5 rounded-full bg-category-dairy"/><p className="text-[9.5px] font-bold uppercase tracking-[.18em] text-category-dairy">Supervisión del sistema</p></div><h1 className="mt-1.5 text-2xl font-bold tracking-tight">Hola, {nombre}</h1><p className="mt-1 text-[12px] text-ink-muted">Estado general, alertas operativas y accesos administrativos.</p></div></div><div className="flex flex-wrap gap-2"><a href={route('admin.base-datos.respaldo')} className="inline-flex items-center gap-2 rounded-xl border border-category-dairy/25 px-4 py-2.5 text-[11px] font-bold text-category-dairy"><DatabaseBackup size={15}/> Descargar respaldo</a><Link href={route('admin.users.create')} className="inline-flex items-center gap-2 rounded-xl bg-category-dairy px-4 py-2.5 text-[11px] font-bold text-white"><UserCog size={15}/> Nuevo usuario</Link></div></div></header>

        <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metrica icon={Users} titulo="Usuarios registrados" valor={m.resumen.total_usuarios ?? 0} detalle={`${m.resumen.total_nutricionistas ?? 0} nutricionistas · ${m.resumen.total_endocrinologos ?? 0} endocrinólogos`} color="purple"/><Metrica icon={HeartPulse} titulo="Pacientes" valor={m.resumen.total_pacientes ?? 0} detalle={`${m.resumen.pacientes_activos ?? 0} activos · ${m.resumen.pacientes_inactivos ?? 0} inactivos`} color="green"/><Metrica icon={Salad} titulo="Planes activos" valor={m.planes.activos ?? 0} detalle={`${m.planes.en_revision ?? 0} en revisión · ${m.planes.sugeridos ?? 0} sugeridos`} color="orange"/><Metrica icon={ClipboardCheck} titulo="Adherencia general" valor={`${m.seguimiento.adherencia_promedio ?? 0}%`} detalle={`${m.seguimiento.pacientes_baja_adherencia ?? 0} pacientes bajo 60%`} color={(m.seguimiento.adherencia_promedio ?? 0) >= 70 ? 'green' : 'red'}/></section>

        <section className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]">
            <article className="rounded-2xl border border-surface-border p-5 dark:border-surface-border-dark"><Titulo icon={AlertTriangle} titulo="Alertas del sistema" subtitulo="Situaciones que requieren supervisión" color="orange"/>{m.alertas_admin.length ? <div className="mt-4 space-y-2">{m.alertas_admin.slice(0, 5).map((a, i) => <div key={`${a.categoria}-${i}`} className="flex items-start gap-3 rounded-xl border border-surface-border/70 p-3 dark:border-surface-border-dark"><span className={clsx('mt-1 h-2 w-2 shrink-0 rounded-full', a.severidad === 'alta' ? 'bg-category-fruits' : a.severidad === 'media' ? 'bg-brand-orange' : 'bg-info')}/><div><p className="text-[11.5px] font-bold">{a.titulo}</p><p className="mt-0.5 text-[10px] leading-relaxed text-ink-muted">{a.mensaje}</p></div></div>)}</div> : <div className="mt-4 flex items-center gap-2 rounded-xl bg-brand-green/5 p-4 text-[11px] font-semibold text-brand-green-dark dark:text-brand-green"><CheckCircle2 size={16}/> No existen alertas administrativas activas.</div>}</article>
            <article className="rounded-2xl border border-surface-border p-5 dark:border-surface-border-dark"><Titulo icon={Activity} titulo="Actividad reciente" subtitulo="Movimientos relevantes de los últimos días" color="blue"/><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><Dato label="Pacientes nuevos · 30 días" valor={m.actividad.pacientes_registrados_ultimos_30_dias}/><Dato label="Planes generados · 30 días" valor={m.actividad.planes_generados_ultimos_30_dias}/><Dato label="Recomendaciones · 30 días" valor={m.actividad.recomendaciones_generadas_ultimos_30_dias}/><Dato label="Seguimientos de comidas · 7 días" valor={m.actividad.seguimientos_comidas_ultimos_7_dias}/><Dato label="Registros de síntomas · 7 días" valor={m.actividad.seguimientos_sintomas_ultimos_7_dias}/><Dato label="Próximas citas · 7 días" valor={m.actividad.citas_proximos_7_dias}/></div><Link href={route('admin.auditoria.actividad')} className="mt-4 inline-flex items-center gap-1 text-[11px] font-bold text-category-dairy">Ver registro completo <ChevronRight size={14}/></Link></article>
        </section>

        <section className="grid gap-5 lg:grid-cols-3"><ResumenModulo icon={Stethoscope} titulo="Diagnóstico endocrinológico" datos={[['PMOS confirmados',m.diagnosticos.pmos_confirmado],['PMOS en estudio',m.diagnosticos.pmos_en_estudio],['RI confirmada',m.diagnosticos.ri_confirmada],['RI no evaluada',m.diagnosticos.ri_no_evaluada]]}/><ResumenModulo icon={Salad} titulo="Planificación nutricional" datos={[['Planes totales',m.planes.total],['Aprobados',m.planes.aprobados],['Finalizados',m.planes.finalizados],['Recomendaciones pendientes',m.recomendaciones_expertas.pendientes]]}/><ResumenModulo icon={CalendarDays} titulo="Agenda general" datos={[['Citas hoy',m.citas.hoy],['Próximas',m.citas.proximas],['Realizadas',m.citas.realizadas],['Canceladas',m.citas.canceladas]]}/></section>

        <section className="rounded-2xl border border-surface-border p-5 dark:border-surface-border-dark"><p className="text-[10px] font-bold uppercase tracking-wider text-category-dairy">Módulos administrativos</p><h2 className="mt-1 text-[15px] font-bold">Gestión organizada por áreas</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Acceso icon={UserCog} titulo="Usuarios" detalle="Roles, estados y accesos" href={route('admin.users.index')}/><Acceso icon={Users} titulo="Pacientes" detalle="Expedientes registrados" href={route('admin.pacientes.index')}/><Acceso icon={ShieldCheck} titulo="Auditoría" detalle="Trazabilidad de pacientes" href={route('admin.auditoria.pacientes')}/><Acceso icon={Activity} titulo="Actividad" detalle="Eventos del sistema" href={route('admin.auditoria.actividad')}/><Acceso icon={DatabaseBackup} titulo="Respaldo" detalle="Descargar copia PostgreSQL" href={route('admin.base-datos.respaldo')}/></div></section>
    </main></AuthenticatedLayout>;
}

const colores = { green:'bg-brand-green/10 text-brand-green-dark dark:text-brand-green', orange:'bg-brand-orange/10 text-brand-orange', red:'bg-category-fruits/10 text-category-fruits', blue:'bg-info/10 text-info', purple:'bg-category-dairy/10 text-category-dairy' };
function Icono({icon:Icon,color}:{icon:typeof Users;color:keyof typeof colores}){return <div className={clsx('flex h-9 w-9 shrink-0 items-center justify-center rounded-xl',colores[color])}><Icon size={18}/></div>}
function Metrica({icon,titulo,valor,detalle,color}:{icon:typeof Users;titulo:string;valor:number|string;detalle:string;color:keyof typeof colores}){return <article className="rounded-2xl border border-surface-border p-4 dark:border-surface-border-dark"><Icono icon={icon} color={color}/><p className="mt-3 text-[9.5px] font-bold uppercase tracking-wider text-ink-muted">{titulo}</p><p className="mt-1 text-2xl font-bold">{valor}</p><p className="mt-1 text-[10.5px] text-ink-muted">{detalle}</p></article>}
function Titulo({icon,titulo,subtitulo,color}:{icon:typeof Users;titulo:string;subtitulo:string;color:keyof typeof colores}){return <div className="flex items-center gap-3"><Icono icon={icon} color={color}/><div><h2 className="text-[14px] font-bold">{titulo}</h2><p className="text-[10.5px] text-ink-muted">{subtitulo}</p></div></div>}
function Dato({label,valor}:{label:string;valor:number}){return <div className="rounded-xl bg-black/[.025] p-3 dark:bg-white/[.035]"><p className="text-xl font-bold">{valor ?? 0}</p><p className="mt-1 text-[9.5px] leading-relaxed text-ink-muted">{label}</p></div>}
function ResumenModulo({icon,titulo,datos}:{icon:typeof Users;titulo:string;datos:[string,number][]}){return <article className="rounded-2xl border border-surface-border p-5 dark:border-surface-border-dark"><div className="flex items-center gap-3"><Icono icon={icon} color="blue"/><h2 className="text-[13px] font-bold">{titulo}</h2></div><div className="mt-4 space-y-2">{datos.map(([k,v])=><div key={k} className="flex items-center justify-between border-b border-surface-border/50 pb-2 text-[11px] last:border-0 dark:border-surface-border-dark"><span className="text-ink-muted">{k}</span><b>{v ?? 0}</b></div>)}</div></article>}
function Acceso({icon,titulo,detalle,href}:{icon:typeof Users;titulo:string;detalle:string;href:string}){const contenido=<><Icono icon={icon} color="purple"/><div className="flex-1"><p className="text-[11.5px] font-bold">{titulo}</p><p className="text-[9.5px] text-ink-muted">{detalle}</p></div><ChevronRight size={14} className="text-ink-muted transition group-hover:translate-x-0.5"/></>;const clase="group flex items-center gap-3 rounded-xl border border-surface-border p-3.5 transition hover:border-category-dairy/35 dark:border-surface-border-dark";return href.includes('/respaldo')?<a href={href} className={clase}>{contenido}</a>:<Link href={href} className={clase}>{contenido}</Link>}
